### ISSUE TITLE
python: implementing interface property requires a `@property` declaration

### ISSUE THREAD

**Issue by rix0rrr** [aws/jsii#1027]
## :bug: Bug Report

To implement an interface property in Python, we have to do something like this:

```python
@jsii.implements(ec2.IPeer)
class SomeIP:
  def __init__(self):
    self._connections = ec2.Connections(peer=self)

  @property
  def connections(self):
    return self._connections

  # ...
```

This is not idiomatic. A Python programmer would expect to be able to do something like this:

```python
@jsii.implements(ec2.IPeer)
class SomeIP:
  def __init__(self):
    self.connections = ec2.Connections(peer=self)
```

From Python's PoV it behaves the same, so why should jsii be different?

(Nevermind about the `@jsii.implements()` of course...)

**Comment by garnaat** [comment]
Maybe it's just me but your first example does seem idiomatic to me.  That's the way I would implement it.  YMMV.

**Comment by rix0rrr** [comment]
Maybe I'm wrong. But consider that the failure mode here is not:

"If you do it wrong, your property happens to be read-write instead of read-only and that is bad form."

The failure mode is:

```
jsii.errors.JSIIError: Cannot read property '_securityGroupRules' of undefined
```

**Comment by garnaat** [comment]
Maybe the problem is that the current approach is too Pythonic.  The naive implementation would be to just create the instance variable in the constructor and that is what a lot of people would probably do and it will fail.
