### ISSUE TITLE
DotNet: user-defined classes implementing JSII interfaces must extend `Amazon.JSII.Runtime.Deputy.DeputyBase`

### ISSUE THREAD

**Issue by RomainMuller** [aws/jsii#1029]
### Affected Languages

- [ ] `TypeScript` or `Javascript`
- [ ] `Python`
- [ ] `Java`
- [X] .NET (`C#`, `F#`, ...)

### General Information
* **JSII Version:** 
* **Platform:**     

### What is the problem?
When implementing an interface in Dotnet, in order for the instance to be able to go to Javascript, the user must extend `Amazon.Jsii.Runtime.Deputy.DeputyBase`. Failure to do so is going to result in an error from the .NET runtime noting that it is unable to convert the argument to the correct representation.

This requirement can be alleviated (objects that inherit from `DeputyBase` would continue to operate normally once the requirement is lifted).

### Impact to CDK
* A type conversion error will occur when a user-defined class that implements a CDK interface is passed as an argument to another CDK API.
* _Workaround_: a user-defined class that does not extend a class from the CDK library needs to extend `Amazon.Jsii.Runtime.Deputy.DeputyBase`. The requirement for doing so will be removed in the future (this will **not** break implementations that have the DeputyBase parent).

**Comment by JCKortlang** [comment]
Still relevant
