### ISSUE TITLE
All jsii stack traces hidden by -verbose flag

### ISSUE THREAD

**Issue by SomayaB** [aws/jsii#1072]
_Originally posted by @ccfife in https://github.com/aws/cdk-ops/issues/394

Debugging across the jsii boundary was not always intuitive for Python developers to understand, and when asked, most participants reported ignoring the Node.js stack traces. Several participants noted that the most relevant debug error was the first message and said it got lost in the debug “spew”.

17/49 | 8:50:57 AM | CREATE_FAILED | AWS::ECS::TaskDefinition | GostOnECS_Fargate/TaskDef (GostOnECSFargateTaskDef47A9FF3F) Invalid 'cpu' setting for task. For more information, see the Troubleshooting section of the Amazon ECS Developer Guide. (Service: AmazonECS; Status Code: 400; Error Code: ClientException; Request ID: b72df6b7-82f2-11e9-a226-1f3aab31f0fb)*

"Beautiful! Error, would like to see this at the bottom of my screen. Had to scroll back pretty far [past all the jsii debug spew] to see it "

Q: How necessary is the jsii portion of the stack trace? Seems like UX study participants didn't find it that useful.

This is also true for .NET

**Comment by MrArnoldPalmer** [comment]
This is covered in #47 , we need to improve stack trace messaging across all target languages and try to trim information that is extraneous.
