### ISSUE TITLE
When a JSII interface has a name like `IFoo`, the generated .NET interface is named `IIFoo`

### ISSUE THREAD

**Issue by mpiroc** [aws/jsii#109]
We should detect the case where the interface already has the `I`- prefix, and skip adding an additional `I`- prefix in this case.

Open question: What if the interface is named something like `IAMFoo`? I.e. it begins with `I<capital letter>`, but the `I` isn't intended as a prefix.

**Comment by assyadh** [comment]
After talking with Romain, we chose to:

Not prefix with I anymore for interfaces that are NOT datatype. Only datatype interfaces should append an I.

**Comment by eladb** [comment]
Do we really need interfaces for data types? I was under the impression that in .NET we can express these data types without interfaces.

**Comment by assyadh** [comment]
See my comment here:

https://github.com/aws/jsii/blob/master/packages/jsii-pacmak/lib/targets/dotnet/dotnetgenerator.ts#L148

Right now for each interface we create the interface, the interface proxy and the interface datatype class (implementing the original interface).

In the case of a datatype (props), we could do with JUST the datatype, not implementing any interface.

Relates: https://github.com/aws/jsii/issues/480

Given that props objects are datatypes, they would live by themselves.

**Comment by eladb** [comment]
So if I understand correctly the answer is that we can get rid of interfaces for data types (formally known as “structs”). Correct?

**Comment by assyadh** [comment]
Yes

**Comment by fulghum** [comment]
@assyadh – so the work for this task now, is just to remove the generation of interfaces for struct/data classes?

**Comment by assyadh** [comment]
Yep. Just create a class with all the properties.

**Comment by assyadh** [comment]
After discussion with Romain at the bindings meeting, looks like the interfaces are here to stay. There is usecases of interfaces implementations that are allowed by the language. Removing them would be a deal breaker.

I'll let @RomainMuller  chime in on the specifics.

**Comment by RomainMuller** [comment]
The current state of things is that data types support multiple inheritance, which implies supporting interfaces in `dotnet`. Have to check whether we can disallow multiple inheritance, which would render interfaces unnecessary.

**Comment by assyadh** [comment]
After discussion with @RomainMuller , we can remove the added I in the interfaces as it JSII is already enforcing the I for an interface.
