### ISSUE TITLE
javadoc truncated on converting from Props -> Builder

### ISSUE THREAD

**Issue by nija-at** [aws/jsii#1094]
### Affected Languages

- [ ] `TypeScript` or `Javascript`
- [ ] `Python`
- [X] `Java`
- [ ] .NET (`C#`, `F#`, ...)

### What is the problem?

Compare FunctionProps.handler in [typescript](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-lambda.FunctionProps.html#handler) vs [java](https://docs.aws.amazon.com/cdk/api/latest/java/software/amazon/awscdk/services/lambda/FunctionProps.Builder.html#handler-java.lang.String-)

<img width="1036" alt="Screenshot 2019-12-07 at 17 01 43" src="https://user-images.githubusercontent.com/16217941/70382107-5d620780-1913-11ea-949d-9d9f5f01a998.png">

<img width="1309" alt="Screenshot 2019-12-07 at 17 01 19" src="https://user-images.githubusercontent.com/16217941/70382108-6226bb80-1913-11ea-8079-e56c71d3967f.png">

**Comment by RomainMuller** [comment]
This is because the second paragraph and further gets into a "remarks" section and is not in the "summary" section. Code generation appears to ignore remarks.
