### ISSUE TITLE
Design better strategy for dealing with type/namespace name conflicts in .NET

### ISSUE THREAD

**Issue by mpiroc** [aws/jsii#110]
`.NET` requires that a fully qualified type name not match a fully-qualified namespace name.

Our current strategy is to append `_` to the type name until there is no conflict. This might be a good strategy for avoiding occasional conflicts. But in some cases (including the CDK), there are hundreds of conflicts. Naming hundreds of types `MyType_` is not a good user experience.

**Comment by assyadh** [comment]
Closing as we use nested types now.
