### ISSUE TITLE
jsii-pacmak throws error when checking bundleDependencies due to returning false instead of an array

### ISSUE THREAD

**Issue by dheffx** [aws/jsii#1118]
### Affected Languages

- [X] `TypeScript` or `Javascript`
- [X] `Python`
- [X] `Java`
- [X] .NET (`C#`, `F#`, ...)

### General Information
* **JSII Version:**0.20.9 (build 41da907), typescript 3.7.3
* **Platform:**     Darwin xx 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64

### What is the problem?
I created a stub project with the AWS CDK (`cdk init --language typescript`) and then attempted to set up jsii for a hello-world.

This error is thrown when running `jsii-pacmak`. I dug into it a little and I see it returns a value of `false` rather than an array when evaluating the bundled dependencies. In this case, it threw it on `aws-cdk/cx-api` which has a `bundleDependencies` of `["semver"]`.

```typescript
const bundled = (_b = (_a = pkg.bundleDependencies, (_a !== null && _a !== void 0 ? _a : pkg.bundleDependencies)), (_b !== null && _b !== void 0 ? _b : []));
```

I'm not going to pretend I understand right now what that function is attempting to do, but I was able to get it to seemingly work with a local mod of (I haven't test that the output modules work in the other languages CDK)

```typescript
const bundled = pkg.bundleDependencies || [];
```

### Verbose Log
```
$ npm run package

> hello-jsii@0.1.0 package /xxxx/
> jsii-pacmak --verbose

[jsii-pacmak] [INFO] Found 1 modules to package
[jsii-pacmak] [INFO] Packaging NPM bundles
[jsii-pacmak] [INFO] Loading jsii assemblies and translations
TypeError: bundled.includes is not a function
    at TypeSystem._loadModule ( /hello-jsii/node_modules/jsii-reflect/lib/type-system.js:101:29)
    at async TypeSystem._loadModule ( /hello-jsii/node_modules/jsii-reflect/lib/type-system.js:108:17)
    at async TypeSystem.loadModule (/hello-jsii/node_modules/jsii-reflect/lib/type-system.js:68:21)
    at async JsiiModule.load (/hello-jsii/node_modules/jsii-pacmak/lib/packaging.js:47:26)
    at async /hello-jsii/node_modules/jsii-pacmak/bin/jsii-pacmak.js:128:13
    at async Promise.all (index 0)
    at async Timers.recordAsync (/hello-jsii/node_modules/jsii-pacmak/lib/timer.js:58:23)
    at async main (/hello-jsii/node_modules/jsii-pacmak/bin/jsii-pacmak.js:124:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hello-jsii@0.1.0 package: `jsii-pacmak --verbose`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the hello-jsii@0.1.0 package script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /hello-jsii/.npm/_logs/2019-12-13T01_14_31_492Z-debug.log
```

**Comment by RomainMuller** [comment]
This was actually fixed as we discovered the same :) Thanks for reporting anyway!
