### ISSUE TITLE
Stop relying on synchronous reads from STDIN

### ISSUE THREAD

**Issue by RomainMuller** [aws/jsii#1142]
### Affected Languages

- [ ] `TypeScript` or `Javascript`
- [X] `Python`
- [X] `Java`
- [X] .NET (`C#`, `F#`, ...)

### What is the problem?
`node` opens it's STDIN file descriptor in `O_NONBLOCK` mode, making attempts to synchronously read unsafe. Starting with node `13.2`, there has been a significant increase in the incidence of hitting EAGAIN in this process. Synchronous mitigations are tacky at best, and the proper way to fix is to move away from synchronous IO.

See aws/aws-cdk#5187

**Comment by eladb** [comment]
I don't think it will be possible to move away from synchronous reads since you need to invoke host callbacks during synchronous javascript function calls, so you need to block the javascript execution.

**Comment by eladb** [comment]
Can you also provide a reference to the node.js documentation that says that stdin is opened with O_NONBLOCK. From https://github.com/joyent/libuv/commit/1988f5e is seems like it's actually opened without O_NONBLOCK

**Comment by RomainMuller** [comment]
> Can you also provide a reference to the node.js documentation that says that stdin is opened with O_NONBLOCK? From [joyent/libuv@1988f5e](https://github.com/joyent/libuv/commit/1988f5e) is seems like it's actually opened without O_NONBLOCK

The code you are pointing at is the code that initializes the STDIN/OUT for child processes, which was introduced around nodejs/node-v0.x-archive#3994, where people very specifically call out that, unlike `node`, most other programs don't have a non-blocking STDIN and hit problems when they do.

**Comment by RomainMuller** [comment]
That being said, I think you're correct about it not being possible to make this process synchronous (or it'd require the application's code performs NO asynchronous operation ever).
