### ISSUE TITLE
"Ignoring FunctionDecleration" warning is missing context

### ISSUE THREAD

**Issue by eladb** [aws/jsii#1174]
## :bug: Bug Report

I am seeing the following warning, but it lacks any information as to which function is being ignored:

```
JSII: Ignoring FunctionDeclaration node (it cannot be represented int he jsii type model)
```

### General Information
* **JSII Version:** 0.21.1 (build 9ff44cb), typescript 3.7.4
* **Platform:**    Darwin 8c859031ce16.ant.amazon.com 19.2.0 Darwin Kernel Version 19.2.0: Sat Nov  9 03:47:04 PST 2019; root:xnu-6153.61.1~20/RELEASE_X86_64 x86_64

### What is the problem?

I can't understand which function is being ignored.

**Comment by RomainMuller** [comment]
Yeah. It appears that entries reported with the "Message" severity are not showing their context ties in the output formatter.

One way to fix is to make those warnings instead (I'm self-debating whether these are, in fact, warnings; or not).
