### ISSUE TITLE
Python typings fail to recognize implemented interfaces

### ISSUE THREAD

**Issue by eladb** [aws/jsii#1262]
### Affected Languages

- [ ] `TypeScript` or `Javascript`
- [x] `Python`
- [ ] `Java`
- [ ] .NET (`C#`, `F#`, ...)

### General Information
* **JSII Version:** 0.22
* **Platform:**     Mac

### What is the problem?

I get the error `expected type 'IXxx', got Yyy` even though `Yyy` implements `IXxx`.

For example:

<img width="679" alt="Screen Shot 2020-02-16 at 17 06 49" src="https://user-images.githubusercontent.com/598796/74607145-d71a2c80-50de-11ea-9744-0c419078fbba.png">

**Comment by chkothe** [comment]
Also related to https://github.com/aws/aws-cdk/issues/7143

**Comment by mrgrain** [comment]
closing in favor of https://github.com/aws/jsii/issues/3931
