### ISSUE TITLE
Submodules

### ISSUE THREAD

**Issue by eladb** [aws/jsii#1286]
### Affected Languages

- [x] `TypeScript` or `Javascript`
- [x] `Python`
- [x] `Java`
- [x] .NET (`C#`, `F#`, ...)

### Description

We are looking into releasing the entire AWS CDK as a single module (see https://github.com/aws/aws-cdk-rfcs/pull/122).

In order to be able to organize the namespace of that huge single module we need a way to group types into "submodules".

The current way these types are exported is:

```ts
import * as aws_s3 from './aws-s3';
export aws_s3;

import * as aws_sns from './aws-sns';
export aws_sns;
```

This offers a good experience in TypeScript:

```ts
import { aws_s3, aws_sns } from 'monocdk';

new aws_s3.Bucket(this, ...);
```

We need this to translate properly to all supported jsii languages.

### Proposed Solution

A few things to consider:

1. What are we doing with submodule README files? How do we model them inside the jsii manifest? Maybe we need an entry for the submodule itself.
2. Ideally we want to be able to control the name of the submodule per-language. For example, Java submodules should translate into java package names, and we wish to keep the java package names in tact as we bundle all of the code into a single JAR. This means that we can't just use the name of the TypeScript submodule but rather need some form of translation table. It could be a custom jsdocs  attribute such as `@java.package foo.bar.foo`.

**Comment by CaerusKaru** [comment]
We could add a pacmak.json configuration which would allow for per-package name manipulation as well as any other package-level info needed for other languages but not necessarily for Node/NPM.
