### ISSUE TITLE
JSII crashes if a " " is present in the JsiiRuntimePath path

### ISSUE THREAD

**Issue by gregswdl** [aws/jsii#1296]
### Affected Languages

- [ ] `TypeScript` or `Javascript`
- [ ] `Python`
- [ ] `Java`
- [X] .NET (`C#`, `F#`, ...)

### General Information
* **JSII Version:** 0.22.0
* **Platform:**     Windows 10 Pro

### What is the problem?

This issue was discovered trying to use the CDK, however I believe it is ultimately in JSII. As stated above, I'm running the .NET Core 3 version on Windows 10. My Windows login is my full name, Greg Smith. The issue is that my temp dir path is `C:\Users\Greg Smith\AppData\Local\Temp` and when the node process is run with the JSII package, node will crash with 
```
Unhandled exception. Amazon.JSII.Runtime.JsiiException: Child process exited unexpectedly: internal/modules/cjs/loader.js:638
```
I was able to trace the issue down to the [`ProcessStartInfo`][1] object. The arguments simply attach the JsiiRuntimePth from the provider and spaces are interpreted as a new argument by node, equivelant to the following:
```
C:\Users\Greg Smith>node --max-old-space-size=4096 C:\Users\Greg Smith\AppData\Local\Temp\zmqnhp2i.n2w\jsii-runtime.js
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'C:\Users\Greg'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```

However, wrapping with quotes yeilds:
```
C:\Users\Greg Smith>node --max-old-space-size=4096 "C:\Users\Greg Smith\AppData\Local\Temp\zmqnhp2i.n2w\jsii-runtime.js"
{"hello":"@jsii/runtime@0.22.0"}
```
[1]: https://github.com/aws/jsii/blob/958fbab4788664202861b09b857e385b54d1bac0/packages/%40jsii/dotnet-runtime/src/Amazon.JSII.Runtime/Services/NodeProcess.cs#L33

### Verbose Log

[gist][2] of log

[2]: https://gist.github.com/gregswdl/5f81ebde920cfbd7dffa8b2e7c525162

**Comment by gregswdl** [comment]
Note, as a temporary workaround you can set your TMP path to something without spaces, eg
```PS
PS C:\> $env:TMP = "C:\tmp"
```

**Comment by ashovlin** [comment]
Could we reopen this if it hasn't been resolved?

I work on https://github.com/aws/aws-dotnet-deploy, which generates CDK projects based on user's .NET applications. My hunch is we have a higher likelihood of users on Windows than the other language bindings.

We provide an [environment variable](https://aws.github.io/aws-dotnet-deploy/docs/getting-started/custom-workspace/) to let users override the path where our tool is generating the CDK projects, but it's still a sharp edge. Here's an example from [last week](https://github.com/aws/aws-toolkit-visual-studio/issues/358).
