### ISSUE TITLE
Python docs linking to incorrect types

### ISSUE THREAD

**Issue by MrArnoldPalmer** [aws/jsii#1300]
### Affected Languages

- [ ] `TypeScript` or `Javascript`
- [x] `Python`
- [ ] `Java`
- [ ] .NET (`C#`, `F#`, ...)

### General Information
* **JSII Version:** 1.0.0

### What is the problem?

In some places the Python docs website links to types with same name, but from different modules.

ie: https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_s3/Bucket.html#aws_cdk.aws_s3.Bucket.__init__

The link for `LifecycleRule` type under `lifecycle_rules` parameter links to [ECR LifecycleRule](https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_ecr/LifecycleRule.html#aws_cdk.aws_ecr.LifecycleRule) instead of [S3 LifecycleRule](https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_s3/LifecycleRule.html).

Possibly related to https://github.com/aws/jsii/issues/474

**Comment by RomainMuller** [comment]
Confirmed fixed at the same time as #474
