### ISSUE TITLE
Support for language specific iterators

### ISSUE THREAD

**Issue by philcali** [aws/jsii#1302]
### Affected Languages

- [ ] `TypeScript` or `Javascript`
- [X] `Python`
- [X] `Java`
- [X] .NET (`C#`, `F#`, ...)

### General Information
* **JSII Version:** `j1.0.0 (build eb2db9d), typescript 3.7.5`
* **Platform:**     `Linux penguin 4.19.79-07511-ge32b3719f26b #1 SMP PREEMPT Mon Nov 18 17:41:41 PST 2019 x86_64 GNU/Linux` (UNIX) 

* [X] I may be able to implement this feature request
* [ ] This feature might incur a breaking change

### Description

I would like for JSII to be able to translate Typescript [Iterators][1] into a language proxy that calls into the JSII runtime for more information via `next` and `hasNext` equivalents. This will allow language specific code to wrap those iterator proxies with lazy loading techniques for pulling large datasets from the child process. For where it matters, the generics rule can still apply to languages that support generics in the same way `Array` is supported.

__Note__: There is totally a workaround that exists for this. Nothing is stopping the JSII library owner to vend an "IteratorLike" object that can be translated by language specific modules. This request proposes that JSII should own that translation.

[1]: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-6.html

### Proposed Solution

I may define an iterator like this:

``` typescript
class ThingIterator implements Iterator<Thing> {
    next() {
        return { next: this.fetchedThing(), done: this.sDone() };
    }
}
```

The JSII code generators will generate a proxy `ThingIterator` that implements the correct language specific iterator, but calls into the JSII runtime to invoke the `next` method to determine if it can be terminated.

I'm hand-waving a fair amount of details here, and I don't even know if such a thing is even possible today. That said: I'm totally willing to spend some spare cycles getting my hands dirty implementing this.

Thanks!

**Comment by RomainMuller** [comment]
That's an interesting request! I'm not sure we'll be able to attend to it shortly, but I am interested in the general pattern. There are definitely other interesting things to be able to re-model across, such as `Set<T>`. I had never thought about `Iterator<T>` (and maybe `Iterable<T>`?), but that certainly sounds like something that could be useful.

**Comment by philcali** [comment]
Awesome! Thanks for taking a look!
