### ISSUE TITLE
Generated Python not respecting null check

### ISSUE THREAD

**Issue by Brian-Triplett** [aws/jsii#1317]
### Affected Languages

- [ ] `TypeScript` or `Javascript`
- [X] `Python`
- [ ] `Java`
- [ ] .NET (`C#`, `F#`, ...)

### General Information
* **JSII Version:** 1.0.0
* **Platform:**     Darwin 19.3.0

### What is the problem?
I packaged an s3 wrapper that looks like this

```ts
import s3 = require('@aws-cdk/aws-s3');
import cdk = require('@aws-cdk/core');

export class Bucket extends s3.Bucket {
  /**
   *
   * @param stack The stack in which the bucket should be created.
   * @param name The bucket name
   * @param props Bucket properties.  If not provided, default properties will be used.
   * default properties include:
   */
  constructor(stack: cdk.Construct, name: string, props?: s3.BucketProps) {
    if (props) {
      super(stack, name, props);
    } else {
      super(stack, name, {
        bucketName: name,
        removalPolicy: cdk.RemovalPolicy.DESTROY,
        blockPublicAccess: s3.BlockPublicAccess.BLOCK_ALL,
      });
    }
  }
}
```

I then package it with jsii into a *.whl file for use in python. I then pip install it into another python cdk project and use it in a python class like this:

```python
from aws_cdk import core
import my.aws_cdk

class MyCdkTestStack(my.aws_cdk.Stack):

    def __init__(self, scope: core.Construct, id: str, **kwargs) -> None:
        super().__init__(scope, id, **kwargs)

        my.aws_cdk.Bucket(self, "test-cdk")
```

but upon deploying or running `cdk synth` the bucket policy is still set to "Retain". It's almost like that if/else in the constructor is just being ignored. Does the python translation not work with "truthy" checks? Does it need something more specific? 

### Verbose Log
[jsii-pacmak] [INFO] Found 1 modules to package
[jsii-pacmak] [INFO] Packaging NPM bundles
[jsii-pacmak] [INFO] Loading jsii assemblies and translations
[jsii-pacmak] [INFO] Packaging 'python' for @my/aws-cdk
[jsii-pacmak] [INFO] Packaging 'dotnet' for @my/aws-cdk
[jsii-pacmak] [INFO] Packaging 'js' for @my/aws-cdk
[jsii-pacmak] [INFO] js finished
[jsii-pacmak] [WARN] Unable to validate distribution packages because `twine` is not present. Run `pip3 install twine` to enable distribution package validation.
[jsii-pacmak] [INFO] python finished
[jsii-pacmak] [INFO] dotnet finished
[jsii-pacmak] [INFO] Packaged. npm pack (12.2s) | dotnet (11.6s) | load jsii (3.6s) | python (1.5s) | js (0.1s) | cleanup (???)

**Comment by MrArnoldPalmer** [comment]
So I believe whats happening here, is what is actually being passed as the 3rd argument to the constructor in NodeJS is `{}`, which is truthy. This is a result of the way we convert from an object in JS, to a list of keyword args in python. If all optional keyword args are `None`, this results in an empty object. I think you can workaround by changing your constructor to
```typescript
  constructor(stack: cdk.Construct, name: string, props: s3.BucketProps = {}) {
      super(stack, name, {
        bucketName: name,
        removalPolicy: cdk.RemovalPolicy.DESTROY,
        blockPublicAccess: s3.BlockPublicAccess.BLOCK_ALL,
        ...props
      });
  }
```

**Comment by Brian-Triplett** [comment]
I converted the constructor to this:

```ts
  constructor(stack: cdk.Construct, name: string, props: s3.BucketProps = {}) {
    super(stack, name, {
      bucketName: name,
      removalPolicy: cdk.RemovalPolicy.DESTROY,
      blockPublicAccess: s3.BlockPublicAccess.BLOCK_ALL,
      ...props,
    });
  }
```

repacked it with jsii, re-pip-installed it in the python project and still getting the same result :/

**Comment by MrArnoldPalmer** [comment]
@Brian-Triplett can you verify that the change to the constructor is available in the JS code that gets bundled with the generated pip module?

If you're still running into that issue do you mind creating a minimal reproduction repo?

**Comment by Brian-Triplett** [comment]
It looks like it is, working ow to setup a reproduction repo.

```js
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const s3 = require("@aws-cdk/aws-s3");
const cdk = require("@aws-cdk/core");
class Bucket extends s3.Bucket {
    /**
     *
     * @param stack The stack in which the bucket should be created.
     * @param name The bucket name
     * @param props Bucket properties.  If not provided, default properties will be used.
     * default properties include:
     */
    constructor(stack, name, props = {}) {
        super(stack, name, {
            bucketName: name,
            removalPolicy: cdk.RemovalPolicy.DESTROY,
            blockPublicAccess: s3.BlockPublicAccess.BLOCK_ALL,
            ...props,
        });
    }
}
exports.Bucket = Bucket;```

**Comment by Brian-Triplett** [comment]
@MrArnoldPalmer I setup a repro repo (which is fun to say). Here it is: I hope I didn't mess it up when slimming it down but I was seeing the same behavior with this repo as before.

https://github.com/Brian-Triplett/jsii-issue-1317

**Comment by MrArnoldPalmer** [comment]
Awesome! I'll check this out and see if we can workaround.

**Comment by Brian-Triplett** [comment]
Has anyone come up with a workaround for this one? I'm happy to adjust the way we're implementing it in Typescript

**Comment by MrArnoldPalmer** [comment]
@Brian-Triplett I just pulled and used your repo.

```typescript
import s3 = require('@aws-cdk/aws-s3');
import cdk = require('@aws-cdk/core');

export class Bucket extends s3.Bucket {
  /**
   *
   * @param stack The stack in which the bucket should be created.
   * @param name The bucket name
   * @param props Bucket properties.  If not provided, default properties will be used.
   * default properties include:
   */
  constructor(stack: cdk.Construct, name: string, props: s3.BucketProps = {}) {
    super(stack, name, {
      bucketName: name,
      removalPolicy: cdk.RemovalPolicy.DESTROY,
      blockPublicAccess: s3.BlockPublicAccess.BLOCK_ALL,
      ...props
    });
  }
}
```

Correctly outputs the default params as intended.

```python
class CdkAppStack(core.Stack):

    def __init__(self, scope: core.Construct, id: str, **kwargs) -> None:
        super().__init__(scope, id, **kwargs)

        jsii_test.Bucket(self, "test-bucket-name")
```

template output
```yaml
{
  "Resources": {
    "testbucketname086F697F": {
      "Type": "AWS::S3::Bucket",
      "Properties": {
        "BucketName": "test-bucket-name",
        "PublicAccessBlockConfiguration": {
          "BlockPublicAcls": true,
          "BlockPublicPolicy": true,
          "IgnorePublicAcls": true,
          "RestrictPublicBuckets": true
        }
      },
      "UpdateReplacePolicy": "Delete",
      "DeletionPolicy": "Delete",
      "Metadata": {
        "aws:cdk:path": "cdk-app/test-bucket-name/Resource"
      }
    }
  }
}
```

**Comment by Brian-Triplett** [comment]
Maybe it's something the the steps I'm using to generate the .whl? Which version of cdk and jsii did you use?

**Comment by MrArnoldPalmer** [comment]
@Brian-Triplett I used jsii v0.22.0, with cdk v1.28.0. jsii v1 isn't compatible with cdk v1.28.0. (we are working on a release now that upgrades to jsii v1.1.0)

I ran `npm install && npm build && npm package`. Then I went into the cdk_app directory and did `pip3 install -r requirements.txt` and `pip3 install ../dist/python/brian-triplett.jsii-issue-1137-0.0.1.tar.gz`. Then I ran `cdk synth`.

Could be you have some build cache somewhere or something along those lines.

**Comment by Brian-Triplett** [comment]
Sure enough that was it. I didn't uninstall the .whl file correctly before so the changes weren't coming through after I modified the code as you originally suggested. It's working as expected now!

I'm good to close this one out. The lesson learned is we need to use the constructor pattern you proposed above. Thanks!

**Comment by MrArnoldPalmer** [comment]
Awesome! Glad this worked out.

Weirdness around conversion between an object in JS and kwargs in python is a rough edge. There may be some further action we can take during codegen to minimize this. I'll noodle on that for the future. 🤔
