### ISSUE TITLE
Generate type validation code

### ISSUE THREAD

**Issue by iliapolo** [aws/jsii#1321]
## :rocket: Feature Request

Add type validation code to dynamic languages. 

### Affected Languages

- [X] `TypeScript` or `Javascript` (Javascript)
- [X] `Python`
- [ ] `Java`
- [ ] .NET (`C#`, `F#`, ...)

### General Information
* **JSII Version:** 0.22.0 (build 14afdde), typescript 3.7.5
* **Platform:**     Darwin a483e7b9e4e1.ant.amazon.com 18.7.0 Darwin Kernel Version 18.7.0: Thu Jan 23 06:52:12 PST 2020; root:xnu-4903.278.25~1/RELEASE_X86_64 x86_64

* [X] I may be able to implement this feature request

* [ ] This feature might incur a breaking change

### Description

We currently have quite a few issues coming from users who mistakenly pass L1 objects to L2 constructs. 

For example: https://github.com/aws/aws-cdk/issues/6540

These types of errors are not presented in typed languages because they actually cause a compile time error. It would be nice to provide a similar experience in dynamic languages as well. 

### Proposed Solution

JSII can generate some sort of type validation code in the proxy objects, something like:

```python
@jsii.data_type(jsii_type="@aws-cdk/aws-cloudfront.S3OriginConfig", jsii_struct_bases=[], name_mapping={'s3_bucket_source': 's3BucketSource', 'origin_access_identity': 'originAccessIdentity'})
class S3OriginConfig():
    def __init__(self, *, s3_bucket_source: aws_cdk.aws_s3.IBucket, origin_access_identity: typing.Optional["IOriginAccessIdentity"]=None):
        """S3 origin configuration for CloudFront.

        :param s3_bucket_source: The source bucket to serve content from.
        :param origin_access_identity: The optional Oriagin Access Identity of the origin identity cloudfront will use when calling your s3 bucket. Default: No Origin Access Identity which requires the S3 bucket to be public accessible

        stability
        :stability: experimental
        """

        # type validation
        if not isinstance(origin_access_identity, IOriginAccessIdentity):
            raise RuntimeError('Illegal argument type...)

        self._values = {
            's3_bucket_source': s3_bucket_source,
        }
        if origin_access_identity is not None: self._values["origin_access_identity"] = origin_access_identity
```

**Comment by RomainMuller** [comment]
I don't think this is a breaking change (it'd prohibit cases that won't have worked).

I also believe we should start off by issuing warnings instead of breaking the run-time (which makes it even less breaking). Possibly have an environment-controlled "strict" mode that throws instead of warning.

**Comment by iliapolo** [comment]
> I don't think this is a breaking change (it'd prohibit cases that won't have worked).

Isn't it possible that there exists cases with "accidental" compatibility? Where the property names just happen to match?

> I also believe we should start off by issuing warnings

I agree this would prevent the breakage, at the first iteration anyway.

**Comment by eladb** [comment]
dup with https://github.com/aws/jsii/issues/75?

**Comment by RomainMuller** [comment]
@eladb - it's related, but I think adding checks in Python code can be delivered faster and stop the "bleeding".
