### ISSUE TITLE
Add compile check for interface down-cast without explicit implementation

### ISSUE THREAD

**Issue by eladb** [aws/jsii#140]
Repro:

```ts
class MyClass {
  foo: number
}

interface Fooable {
  foo: number;
}

var f: Fooable = new MyClass() as Fooable;
```

This works in TypeScript but will fail (at runtime) in Java.

See: awslabs/aws-cdk#504, awslabs/aws-cdk#505

**Comment by RomainMuller** [comment]
Technically we have access to everything, so it *can* be done. But it won't be trivial for sure.
