### ISSUE TITLE
Document licensing considerations around generated packages

### ISSUE THREAD

**Issue by RomainMuller** [aws/jsii#1671]
### Affected Languages

- [ ] `TypeScript` or `Javascript`
- [X] `Python`
- [X] `Java`
- [X] .NET (`C#`, `F#`, ...)

### Description
There is currently no documentation informing users about any licensing quirks (or absence thereof) that apply to the code generated by jsii. In particular, it's not clear to users whether attribution is necessary; or if the generated code contains any bundled OSS that they would need to worry about the licenses of / attribute to.

**Comment by RomainMuller** [comment]
The current state of things is that:
* `jsii-pacmak` generates code based on the API outline produced from `jsii` compiling the TypeScript, and slaps it with the same license than the source TypeScript/Node module. I'm not certain whether this requires any kind of attribution from the authors to `jsii`
* `jsii-pacmak` generates code that does not bundle any other OSS product (at time of writing anyway). It includes dependency declarations that will cause other OSS products to be resolved on the users' computers upon installing a jsii generated module (e.g: Maven dependencies modeled in the package's `pom.xml` file, etc..). Those dependencies are not re-distributed and thus my understanding is they shouldn't require attribution.

**Comment by RomainMuller** [comment]
Sorry - nothing yet.

**Comment by RomainMuller** [comment]
Alright - packages generated by `jsii-pacmak` are licensed under the very same license that applies to the original npm library. It is however the author's responsibility to make sure that any licenses that attach to the original library are also applied to the output (for example - that any attributions document necessary is bundled in the npm package, etc...).

I'll be adding this to the documentation whenever I get two minutes :)

**Comment by ddneilson** [comment]
Cool. So, to be clear, `jsii-pacmak` does bundle up all of the dependencies of the npm package when publishing into other languages (ex: Python, Java, C#), correct? So, the NOTICE file must include all dependencies as distributions since the package *is* actually distributing them.

**Comment by RomainMuller** [comment]
Licensing considerations are now documented [here](https://aws.github.io/jsii/user-guides/lib-author/configuration/#important-license-information)
