### ISSUE TITLE
Extending interface with Omit<T, K> helper returns TypeError: Cannot read property 'parent' of undefined

### ISSUE THREAD

**Issue by leandropadua** [aws/jsii#1703]
I would like to override an interface property and I was trying that using `Omit`

```typescript
import * as s3 from '@aws-cdk/aws-s3';

export interface SecureBucketProps extends Omit<s3.BucketProps,'encryption'> {
  readonly encryption: s3.BucketEncryption.KMS | s3.BucketEncryption.KMS_MANAGED;
}
```
I get the following error when building with `jsii`:
> [ERROR] jsii/compiler - Error during type model analysis: TypeError: Cannot read property 'parent' of undefined

Initially I was doing simply:
```typescript
export interface SecureBucketProps extends s3.BucketProps {
  readonly encryption: s3.BucketEncryption.KMS | s3.BucketEncryption.KMS_MANAGED;
}
```
but that is not possible and give me this error instead:
>[ERROR] jsii/compiler - Type model errors prevented the JSII assembly from being created
lib/index.ts:3:1 - error TS9999: JSII: Interface declares same member as inherited interface: encryption

Any ideas on how to go around it?

Thank you

### General Information
* **JSII Version:** 1.5.0 (build 46538f8), typescript 3.8.3
* **Platform:**     macOS Darwin Kernel Version 18.2.0

**Comment by GriffinMB** [comment]
If you haven't found the TypeScript limitations page, you may find it useful: https://github.com/aws/jsii/blob/master/docs/typescript-restrictions.md

It seems like your current issue is due to the use of `Omit<T,K>`. JSII does not support Generics aside from Arrays or Promises. As you note, directly extending and type-narrowing doesn't work either. 

AFAIK, the only options are to redefine the interface for jsii compatibility, or to not use jsii.

**Comment by leandropadua** [comment]
Thanks for clarifying that @GriffinMB 
I will close this issue as it's working as expected.

**Comment by leandropadua** [comment]
Hi @GriffinMB , have you seen the [new covariant return for c#](https://devblogs.microsoft.com/dotnet/c-9-0-on-the-record/#covariant-returns)?  Can it be a solution for this problem too? I have created a feature request in a new issue to see if we can remove some of that limitation already. 
https://github.com/aws/jsii/issues/2314
Thanks
