### ISSUE TITLE
jsii build succeeds when using Omit<T, K>

### ISSUE THREAD

**Issue by nija-at** [aws/jsii#1707]
### What is the problem?

jsii does not support the [`Omit` type](https://www.typescriptlang.org/docs/handbook/utility-types.html#omittk) but jsii build does not fail. It's likely that the jsii compiler is ignoring the `Omit` type.

Props class uses `Omit` utility type - [PR commit](https://github.com/aws/aws-cdk/pull/8281/commits/5771bcb56d93b823365751f7e25509df2093947f#diff-f869db0e3fd8a48f38c33737566ebf70)

Successful build (account: 260708760616) - https://us-east-1.console.aws.amazon.com/codesuite/codebuild/260708760616/projects/AutoBuildProject6AEA49D1-qxepHUsryhcu/build/AutoBuildProject6AEA49D1-qxepHUsryhcu%3A531f3f72-e613-425b-b692-c041b756d515?region=us-east-1

**Comment by hoegertn** [comment]
Is there any chance to support Omit in the future?

**Comment by blimmer** [comment]
@mrgrain pointed me at https://github.com/mrgrain/jsii-struct-builder, which could help others looking to `Omit`
