### ISSUE TITLE
Add test to ensure that .NET spec stays in sync with JSII spec

### ISSUE THREAD

**Issue by mpiroc** [aws/jsii#171]
Json.NET supports [generating json schemas from .NET types](https://www.newtonsoft.com/jsonschema/help/html/GeneratingSchemas.htm).

We should write a test that generates a json schema from `Amazon.JSII.JsonModel.Spec`, and compares it to the schema generated by `jsii-spec`.

**Comment by mpiroc** [comment]
While we're at it, we should move `Amazon.JSII.JsonModel.Api` into `Amazon.JSII.Runtime` (because it isn't used by `Amazon.JSII.Generator`), and rename `jsii-dotnet-jsonmodel`/`Amazon.JSII.JsonModel` to `jsii-dotnet-spec`/`Amazon.JSII.Spec`.

**Comment by MrArnoldPalmer** [comment]
@RomainMuller how does this fit into the current work on the JSII spec and the compliance suite. Seems like we could do this in addition but most of what it verifies would already be covered. Seems like another relatively inexpensive to implement layer of verification though.

**Comment by RomainMuller** [comment]
To be frank it might be sweet to get that code-generated from the JSON Schema or something. Manually keeping in sync is busy work that does not add much value.

**Comment by MrArnoldPalmer** [comment]
Lets link this to development of the greater DotNet compliance suite. We can look into automating this with the rest of the compliance tool set we build.
