### ISSUE TITLE
structs with variable field names are allowed

### ISSUE THREAD

**Issue by rix0rrr** [aws/jsii#1723]
### Affected Languages
- [ ] `TypeScript` or `Javascript`
- [x] `Python`
- [x] `Java`
- [x] .NET (`C#`, `F#`, ...)

### What is the problem?

TypeScript allows arbitrary "unknown" fields in an interface definition:

```ts
export interface SomeInterface {
  [key: string]: SomeType
}
```

The previous definition behaves much the same as the following would have:

```ts
export type SomeInterface = {[key: string]: SomeType};
```

The latter was probably similar to what was intended, but in TypeScript those types behave the same.

However, when JSII parses the former, it produces a `struct` (correct) with 0 properties (arguable?).

The end result is that there is an API disparity where for TypeScript/JavaScript users everything seems okay, but jsii users are not able to pass any data.

This has happened in real life already: https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-stepfunctions-tasks/lib/dynamodb/call-dynamodb.ts#L76-L78 , and the type defined there is now not usable over jsii.

Proposed solution: reject `[key: string]: SomeType` when it occurs in interface definitions.

**Comment by RomainMuller** [comment]
Yep, that should definitely be rejected.
