### ISSUE TITLE
jsii compiler should error when @internal types attempt to expose public methods

### ISSUE THREAD

**Issue by nija-at** [aws/jsii#1734]
## :rocket: Feature Request

An @internal type that is inherited into a public type must not implement public APIs that are not already declared as a public API (via an interface or such).

This results in a situation where the public API(s) are not actually available, which is unintended.

Example:
[`RestApi` inherits](https://github.com/aws/aws-cdk/blob/ae3b59f0fb5199c527c598ddb7e11b3b7d721028/packages/%40aws-cdk/aws-apigateway/lib/restapi.ts#L301) an `@internal` type [`RestApiBase`](https://github.com/aws/aws-cdk/blob/ae3b59f0fb5199c527c598ddb7e11b3b7d721028/packages/%40aws-cdk/aws-apigateway/lib/private/restapi-base.ts) which declares a new (previously undeclared) public API [`domainName`](https://github.com/aws/aws-cdk/blob/ae3b59f0fb5199c527c598ddb7e11b3b7d721028/packages/%40aws-cdk/aws-apigateway/lib/private/restapi-base.ts#L100).

The error message from a consuming API is so -

```
lib/api-gateway-domain-name.ts:30:14 - error TS2339: Property 'domainName' does not exist on type 'RestApi'.

30     if (!api.domainName) {
                ~~~~~~~~~~
```

**Comment by RomainMuller** [comment]
I guess alternatively, `public` APIs introduced on erased types must be "moved up" to the visible types.

**Comment by nija-at** [comment]
Feels like a poorer experience / unintended side effect
If it was intended to be 'moved up', might as well do it explicitly at source rather than being implicit.

**Comment by RomainMuller** [comment]
@nija-at I am thinking of this as a way to sugar up adding public methods to all children, but after reading your comment I'm actually thinking those methods probably should then be introduced by a *visible* type below the `@internal` one... In which case yeah, `@internal` types may not introduce new non-`@internal` members (but they're still free to implement or override existing visible members as necessary).
