### ISSUE TITLE
When generating .NET code, convert non-default namespace parts to PascalCase.

### ISSUE THREAD

**Issue by mpiroc** [aws/jsii#174]
Currently, if a JSII type's namespace is a child of the default namespace, the child namespace is not `PascalCase`d. For example, `jsii-calc.composition.CompositeOperation` has the namespace `Amazon.JSII.Tests.CalculatorNamespace.composition`, when it should be `Amazon.JSII.Tests.CalculatorNamespace.Composition`.

**Comment by assyadh** [comment]
After discussing with @RomainMuller , downgrading the priority as namespaces are likely to go away.
