### ISSUE TITLE
Unable to use "peer dependencies" between modules in a mono-repo

### ISSUE THREAD

**Issue by eladb** [aws/jsii#1750]
### Affected Languages

- [x] `TypeScript` or `Javascript`
- [x] `Python`
- [x] `Java`
- [x] .NET (`C#`, `F#`, ...)

### General Information
* **JSII Version:** 1.6.0 (build 248e75b)
* **Platform:**     Darwin

### What is the problem?

We are trying to add a new jsii module to a mono-repo ([cdk8s](https://github.com/awslabs/cdk8s)). This module takes a `peerDependency` on another jsii module. However, when running `jsii-pacmak`, maven and nuget are failing to resolve the local references.

### Verbose Log

```
[ERROR] Failed to execute goal on project cdk8s-plus: Could not resolve dependencies for project org.cdk8s:cdk8s-plus:jar:0.0.0: Failed to collect dependencies at org.cdk8s:cdk8s:jar:[0.0.0,0.0.1): No versions available for org.cdk8s:cdk8s:jar:[0.0.0,0.0.1) within specified range -> [Help 1]
```

### Root Cause

The root cause is here:

https://github.com/aws/jsii/blob/241d2b4577781fd0dc715441871babbbb51798c9/packages/jsii-pacmak/lib/target.ts#L119

The `findLocalBuildDirs` method only recurses into modules defined under `dependencies` and it should also include `peerDependencies`.

In fact, it should also **exclude** `bundledDependencies` I think.

Replacing this:

```ts
Object.keys(pkg.dependencies ?? {}).map((dependencyName) => {
```

With:

```ts
Object.keys({ ...pkg.dependencies, ...pkg.peerDependencies }).map((dependencyName) => {
```

Has been verified to fix the issue.

**Comment by zyrorl** [comment]
We're also affected by this issue here

**Comment by zyrorl** [comment]
Are there any updates on this? This is still causing us issues.

**Comment by RomainMuller** [comment]
I think this has been fixed a while back... I'll resolve - please re-open if it turns out to still be a problem.
