### ISSUE TITLE
Error during package build

### ISSUE THREAD

**Issue by jvargh** [aws/jsii#1799]
### Affected Languages
- [x] `TypeScript` or `Javascript`
- [ ] `Python`
- [ ] `Java`
- [ ] .NET (`C#`, `F#`, ...)

### General Information
* **JSII Version:** 1.9.0 (build 5c646d5), typescript 3.9.7
* **Platform:**     win10

### The Question
running `npm run package` fails but build works

[log.txt](https://github.com/aws/jsii/files/4941752/log.txt)

**Comment by SomayaB** [comment]
Hi @jvargh, sorry for the late reply. Are you still experiencing this issue with the newest release?
