### ISSUE TITLE
Integrate Go into aws-cdk build and publishing workflow (delivlib)

### ISSUE THREAD

**Issue by MrArnoldPalmer** [aws/jsii#1834]
## Description

After an initial implementation of GoLang support is added, verifying compatibility with the aws-cdk codebase will help us uncover any additional bugs that need to be fixed. This should be done as soon as possible to avoid uncovering severe issues that require large sweeping fixes at the last minute.

**Comment by eladb** [comment]
[jsii-release] now supports go publishing.

[jsii-release]: https://github.com/aws/jsii-release

**Comment by eladb** [comment]
@MrArnoldPalmer this is still not complete - I haven't done the CDK build bit yet (just the delivlib/pipelines bit). I'll open another issue to cover the CDK build.
