### ISSUE TITLE
Emulate Native Types like Lists and Dictionaries via Proxy Objects

### ISSUE THREAD

**Issue by skorfmann** [aws/jsii#1841]
### Affected Languages

- [x] `TypeScript` or `Javascript`
- [x] `Python`
- [x] `Java`
- [x] .NET (`C#`, `F#`, ...)

### General Information
* **JSII Version:** 
* **Platform:**     

* [x] I may be able to implement this feature request

* [ ] This feature might incur a breaking change

### Description

For [cdktf](https://cdk.tf) there's the use case of having to support complex computed types. These are lists and dictonaries, which reference attributes not supplied by a user.`cdktf` has to provide a way to reference these attributes, with the following goals in mind:

- Fully typed 
- Idiomatic usage
- `jsii` compatible

Example:

The [acm cert validation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/acm_certificate_validation) resource has a `domainValidationOptions` attribute, which is a list of `AcmCertificateDomainValidationOptions`:

```ts
export interface AcmCertificateDomainValidationOptions {
  readonly domainName?: string;
  readonly resourceRecordName?: string;
  readonly resourceRecordType?: string;
  readonly resourceRecordValue?: string;
}
```

What I'm looking for, is a way to provide a way to access these attributes which feels natural to the user of the given language. In Typescript this would be something like `certValidation.domainValidationOptions[0].resourceRecordName`. 

In Typescript, this could be achieved with a [proxy](https://github.com/hashicorp/terraform-cdk/issues/12#issuecomment-616201296) object. However, there's no way to represent this in `jsii` at the moment. 

The current implementation in `cdktf` makes the above example accessible like this: `certValidation.domainValidationOptions('0').resourceRecordName` (the string type will likely be replaced by number) and returns a reference like this `acm_certificate.domain_validation_options.0.resourceRecord`. That's close to our ideal requirements, but lacks the idiomatic aspect. 

### Proposed Solution

Not sure how this could be achieved in a way which supports all target languages. In particular, since only Python seems to have a similar way of using proxy objects to emulate native types like lists and dictionaries.

**Comment by RomainMuller** [comment]
We had thought about it in the past and that is definitely something we'd be considering to do. The main challenge here (and the reason we had deferred this work so far) is that providing a full implementation of the `List` or `Map` contracts can be a rather large endeavor (just look at the abstract methods one needs to implement in the Javadoc for [`AbstractList`](https://docs.oracle.com/javase/8/docs/api/java/util/AbstractList.html)!).

At the end of the day, this is a *simple matter of programming*. We only need to find the time to do this!

**Comment by skorfmann** [comment]
Cool, thanks for providing a bit of context.

> It might be interesting to get an [RFC](https://github.com/aws/aws-cdk-rfcs) going to get a plan figured out. Let me know if you're interested in getting something started 🙃

Yes, I'll get that started.
