### ISSUE TITLE
How to keep base classes private?

### ISSUE THREAD

**Issue by udondan** [aws/jsii#1860]
### The Question

This is in response to [this post](https://github.com/aws/jsii/issues/1818#issuecomment-665561112) of @RomainMuller:

> [...] those types you are not exporting from the module's entry point (`lib/index.ts`) cannot be used anywhere in exported declarations... But their TypeScript AST nodes have the `Export` modifier (since they are internally exported). The `jsii` compiler normally erases unexpected types from the exported API definition (so you can have "private base classes" and it "just works", however for those cases it requires the declarations to have `@internal` as part of their JSDoc.

I tried to keep my base classes private by adding the `@internal` tag to the tsdoc, but I'm having no luck. Still seeing lots of errors like `error TS0: Exported APIs cannot use un-exported type my-package.Foo`.

Is there an example available or could you have a look at my project again? 🐱 

This is what I'm getting in my [current attempt](https://github.com/udondan/iam-floyd/pull/23):

```
error TS0: Exported APIs cannot use un-exported type iam-floyd.PolicyStatementWithActions
error TS0: Exported APIs cannot use un-exported type iam-floyd.PolicyStatementWithPrincipal
error TS0: Exported APIs cannot use un-exported type iam-floyd.PolicyStatementWithEffect
error TS0: Exported APIs cannot use un-exported type iam-floyd.PolicyStatementWithCondition
error TS0: Exported APIs cannot use un-exported type iam-floyd.PolicyStatementWithResources
```

All of those classes have the `@internal` flag set, e.g. https://github.com/udondan/iam-floyd/blob/e308174fe9afaeb7ed881a3da59fba37c241ca0b/lib/shared/policy-statement/3-actions.ts#L22

**Comment by RomainMuller** [comment]
I'll have a quick look. My supporting at this stage is that you have `public` members on those private types that have an explicit or inferred return type that is one of those private types (e.g: `return this` would have the method return type inferred to the declaring class).

Hopefully I can use this example to trace the error generation path & provide a better locality.

**Comment by RomainMuller** [comment]
So I've confirmed some of the problem at least comes from methods that return `this` declared in private types.

**Comment by RomainMuller** [comment]
Here's a ZIP file containing an experimental build of *jsii* based on #1861 (I'm not sure whether you can download it directly from the "Checks" page or not), in case you want to give this a shot before the fix is merged & released: [jsii-1.10.1-pr1861.0.zip](https://github.com/aws/jsii/files/5042315/jsii-1.10.1-pr1861.0.zip).

If you want to check it before opening it, here's a GPG signature from me for this file:
```
-----BEGIN PGP SIGNATURE-----

iQEzBAABCgAdFiEEv9uVfxj3zh6kI9LpSb0n520h4AEFAl8tdL4ACgkQSb0n520h
4AH7PQf/eW8RTaABL0Hxa+/qpsG0WQykrv82S+66gSj+iF1lbEjJ94KzQobD/96D
Obm7uHcFjN3HUHoLJk5uHCcsnXJ2KVjQp+PpvY4i5JkPV5TsjTj+yzMmBtWMIYbp
9OGwjdWCUyUlmK3k10f2+fGluLZCpaydwQYAmd4aBZnHPCkD4iVuDAa8Tk2+H69j
o75rRHfEZGPw3xOkrl6zaukBabl9xU0wiMI3NOHJi0QrXE09RqpMbX9o8PQgVXUs
8a0CI/dStOmnkQcfdKIdWrzcMXlMEhcWsLkFK1CGieHosW44XD789i1RJta8GmrF
ZdFxvrqJDZD4AxDWfQLZGHhpkkbNuA==
=+8zn
-----END PGP SIGNATURE-----
```

**Comment by udondan** [comment]
Thanks so much Romain! I'll try it ASAP. Might be a while though, currently on vacation and not getting to the keyboard very often 🙂

**Comment by RomainMuller** [comment]
@udondan no worries! Enjoy your vacation 👍🏻
