### ISSUE TITLE
Readme.md Filename Case Sensitive for Python

### ISSUE THREAD

**Issue by skorfmann** [aws/jsii#1862]
### Affected Languages

- [ ] `TypeScript` or `Javascript`
- [x] `Python`
- [ ] `Java`
- [ ] .NET (`C#`, `F#`, ...)

### General Information
* **JSII Version:** 1.10.0 (build 27cfbed), typescript 3.9.7
* **Platform:**  Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64 x86_64

### What is the problem?

When publishing a package to Pypi, it gets rejected with the following error message when the readme file is named like this `Readme.md`. 

```
Uploading skorfmann_cdktf_provider_aws-0.0.9-py3-none-any.whl

  0%|          | 0.00/2.73M [00:00<?, ?B/s]
  0%|          | 8.00k/2.73M [00:00<00:50, 56.0kB/s]
 10%|█         | 288k/2.73M [00:00<00:32, 79.2kB/s] 
 67%|██████▋   | 1.83M/2.73M [00:00<00:08, 113kB/s]
HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/
100%|██████████| 2.73M/2.73M [00:00<00:00, 4.14MB/s]
The description failed to render for 'text/markdown'. See https://pypi.org/help/#description-content-type for more information.
Content received from server:
<html>
 <head>
  <title>400 The description failed to render for 'text/markdown'. See https://pypi.org/help/#description-content-type for more information.</title>
 </head>
 <body>
  <h1>400 The description failed to render for 'text/markdown'. See https://pypi.org/help/#description-content-type for more information.</h1>
  The server could not comply with the request since it is either malformed or otherwise incorrect.<br/><br/>
The description failed to render for &#x27;text/markdown&#x27;. See https://pypi.org/help/#description-content-type for more information.
```

I was able to fix it by changing the filename to `README.md`

It was working on my local machine - I guess due to the case insensitive filesystem on OSX. - but failing in CI.

**Comment by RomainMuller** [comment]
This is really weird - no file copies are happening, and `jsii-pacmak` very specifically creates a file named `README.md`:

https://github.com/aws/jsii/blob/c236307c7837dcd4bb1d058eef9f4531b633115b/packages/jsii-pacmak/lib/targets/python.ts#L1611-L1613

I can see this failing if there was *already* a `Readme.md` (different case) in the `outdir` when `jsii-pacmak` generated afresh (in such cases, macOS will likely preserve the existing file's casing)...

**Comment by skorfmann** [comment]
Yes, that's what I thought as well. My first assumption was, that invalid markdown might have caused it (something like #1244). However, that wasn't the case.

Here are the relevant builds:

- https://github.com/skorfmann/cdktf-provider-aws/actions/runs/201653384 (fix markdown, failed)
- https://github.com/skorfmann/cdktf-provider-aws/actions/runs/201672064 (rename `Readme.md` -> `README.md`, success)

You can download the respective artifacts from the "release pypi" builds. For the failing one the metadata description field and the `README.md` is empty. For the succeeding build, the field and the file are properly set `¯\_(ツ)_/¯`

**Comment by RomainMuller** [comment]
Oh I see what is happening is:
1. The `jsii` compiler will only look at `README.md` (so nothing on case-sensitive file system if you have `Readme.md`)
2. PyPI requires a readme to be provided

So basically we just need to make the compiler process case-insensitive, so it works on case-sensitive file systems the same way that it does on case-insensitive ones. I'll also make the *absence* of (any) readme file a warning (instead of a suggestion), since not having one appears to result in invalid PyPI packages.

**Comment by skorfmann** [comment]
Cool, thanks for the fix 👍
