### ISSUE TITLE
Cannot return `this` in overridden methods

### ISSUE THREAD

**Issue by udondan** [aws/jsii#1935]
### General Information
* **JSII Version:** 1.11.0 (build 1e9b8e1), typescript 3.9.7
* **Platform:**     19.6.0 Darwin Kernel Version 19.6.0

### What is the problem?

```ts
export class A {
  public foo() {
    return this;
  }
}

export class B extends A {
  public foo() {
    return this;
  }
}
```

If class B extends class A and B overrides a methods which returns `this`, jsii fails with:

> error TS0: HelloJSII.B#foo changes the return type when overriding HelloJSII.A (expected HelloJSII.A, found HelloJSII.B)

In the end `this` refers to the exact same thing. Any way to fix this?

For me this is a big blocker. I have 237 classes depending on a base class which defines 30 common methods. In some cases these methods get overridden in the child classes. The only alternative at this point seems to be to remove those methods all together from the base class and add them to every single child class. Delete 30, add 7110 methods. 😿

**Comment by rix0rrr** [comment]
Write this:

```ts
export class A {
  public foo() {
    return this;
  }
}

export class B extends A {
  public foo(): A {
    return this;
  }
}
```

**Comment by rix0rrr** [comment]
Explanation: without type annotations TypeScript will infer the type. Since it CAN infer a very specific type ("B") it will do so.

That just happens to change the return type w.r.t. with the inherited definition. Some languages support making the return type more specific (TypeScript, Java) but jsii must reject this more specific return type because C# won't allow it.

**Comment by RomainMuller** [comment]
@rix0rrr nailed it. I'll just add that the reason why `jsii` is not "using the more general type" in this particular case is because this means the API as visible from other languages would be different than that available from TypeScript users; which makes it more difficult to write example code that is universally relevant (i.e: in this case, you'd be able to use all aspects of `B` in TypeScript; while in other languages you'd end up having to manually cast the value).

**Comment by udondan** [comment]
Thanks folks, makes sense! One small addition, for everyone facing the same thing: `A.foo` must also return type `A` or it won't compile:

```
Property 'foo' in type 'B' is not assignable to the same property in base type 'A'.
  Type '() => A' is not assignable to type '() => this'.
    Type 'A' is not assignable to type 'this'.
      'A' is assignable to the constraint of type 'this', but 'this' could be instantiated with a different subtype of constraint 'B'.ts(2416)
```

This will work:

```ts
export class A {
  public foo(): A {
    return this;
  }
}

export class B extends A {
  public foo(): A {
    return this;
  }
}
```

**Comment by udondan** [comment]
Hey folks, @rix0rrr & @RomainMuller. 👋 

So, it turns out this is actually not a solution. Yes, this makes it compile, but if you think about it, it defeats the purpose. The only reason why you want to return `this` from a class method is to support method chaining. And of course if the return type is `A`, you cannot chain commands from B. Take a look at this more detailed example:


```typescript
export class A {
  public foo(): A {
    return this;
  }

  public bar(): A {
    return this;
  }
}

export class B extends A {
  public foo(): A {
    return this;
  }

  public baz(): A {
    return this;
  }
}
```

And now attempting to call this:

```typescript
new B().foo().bar() //works
new B().foo().baz() //fails, because `baz()` is not present on `A` but `B`.
```

Things get worst if you add more layers: 


```typescript
export class A {
  public foo(): A {
    return this;
  }

  public bar(): A {
    return this;
  }
}

export class B extends A {
  public foo(): A {
    return this;
  }

  public baz(): A {
    return this;
  }
}

export class C extends B {
  public bam() {
    return this;
  }
}
```

`C.bam` does not override anything nor has an explicit return type. Due to the fuped return types of the methods on the parent classes suddenly the order of method calls matters

```typescript
new C().bam().foo() //works
new C().foo().bam() //fails, because `foo()` returns `A` which has no bam() method
```

So yes, while you can trick JSII to return `this`, the result defeats the purpose. I'd appreciate if this issue could be opened again.

Thanks,
Daniel

**Comment by mbonig** [comment]
> And of course if the return type is `A`, you cannot chain commands from B.

Yes, but that's OOP. I think your only option would be to cast it (on the consumer) as the derived class, but then you defeat the benefits of a chained syntax (`(new C().foo() as C).bam()`). However, I don't know how you achieve both succinct syntax and proper OOP. Perhaps Typescript has another trick up its sleeve?

Personally, I think this is why chained API's don't last too long, you start to find these rough edges rather quickly and cut yourself up trying to work around them.

**Comment by udondan** [comment]
Well, the rough edge here is only cause  by the fact, that JSII forces me to return type A, while that never was my intention and is not what is actually returned when converted to JS. (I hope it's clear what I mean, no need to tell my JS doesn't have types etc ;))

Chained APIs work fine. Just not with JSII.

**Comment by mbonig** [comment]
The JSII is just enforcing good OOP since it has to convert to proper OOP languages and can't just get by with JS's loose-typing. 

If you have control over all classes, could you add a typed function to the base class that could still enforce the extended type on the handler?

e.g.
```
class A<T> {
...
    foo():T
}

class B extends A<B> ...
```

??

**Comment by udondan** [comment]
I solved my problem by avoiding it. If indeed this is not fixable bc JSII needs an exact type, this should be documented in the limitations of JSII, so nobody works for days into the wrong direction, like I did.

**Comment by mbonig** [comment]
@udondan since your iam-floyd is public, can you point us to the specific issue you're having with your code, as an example of what couldn't be done with the JSII?

**Comment by udondan** [comment]
Usually you're being asked to provide the simplest possible example. 😹  Ok, so here's the most complex example possible, with the method `ifAwsRequestTag`:


Present on the base* class `PolicyStatementWithCondition`: https://github.com/udondan/iam-floyd/blob/1f28e984bdf46321ae62c1a10567c7d54166d3f3/lib/shared/policy-statement/2-conditions.ts#L421-L427

And here one of many overrides, in the Ec2 class: https://github.com/udondan/iam-floyd/blob/1f28e984bdf46321ae62c1a10567c7d54166d3f3/lib/generated/amazonec2.ts#L12011-L12013

The code of these methods is identical, and this is the case as well for all other overrides. The override is in place to only override the methods tsdoc which is meant to give important context information to the user.

This has been dropped for now. The only alternative would have been to remove the methods from the base\* class (or remove the base\* class completely) and each and every single method to the 238 top level classes.


\* It's not the direct parent class nor the absolute base class. Just one in a long chain of inheritance:

`cdk.Iam.PolicyStatement` <- `PolicyStatementBase` <- `PolicyStatementWithCondition` <- `PolicyStatementWithActions` <- `PolicyStatementWithResources` <- `PolicyStatementWithEffect` <- `PolicyStatementWithPrincipal` <- `PolicyStatementWithCDKPrincipal` <- `PolicyStatement` <- `Ec2`
