### ISSUE TITLE
Could not generate package for .NET Standard 2.0 (jsii-pacmak@0.17.1)

### ISSUE THREAD

**Issue by BiDzej** [aws/jsii#1984]
### Affected Languages

- [ ] `TypeScript` or `Javascript`
- [ ] `Python`
- [ ] `Java`
- [X] .NET (`C#`, `F#`, ...)

### General Information
* **JSII Version:** 0.17.1 (build f4a0dbe)
* **Platform:**     
OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.19041 N/A Build 19041

### What is the problem?

I am not able to generate NuGet package from typescript code with usage of 0.17.1 version of the JSII (latest JSII version supporting .NET Standard 2.0 instead of .NET Core 3.0). 
Steps to reproduce:
**mkdir testFolder**
**cd testFolder**
**npm init -y**
**npm install --save-dev jsii@0.17.1 jsii-pacmak@0.17.1**
create lib folder and place there index.ts file (see attached file)
set up package.json config file (see attached file)
**npm run build**
> jsiioldversiontest@1.0.0 build C:\Users\t-bjurek\Desktop\temp\test3
> jsii -vvv
>[2020-09-08T16:25:09.910] [DEBUG] jsii/compiler - Creating or updating C:\Users\t-bjurek\Desktop\temp\test3\tsconfig.json
>[2020-09-08T16:25:10.779] [TRACE] jsii/assembler - Emitting assembly: C:\Users\t-bjurek\Desktop\temp\test3\.jsii
>suggestion TS9999: JSII: A "description" field should be specified in "package.json"
>suggestion TS9999: JSII: A "homepage" field should be specified in "package.json"
>suggestion TS9999: JSII: There is no "README.md" file. It is recommended to have one.

**npm run package**
> for logs see attached file
### Verbose Log
See attached zip archive, logs folder
[JSII-Pacmak_bug.zip](https://github.com/aws/jsii/files/5188619/JSII-Pacmak_bug.zip)

**Comment by RomainMuller** [comment]
Jsii pacmak 0.x is no longer supported and you are encouraged to migrate to the 1.x tree instead.

Net Standard 2.0 is also not supported by jsii 1.x - we required C# 8.0, which is only available from `netstandard2.1`.
We currently target only `netcoreapp3.1`. If you have a use-case for `netstandard2.1`, we would love to hear about it (in a feature request).
