### ISSUE TITLE
How to interpret "Type "SendMessageResult" cannot be used as the return type because it is private or @internal"?

### ISSUE THREAD

**Issue by flyingImer** [aws/jsii#2000]
### Affected Languages

- [X] `TypeScript` or `Javascript`
- [ ] `Python`
- [ ] `Java`
- [ ] .NET (`C#`, `F#`, ...)

### General Information
* **JSII Version:**  `1.12.0`
* **Platform:**      `macOS 10.15.6`
* **AWS SDK:** `2.751.0`

### The Question

I'm playing around the `jsii` with `aws-sdk` (see code snippet below). However, when running `yarn build` (or `jsii --silence-warnings=reserved-word --no-fix-peer-dependencies`, in particular), I saw the error message `Type "SendMessageResult" cannot be used as the return type because it is private or @internal`. Not sure I understand why I'm seeing this message - I don't think this interface is `private` or `@internal` given my limited experience with JS/TS...
```
  public async putToQueue(messageBody: string, queueURL: string): Promise<SQS.SendMessageResult> {
    const url = queueURL || process.env.TASK_PIPE;
    if (!url) {
      throw new Error('Missing queue URL');
    }
    const params: SQS.SendMessageRequest = {
      MessageBody: messageBody,
      QueueUrl: url,
    };
  
    console.log(params);
    const sqsData: SQS.SendMessageResult = await new SQS().sendMessage(params).promise();
    console.log(sqsData);
    return sqsData;
  }
```

See full code repo -> https://github.com/flyingImer/jsii-playground/blob/error-msg/src/index.ts

**Comment by flyingImer** [comment]
@RomainMuller any thought? 😃

**Comment by RomainMuller** [comment]
Weird... this ought to be a message telling you that this type is not exported from a `jsii` module (`aws-sdk` isn't a customer of ours)...

This type basically won't be portable to other languages so you cannot expose it in a public API...

I'll investigate why you got this error message and not the appropriate one... I'm guessing the typescript compiler represented this API in a surprising (to me anyway) way

**Comment by flyingImer** [comment]
It's good to know this is not the appropriate error message in this case. 

On the other hand, it sounds my intention with this code is not feasible with jsii right now. I wonder is there any plan in this direction?
