### ISSUE TITLE
Go Runtime Handle Callbacks

### ISSUE THREAD

**Issue by MrArnoldPalmer** [aws/jsii#2048]
## :rocket: Feature Request

Runtime methods currently don't handle callback responses from the API. Basically, they should 😄. This is a non-trivial task that kernel request methods need to handle.

The custom `UnmarshalJSON` implementation for runtime response apis may be an appropriate place to distinguish between a callback response and everything else, as this is where error and ok responses are currently deciphered. Decoding the callback should trigger additional runtime request round trips until a complete response is received.

- [x] blocked by https://github.com/aws/jsii/issues/2561

**Comment by iliapolo** [comment]
Emm..not sure what happening here with all these linked issues, I definitely did not intend to close this out.
