### ISSUE TITLE
ability to override default settings of generated tsconfig.json

### ISSUE THREAD

**Issue by skarode96** [aws/jsii#2071]
### Affected Languages

- [x] `TypeScript` or `Javascript`
- [ ] `Python`
- [ ] `Java`
- [ ] .NET (`C#`, `F#`, ...)

### General Information
* **JSII Version: *1.13.0 (build 385c325), typescript 3.9.7
* **Platform:*Mac Os*     
* [ ] I may be able to implement this feature request

* [ ] This feature might incur a breaking change

### Description

Currently Jsii only allows outDir and rootDir fields to be modified in jsii.tsc section, it should consider additional fields which can be configured. I am running into few issues which are caused due to default settings of tsconfig. It should take additional fields into consideration as well

**Comment by RomainMuller** [comment]
I have this idea where I'd like to allow folks to *own* their `tsconfig.json` and basically only have `jsii` enforce the configuration remains within certain boundaries (to ensure correct inter-operability). I reckon this would effectively solve your problem?

**Comment by RomainMuller** [comment]
Also see #1644

**Comment by markusl** [comment]
We'd like to see this implemented to be able to resolve the referenced issue in the 'projen' project.

**Comment by Hi-Fi** [comment]
Currently there's need to include (quite ugly) script to beginning of `projen`s compile (and watch) task to allow compilation:
`replace-in-file "lib: ['lib.es2019.d.ts']" "lib: ['lib.es2019.d.ts','lib.dom.d.ts']" node_modules/jsii/lib/compiler.js`. So some configuration offering would be quite nice.

**Comment by mrgrain** [comment]
This feature is no available as preview in [jsii@5.4.16-dev.3](https://www.npmjs.com/package/jsii/v/5.4.16-dev.3)
For now please refer to the PR https://github.com/aws/jsii-compiler/pull/931 for documentation.

Pending beta testing, I expect this to be released next week and backported to all currently supported version lines (5.3.x and 5.2.x). Documentation and website updates are also underway.

**Comment by mrgrain** [comment]
This is now releases as an experimental feature on jsii >= 5.2

Documentation:
https://aws.github.io/jsii/user-guides/lib-author/configuration/#typescript-configuration
