### ISSUE TITLE
Is it possible to ignore a particular declaration

### ISSUE THREAD

**Issue by jsteinich** [aws/jsii#2085]
### Affected Languages

- [X] `TypeScript` or `Javascript`
- [ ] `Python`
- [ ] `Java`
- [ ] .NET (`C#`, `F#`, ...)

### General Information
* **JSII Version:** 1.11.0
* **Platform:**     Linux docker-desktop 4.19.128-microsoft-standard #1 SMP Tue Jun 23 12:58:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

### The Question
I have a file which is roughly equivalent to https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/core/lib/runtime.ts. Running it through jsii gives warnings like:
```
lib/runtime.ts:16:14 - message TS9999: JSII: Ignoring VariableDeclaration node (it cannot be represented in the jsii type model)

16 export const booleanToTerraform: Mapper = identity;
```
The warnings make sense, but really this file doesn't need to be compiled for other languages. It is just needed for the runtime execution, so ignoring it would be ideal.

It does need to be referenced by code external to the package, so I can't exclude from the index.
I've tried adding `@internal` to tsdocs on everything exported, but the warnings persisted.
I've tried adding to `excludeTypescript`, but then it doesn't compile.

Alternatively, just suppressing warnings from this particular file would probably be fine.

**Comment by RomainMuller** [comment]
Hey!

We do not currently support ignoring those declarations.
To a certain extent, the "correct" way to "move them out of way" is to simply move them into a separate `.ts` file, which you simply do not export from your entry point (typically `index.ts`).

That being said, I understand this is unnecessary overhead, and we are working on mechanisms that will allow users to silence warnings in various ways (either globally, or per declaration/statement). It might be a little while before this is done though.

**Comment by jsteinich** [comment]
I thought that might be the case. Thanks for the confirmation.

Looking forward to more having more controls.
