### ISSUE TITLE
Go runtime investigate replacing JsiiObj Interface

### ISSUE THREAD

**Issue by MrArnoldPalmer** [aws/jsii#2091]
The go runtime currently uses an interface that all jsii objects must implement in order to link instance IDs within the kernel to the host object instance itself. This isn't ideal since this interface can conflict user defined code. IE the methods of the interface may prevent users from defining functions with conflicting names.

Alternatively, we should investigate defining a global hash-map that maps reference IDs to object instances. This allows us to look up objects by reference ID and find reference IDs from instances, similarly to the current `getJsiiObjId` method used in runtime calls.

**Comment by SoManyHs** [comment]
Related: https://github.com/aws/jsii/issues/2117
