### ISSUE TITLE
Go Runtime Get/Set

### ISSUE THREAD

**Issue by MrArnoldPalmer** [aws/jsii#2128]
Go runtime support for JSII get/set calls. Update jsii-pacmak implementations of interface methods for property access to call these runtime fns.

- [x] GetRequest
- [x] SetRequest
- [x] StaticGetRequest
- [x] StaticSetRequest

**Comment by SoManyHs** [comment]
Note: https://github.com/aws/jsii/pull/2133 currently has placeholder for `StaticGetRequest` on static properties
