### ISSUE TITLE
Provide replacements for prohibited member names

### ISSUE THREAD

**Issue by jsteinich** [aws/jsii#2155]
### Affected Languages

- [ ] `TypeScript` or `Javascript`
- [ ] `Python`
- [X] `Java`
- [X] .NET (`C#`, `F#`, ...)

### General Information
* **JSII Version:** 1.10.0

* [X] I may be able to implement this feature request

* [ ] This feature might incur a breaking change

### Description
Currently [prohibited member names](https://github.com/aws/jsii/blob/85764deffd70af92333363bf38478440351654da/packages/jsii/lib/assembler.ts#L2896) cause jsii to fail with a clear error message. This is in contrast to reserved words which jsii-pacmak generally takes care of renaming. Since it is the jsii step that blocks the names, jsii-pacmak isn't given the chance to rename.

### Proposed Solution

- Downgrade the error to warning
- Add the replacements into jsii-pacmak for Java/.Net

**Comment by jsteinich** [comment]
On a somewhat related note, is there a reason the lists that jsii-pacmak uses for replacements are different than the reserved word lists inside jsii?

**Comment by RomainMuller** [comment]
> On a somewhat related note, is there a reason the lists that jsii-pacmak uses for replacements are different than the reserved word lists inside jsii?

Other than implementation details, not really. There can be *contextually* reserved words (C# is mostly that - the word is reserved only in certain contexts, but this is difficult to reason over when compiling the TypeScript).

---

Now pertaining to your request - I think the direction I would rather go with respects to this particular issue is having language-specific reservations (i.e: `Builder` is only reserved in Java, etc...); and then have some kind of formalism for library authors to specify an alternate name to be used in languages where the name is reserved in a very local manner.

The only alternative to this is to actually slugify names by appending characters that are illegal in jsii member names (i.e: `$`, `_` for non-`static const`, ...), but this actually derives in degraded experience in the languages where the slugs need to apply, and generally speaking makes code generation more difficult down the line.

**Comment by jsteinich** [comment]
I think that makes a lot of sense. Here's what I'm thinking to accomplish that:

1. Add methods to the `Generator` class (or a new class that it has a reference to) for doing name replacement for each context
2. Also have a default replacement method that each context calls into so that languages without (or with little) context specific replacement can have an easier time with
3. Implement necessary language specific overrides * we may want to cut part of this for ease of configuration
4. Refactor generator implementations to call these standard replacement methods instead of the ad-hoc current replacements
5. Provide a way to pass configuration to the generator
   - Modify `BuildOptions` and `TargetOptions` to have specific keys for each context (or just use generic arguments as needed per language)
   - For cli usage, having the values be a regular expression would provide the most flexibility, but perhaps could be simplified to replacement character/string
   - If a programmatic API was created, these values could potentially just be functions
   - These additions would likely ripple up to the jsii targets configuration
6. Potentially move reserved word lists out of jsii check and completely into the generators

**Comment by jsteinich** [comment]
@RomainMuller any thoughts on the above approach? I could work on a draft PR if it's heading a direction that the jsii team agrees with.

**Comment by RomainMuller** [comment]
I reckon I would rather use TSDoc style comments to signify the name replacements, this way the alternative name lives right where the code is (instead of in a separate file).

For example, the below would rename a hypothetical `Builder` class to `CustomBuilder` in **Java**.

```ts
/**
 * @javaName CustomBuilder
 */
export class Builder {
  // ...
}
```

Now - we currently have 4 code generators (soonish to be 5), all of which are *slightly* different, which would make implementing this feature... a little more painful than it really needs to be.

I kinda would like to refactor all code generators to have a similar structure to that of the new generator for **Go** (but this is quite a project). This would also allow all generators to work on top of `jsii-reflect` (instead of `@jsii/spec`'s very low-level API) - where each *named* declaration could have a `nameForTarget(target: TargetName): string` method... so you'd be able to e.g: `builderType.nameForTarget(TargetName.JAVA)` and all the code generators would basically only render that one.

**Comment by jsteinich** [comment]
I can certainly see a lot of advantages to that approach, but the biggest downside is that it moves the responsibility of renaming out to projects that use jsii. I think that raises the bar of knowledge needed for each target language. It's not hard to find a list of reserved words for a language, but knowing naming conventions and restrictions with enough detail to provide good replacements is much harder.

All that said, perhaps there could be a pre-processor type step that adds naming overrides following a default renaming schema to allow the full flexibility while still making it easy in most cases.

**Comment by RomainMuller** [comment]
I believe allowing developers to control what their APIs render like is actually a good thing. But you are right that there might be a middle ground where we find "decent" substitutions for most languages and allow developers to configure different renaming arrangements if they know better...
