### ISSUE TITLE
Go codegen - refactor implementation map

### ISSUE THREAD

**Issue by MrArnoldPalmer** [aws/jsii#2272]
Currently the `implMap` variable created in each code generated get/invoke call to the jsii runtime is type `map[reflect.Type]reflect.Type`, where the key is the type of an interface and the value is the type of a struct that implements it. This is used by the runtime when the return type of a function is an interface type. Since the interface itself cannot be instantiated and returned, the concrete type associated with it is instead.

This type was made as a map in order to be able to resolve multiple interfaces within a single function. However, JSII may not allow this scenario to actually occur.

For example, a typescript function returning an unnamed interface referencing multiple known interfaces like so:
```typescript
interface SomeInterface{}
interface SomeOtherInterface{}
someMethod(): { someKey: SomeInterface, someOtherKey: SomeOtherInterface } {}
```
could be represented in Go as:
```go
type SomeInterface interface{}
type SomeOtherInterface interface{}

func returnsMultipleInterfaces() struct {
	someKey      SomeInterface
	someOtherKey SomeOtherInterface
} {
	return struct {
		someKey      SomeInterface
		someOtherKey SomeOtherInterface
	}{
		someKey:      struct{}{},
		someOtherKey: struct{}{},
	}
}
```
This would require passing an implementation map with concrete types for both interface1 and interface2.

JSII doesn't allow the returning of unnamed object types unless they are string indexed, IE: {[key: string]: SomeInterface}, which maps to a go `map[string]SomeInterface`. Additionally since unions are also currently unsupported, there may not actually be any way for a generated go return type to reference multiple interfaces. If this is the case, and only one is ever needed, the implMap type could instead just be a single value with type `interface{}` and an instance of the correct concrete implementation may be passed.

**Comment by RomainMuller** [comment]
Resloved by #2561
