### ISSUE TITLE
Identical static methods in parent/child classes are mistakenly marked as overrides in java resulting in a compilation error

### ISSUE THREAD

**Issue by iliapolo** [aws/jsii#2358]
### Affected Languages

- [ ] `TypeScript` or `Javascript`
- [ ] `Python`
- [X] `Java`
- [X] .NET (`C#`, `F#`, ...) *[Probably]*

### General Information
* **JSII Version:** 1.15.0 (build 585166b), typescript 3.9.7
* **Platform:**     MacOS, CodeBuild (jsii/superchain)

### What is the problem?

We encountered a scenario in `aws-cdk` that generates illegal java code, annotating static methods with the `@Override` annotation. 

This happens when a child class has the same static method as its parent.

```ts
export class Parent {
  public static hello() {}
}

export class Child extends Parent {
  public static hello() {}
}
```

This code will generate a JSII assembly that marks the `Child.hello` function both as static and as overrides of `Parent.hello`.
The generated java code will look like:

```java
public class Child extends Parent {

  @Override
  public static hello() {}

}
```

Resulting in a compilation error: `method does not override or implement a method from a supertype`

See https://github.com/aws/aws-cdk/pull/12091 for the full scenario.

**Comment by RomainMuller** [comment]
@all-contributors add @epolon for bug

**Comment by RomainMuller** [comment]
@all-contributors add @iliapolo for bug
