### ISSUE TITLE
jsii-pacmak java fails compilation if a struct as a field named "java"

### ISSUE THREAD

**Issue by eladb** [aws/jsii#2405]
### Affected Languages

- [x] `Java`

### General Information
* **JSII Version:** 1.16.0

### What is the problem?

Trying to run `jsii-pacmak` in a project that exports an interface with a field named `java`:

```ts
export interface Repro {
  readonly java: string;
}
```

Results in a compilation error: 

```
[ERROR] /private/var/folders/n2/6v4_tbz97ws0h4bn5gbyvzb0m8vcjb/T/npm-packEBNZXY/projen/src/main/java/org/projen/ConstructLibraryCdk8sOptions.java:[1358,38] cannot find symbol
[ERROR]   symbol:   variable util
[ERROR]   location: variable java of type org.projen.JsiiJavaTarget
```

### Root Cause

An example of a line that fails compilation is:

```java
this.author = java.util.Objects.requireNonNull(author, "author is required");
```

The reason compilation is failing is because the symbol `java` is defined in this scope to refer to the field `java` and not the package `java.util`.

**Comment by RomainMuller** [comment]
Wow. Ouch. This one might be very tricky to generically address, because that could literally happen with ANY package name first segment... And this is a "free form" string to a large extent.

**Comment by eladb** [comment]
But there is a limited set of package names being referenced by the generated code. Namely, `java.xxx`. I think if we just protect against `java` we will probably do 80%

**Comment by eladb** [comment]
Alternatively, is there a way in java to rename an import so that instead of `java.util.Objects` you'd refer to it as `jsii$java.util.Objects` or something like that.

**Comment by RomainMuller** [comment]
> Alternatively, is there a way in java to rename an import so that instead of `java.util.Objects` you'd refer to it as `jsii$java.util.Objects` or something like that? So it's kept under a symbol that users won't be able to override?

Nope there is no such thing in Java, unfortunately 😑
