### ISSUE TITLE
Use Named parameters for API and Spec types within the .NET generator

### ISSUE THREAD

**Issue by costleya** [aws/jsii#242]
Tests are much less brittle when named parameters for all api/spec types within the .NET generator Unit Tests. This has several benefits:

Less of a false positive or false negative when the api/spec changes.
Less work to update tests when the spec changes.
Robust against changes to the ordering of parameters, especially adjacent parameters of the same type.

**Comment by assyadh** [comment]
Not required anymore. This is on the old generator.
