### ISSUE TITLE
Go Rosetta Support

### ISSUE THREAD

**Issue by MrArnoldPalmer** [aws/jsii#2439]
Support example code transpilation to Go using JSII Rosetta in pacmak. GoDoc doesn't seem to support embedding separate .md files so when converting examples in README.md files for modules, these may have to be embedded in the package root source file as the module's "header" content.

Referencing the [GoDoc tricks example](https://godoc.org/github.com/fluhus/godoc-tricks#HTML) shows "package level" documentation.

**Comment by cameronelliott** [comment]
JSII and the CDK seem to be very powerful tools together. Although this issue, does appear to prevent some neat possibilities. 

I wonder if it would be possible to enable some preliminary Go Rosetta Support, by forgoing some or all documentation conversion or insertion, as it appears to be preventing the Go Rosetta Support. 
As a user of the Terraform CDK and the AWS CDK, minimal Go support which allows translating some HCL examples will be game-changing, when it comes. Thanks for listening.

**Comment by addihorowitz** [comment]
@MrArnoldPalmer can you please share some updates?

**Comment by aloom0626** [comment]
@MrArnoldPalmer Any update on this? I am very interested in this support being added.

**Comment by MrArnoldPalmer** [comment]
@aloom0626 we added Go support in rosetta in [v1.55.0](https://github.com/aws/jsii/blob/main/CHANGELOG.md#1550-2022-03-10). We are using it on construct-hub for JSII packages that support go.

Check out the docs generated by jsii-docgen for aws-cdk-lib as an [example](https://constructs.dev/packages/aws-cdk-lib/v/2.22.0?lang=go)
