### ISSUE TITLE
JSII Release GH Action Go Publishing

### ISSUE THREAD

**Issue by MrArnoldPalmer** [aws/jsii#2440]
Add support for publishing go modules to git repositories in the [JSII Release github action](https://github.com/aws/jsii-release). The logic currently in the [push-go-runtime job of the main workflow](https://github.com/aws/jsii/blob/main/.github/workflows/main.yml#L470) can likely just be moved to jsii-release. jsii-release can then also be used to publish the jsii-runtime-go repository.

This needs to handle pushing and tagging the specified repository with the corresponding version number of the source package. The action should allow publishing multiple packages to the same repository via nested `go.mod` files within the source tree being pushed if they are all version locked. The initial version does not need to support publishing multiple packages with unlocked/disparate versions.

**Comment by iliapolo** [comment]
Resolved by https://github.com/aws/jsii-release/pull/23
