### ISSUE TITLE
ValueError: write to closed file from using JSII 1.20.0 with AWS CDK for Python3

### ISSUE THREAD

**Issue by JKCT** [aws/jsii#2527]
### Affected Languages
- [ ] `TypeScript` or `Javascript`
- [X] `Python`
- [ ] `Java`
- [ ] .NET (`C#`, `F#`, ...)

### General Information
* **JSII Version:** 1.20.0
* **Platform:** Linux ebfa66379439 4.19.121-linuxkit #1 SMP Tue Dec 1 17:50:32 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

### What is the problem?
We are using JSII as a dependency of AWS CDK with Python 3.8.5.  As of JSII 1.20.0 it appears the following exception is generated by on any run of `cdk` that writes to the cdk.out directory: 
```
Exception ignored in: <function _NodeProcess.__del__ at 0x7f2769b21940>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/jsii/_kernel/providers/process.py", line 228, in __del__
  File "/usr/local/lib/python3.8/dist-packages/jsii/_kernel/providers/process.py", line 285, in stop
ValueError: write to closed file
```
In testing this issue does not occur with JSII 1.19.0, 1.18.0, or 1.17.0.  It is also possible to produce this issue with several recent versions of AWS CDK (tested 1.85.0, 1.86.0, 1.88.0) along with JSII 1.20.0.  This troubleshooting seems to indicate that this issue would be best served as part of the JSII repo, however please let me know if this is not the case.

### Verbose Log
Dubug and error output of running `cdk ls -v`:
```
...
outdir: cdk.out
env: {
  CDK_DEFAULT_REGION: 'us-east-1',
...
  CDK_OUTDIR: 'cdk.out',
  CDK_CLI_ASM_VERSION: '8.0.0',
  CDK_CLI_VERSION: '1.85.0'
}
Exception ignored in: <function _NodeProcess.__del__ at 0x7f2769b21940>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/jsii/_kernel/providers/process.py", line 228, in __del__
  File "/usr/local/lib/python3.8/dist-packages/jsii/_kernel/providers/process.py", line 285, in stop
ValueError: write to closed file
```

Let me know if there is any other information/output that would be helpful to provide.
Thanks!

**Comment by RomainMuller** [comment]
@all-contributors add @JKCT for bug
