### ISSUE TITLE
jsii overrides protocol documentation

### ISSUE THREAD

**Issue by eladb** [aws/jsii#263]
# jsii Overrides

The requirement is to enable users to override a jsii class's method in a
subclass they define in their native language.

For example, say I have a jsii TypeScript class:

```ts
export class Helloer {
  public helloee() {
    return "Jake";
  }

  public sayHello() {
    return `Hello, ${this.helloee()}!`
  }
}
```

In this example, lets say I want to be able to define a class in a native
language (.NET, Java, Python) which extends (derives) from `Helloer` and
overrides `helloee()`, returns a new value.

In java, it will look like this:

```java
public class MyHello extends Helloer {
    public String helloee() {
        return "Fran";
    }
}
```

And now, anyone who uses `MyHello` would get:

```java
MyHello obj = new MyHello();
obj.sayHello() // returns "Hello, Fran!"
```

This is what users expect, and this is what overrides are all about!

Overrides are supported for:
 * Methods
 * Properties (getters/setters)
 * Async Methods

## Synchronous Overrides

The jsii kernel supports overrides at runtime in the following way:

When the jsii client issues a [create
request](https://github.com/awslabs/jsii/blob/bf1f586629b027aa9549e4160d230a81bdd34e7a/packages/jsii-kernel/lib/api.ts#L43),
it can include an `overrides` field, which may include a list of property/method
_names_ that are overridden by the native class.

In the above example, the `create` call would look like this:

```js
{ fqn: 'Helloer', overrides: [ { method: 'helloee' } ] }
```

* You can attach a `cookie` with each override, which will be sent back to you
  when the override is called. This cookie can be used to associate the override
  with the native method. In Java, for example the cookie contains the method
  signature.
* If an override is specified for a method or property that doesn't exist (or is
  private), this override will be ignored. This means that the jsii client can
  simply pass all method/property names that are user-defined when the object is
  created (see the Java
  [`discoverOverrides`](https://github.com/awslabs/jsii/blob/bf1f586629b027aa9549e4160d230a81bdd34e7a/packages/jsii-java-runtime/project/src/main/java/software/amazon/jsii/JsiiEngine.java#L458)
  as an example).

The jsii kernel protocol is a request/response protocol over STDIO. The native client would
issue a request, the jsii kernel will execute it and return a response to the native client.

Continuing with our example, let's the client <=> kernel interaction when the
Java code above which calls `obj.sayHello()` is run (`>>` denotes request from
the native client to jsii runtime and `<<` denotes response from the jsii
runtime to the native client).

First, we create the object with `obj = new Helloer()` via a [create request](https://github.com/awslabs/jsii/blob/master/packages/jsii-kernel/lib/api.ts#L43)
and receive a [create response](https://github.com/awslabs/jsii/blob/master/packages/jsii-kernel/lib/api.ts#L50):

```js
>> { api: "create", fqn: "Helloer", overrides: [ { method: "helloee", cookie: "<magic-string>" } ] }
<< { objref: "helloer@0001" }
```

Now, we call `obj.sayHello()` via an [invoke request](https://github.com/awslabs/jsii/blob/master/packages/jsii-kernel/lib/api.ts#L100):

```js
>> { api: "invoke", objref: "helloer@0001", method: "sayHello" }
```

Since the jsii implementation of `sayHello` calls `this.helloee()`, and it was
defined as overridden, the response will be a [callback
response](https://github.com/awslabs/jsii/blob/master/packages/jsii-kernel/lib/api.ts#L15)
which instructs the client to invoke the override.

```js
<< { callback: { cbid: "<callback-1234>", cookie: "<magic-string>", invoke: { objref: "helloer@0001", method: "helloee" } } }
```

After the native `helloee` method was called, the runtime captures the return
value (`"Fran"`) and issues a
[complete request](https://github.com/awslabs/jsii/blob/master/packages/jsii-kernel/lib/api.ts#L136):

```js
>> { complete: { cbid: "<callback-1234>", result: "Fran" } }
```

> If an exception is thrown from the callback, the complete request will include an `err` field
  instead of `result`, and the exception will be thrown in the jsii side.

This yields control back to the jsii code, which continues to execute, and the `sayHello` method
eventually returns it's result via an [invoke response](https://github.com/awslabs/jsii/blob/master/packages/jsii-kernel/lib/api.ts#L106):

```js
<< { result: "Hello, Fran!" }
```

A similar protocol will occur for property overrides (both getters and setters can be overridden by the native code).

## Async Overrides

jsii also supports async methods and async overrides. This means that users are able to define a jsii
method that returns a `Promise` (or use the `async` keyword), and native code can subclass and override
such a method.

1. Async overrides are declared in `create` similarly to synchronous overrides.

2. When the jsii native client needs to invoke an async method, it issues a [begin request](https://github.com/awslabs/jsii/blob/master/packages/jsii-kernel/lib/api.ts#L110) which
returns a [begin response](https://github.com/awslabs/jsii/blob/master/packages/jsii-kernel/lib/api.ts#L116).
The response will always contain a `promiseid`.

3. Then, the native client should issue a [callbacks request](https://github.com/awslabs/jsii/blob/master/packages/jsii-kernel/lib/api.ts#L129)
which returns a [callbacks response](https://github.com/awslabs/jsii/blob/master/packages/jsii-kernel/lib/api.ts#L132)
with an array of [callbacks](https://github.com/awslabs/jsii/blob/master/packages/jsii-kernel/lib/api.ts#L15).
If the array is empty, this means there are no callbacks to invoke. If it includes callback invocations,
the native code should invoke each native callback and send a [complete request](https://github.com/awslabs/jsii/blob/master/packages/jsii-kernel/lib/api.ts#L136)
for each callback.

4. When all pending callbacks are completed, the native client should issue an [end request](https://github.com/awslabs/jsii/blob/master/packages/jsii-kernel/lib/api.ts#L120)
with the `promiseid` returned from the "begin" and the [end response](https://github.com/awslabs/jsii/blob/master/packages/jsii-kernel/lib/api.ts#L124)
will eventually include the result of the original async invocation.

## Compliance Tests

The following compliance tests cover overrides:

 * [asyncOverrides_callAsyncMethod](https://github.com/awslabs/jsii/blob/bf1f586629b027aa9549e4160d230a81bdd34e7a/packages/jsii-java-runtime-test/project/src/test/java/software/amazon/jsii/testing/ComplianceTest.java#L416)
 * [asyncOverrides_overrideAsyncMethod](https://github.com/awslabs/jsii/blob/bf1f586629b027aa9549e4160d230a81bdd34e7a/packages/jsii-java-runtime-test/project/src/test/java/software/amazon/jsii/testing/ComplianceTest.java#L416)
 * [asyncOverrides_overrideAsyncMethodByParentClass](https://github.com/awslabs/jsii/blob/bf1f586629b027aa9549e4160d230a81bdd34e7a/packages/jsii-java-runtime-test/project/src/test/java/software/amazon/jsii/testing/ComplianceTest.java#L429)
 * [asyncOverrides_overrideCallsSuper](https://github.com/awslabs/jsii/blob/bf1f586629b027aa9549e4160d230a81bdd34e7a/packages/jsii-java-runtime-test/project/src/test/java/software/amazon/jsii/testing/ComplianceTest.java#L435)
 * [asyncOverrides_twoOverrides](https://github.com/awslabs/jsii/blob/bf1f586629b027aa9549e4160d230a81bdd34e7a/packages/jsii-java-runtime-test/project/src/test/java/software/amazon/jsii/testing/ComplianceTest.java#L442)
 * [asyncOverrides_overrideThrows](https://github.com/awslabs/jsii/blob/bf1f586629b027aa9549e4160d230a81bdd34e7a/packages/jsii-java-runtime-test/project/src/test/java/software/amazon/jsii/testing/ComplianceTest.java#L448)
 * [syncOverrides](https://github.com/awslabs/jsii/blob/bf1f586629b027aa9549e4160d230a81bdd34e7a/packages/jsii-java-runtime-test/project/src/test/java/software/amazon/jsii/testing/ComplianceTest.java#L466)
 * [propertyOverrides_get_set](https://github.com/awslabs/jsii/blob/bf1f586629b027aa9549e4160d230a81bdd34e7a/packages/jsii-java-runtime-test/project/src/test/java/software/amazon/jsii/testing/ComplianceTest.java#L486)
 * [propertyOverrides_get_calls_super](https://github.com/awslabs/jsii/blob/bf1f586629b027aa9549e4160d230a81bdd34e7a/packages/jsii-java-runtime-test/project/src/test/java/software/amazon/jsii/testing/ComplianceTest.java#L494)
 * [propertyOverrides_set_calls_super](https://github.com/awslabs/jsii/blob/bf1f586629b027aa9549e4160d230a81bdd34e7a/packages/jsii-java-runtime-test/project/src/test/java/software/amazon/jsii/testing/ComplianceTest.java#L507)
 * [propertyOverrides_get_throws](https://github.com/awslabs/jsii/blob/bf1f586629b027aa9549e4160d230a81bdd34e7a/packages/jsii-java-runtime-test/project/src/test/java/software/amazon/jsii/testing/ComplianceTest.java#L520)
 * [propertyOverrides_set_throws](https://github.com/awslabs/jsii/blob/bf1f586629b027aa9549e4160d230a81bdd34e7a/packages/jsii-java-runtime-test/project/src/test/java/software/amazon/jsii/testing/ComplianceTest.java#L538)
 * [propertyOverrides_interfaces](https://github.com/awslabs/jsii/blob/bf1f586629b027aa9549e4160d230a81bdd34e7a/packages/jsii-java-runtime-test/project/src/test/java/software/amazon/jsii/testing/ComplianceTest.java#L556)
 * [syncOverrides_callsSuper](https://github.com/awslabs/jsii/blob/bf1f586629b027aa9549e4160d230a81bdd34e7a/packages/jsii-java-runtime-test/project/src/test/java/software/amazon/jsii/testing/ComplianceTest.java#L595)
 * [fail_syncOverrides_callsDoubleAsync_method](https://github.com/awslabs/jsii/blob/bf1f586629b027aa9549e4160d230a81bdd34e7a/packages/jsii-java-runtime-test/project/src/test/java/software/amazon/jsii/testing/ComplianceTest.java#L604)
 * [fail_syncOverrides_callsDoubleAsync_propertyGetter](https://github.com/awslabs/jsii/blob/bf1f586629b027aa9549e4160d230a81bdd34e7a/packages/jsii-java-runtime-test/project/src/test/java/software/amazon/jsii/testing/ComplianceTest.java#L612)
 * [fail_syncOverrides_callsDoubleAsync_propertySetter](https://github.com/awslabs/jsii/blob/bf1f586629b027aa9549e4160d230a81bdd34e7a/packages/jsii-java-runtime-test/project/src/test/java/software/amazon/jsii/testing/ComplianceTest.java#L620)
 * [doNotOverridePrivates_method_public](https://github.com/awslabs/jsii/blob/bf1f586629b027aa9549e4160d230a81bdd34e7a/packages/jsii-java-runtime-test/project/src/test/java/software/amazon/jsii/testing/ComplianceTest.java#L842)
 * [doNotOverridePrivates_method_private](https://github.com/awslabs/jsii/blob/bf1f586629b027aa9549e4160d230a81bdd34e7a/packages/jsii-java-runtime-test/project/src/test/java/software/amazon/jsii/testing/ComplianceTest.java#L853)
 * [doNotOverridePrivates_property_by_name_private](https://github.com/awslabs/jsii/blob/bf1f586629b027aa9549e4160d230a81bdd34e7a/packages/jsii-java-runtime-test/project/src/test/java/software/amazon/jsii/testing/ComplianceTest.java#L864)
 * [doNotOverridePrivates_property_by_name_public](https://github.com/awslabs/jsii/blob/bf1f586629b027aa9549e4160d230a81bdd34e7a/packages/jsii-java-runtime-test/project/src/test/java/software/amazon/jsii/testing/ComplianceTest.java#L875)
 * [doNotOverridePrivates_property_getter_public](https://github.com/awslabs/jsii/blob/bf1f586629b027aa9549e4160d230a81bdd34e7a/packages/jsii-java-runtime-test/project/src/test/java/software/amazon/jsii/testing/ComplianceTest.java#L886)
 * [doNotOverridePrivates_property_getter_private](https://github.com/awslabs/jsii/blob/bf1f586629b027aa9549e4160d230a81bdd34e7a/packages/jsii-java-runtime-test/project/src/test/java/software/amazon/jsii/testing/ComplianceTest.java#L904)

**Comment by dstufft** [comment]
Can you override a constructor? What do you pass in as the method in that case?

**Comment by eladb** [comment]
> Can you override a constructor? What do you pass in as the method in that case?

No, the constructor cannot be virtually called.

**Comment by dstufft** [comment]
Something that wasn't clear to me from this documentation, is how an override calling ``super()`` would work here.

From what I understand, if a subclass with an override calls super, then the parent class's invoke call to that function should Just Work (tm) and the JSII will be smart enough not to generate another callback asking for the overridden method to be called.

However, that wasn't clear to me, and I was originally looking for a mechanism to call the original method.
