### ISSUE TITLE
Impossible to control go module name - add 'preview' version module name

### ISSUE THREAD

**Issue by RomainMuller** [aws/jsii#2632]
Consider revising the go configuration block, and [documenting it](https://aws.github.io/jsii/user-guides/lib-author/configuration/targets/go/).

In particular:
- [ ] The "module name root" should probably be called `repositoryName` instead of `moduleName`
- [ ] The go package name should be user-configurable (with sane defaults), as `packageName`
- [ ] Whether the `packageName` is appended to the `repositoryName` to make the fully qualified module name or not should be user-configurable, too (it makes sense for mono-repos, but otherwise is likely undesirable)

**Comment by eladb** [comment]
Changed to P1 because this is a blocker for CDK release.
