### ISSUE TITLE
go: unable to access protected members

### ISSUE THREAD

**Issue by eladb** [aws/jsii#2673]
### Affected Languages

- [x] `GoLang`
- [ ] `TypeScript` or `Javascript`
- [ ] `Python`
- [ ] `Java`
- [ ] .NET (`C#`, `F#`, ...)

### General Information
* **JSII Version:** 1.42.0
* **Platform:**     *any*

### What is the problem?

The generated go code does not contain protected members. Since Go does not really have that concept, we should probably just make them visible on the type (treat them as public).

See compliance test `TestCanOverrideProtectedSetter`.

**Comment by MrArnoldPalmer** [comment]
Ideally we can add a documentation line to indicate that these are protected to give some indication of protectedness
