### ISSUE TITLE
go: unable to set an array of interfaces/enums

### ISSUE THREAD

**Issue by iliapolo** [aws/jsii#2686]
## :bug: Bug Report

Its impossible to set a TS property typed as an array of classes.

### Affected Languages

- [ ] `TypeScript` or `Javascript`
- [ ] `Python`
- [ ] `Java`
- [ ] .NET (`C#`, `F#`, ...)
- [X] Golang

### General Information
* **JSII Version: ALL**
* **Platform: ALL**

### What is the problem?

Consider the following TS code:

https://github.com/aws/jsii/blob/45b527c0b2f35a09b715c1a6c5940ec0578007fb/packages/jsii-calc/lib/calculator.ts#L205-L209

Which generates the following Golang code:

```go
type Sum interface {
  SetParts(val []scopejsiicalclib.NumericValue)
}
```

Trying to set this property from Go produces an error:

```go
sum.SetParts([]calclib.NumericValue{calclib.NewNumber(5), calclib.NewNumber(10), calc.NewMultiply(calclib.NewNumber(2), calclib.NewNumber(3))});
```

```console
test panicked: "Value did not match any type in union: Expected a number, got {\"Base\":{}}, Expected object reference, got {\"Base\":{}}"
```

**Comment by eladb** [comment]
@MrArnoldPalmer I suspect the same bug also applies to an array of enums. When setting an array of enums it seems like the enums are marshaled as strings instead of as jsii enums. Updating title to reflect.

**Comment by RomainMuller** [comment]
@eladb  - this would have been correct - the _contents_ of the map was not recursively transformed on the way in from JavaScript, so only the top level map was correctly processed.

There was also an additional bug whereby you could not receive a list as an `interface{}` in certain conditions (including when that was part of a map)
