### ISSUE TITLE
xmldom 0.4.0 vulnerability i jsii-rosetta 1.24.0

### ISSUE THREAD

**Issue by pahud** [aws/jsii#2710]
## :rocket: Feature Request

The current release of jsii-rosetta [1.24.0](https://www.npmjs.com/package/jsii-rosetta) depends on xmldom ^0.4.0 and xmldom 0.4.0 is vulnerable
https://github.com/xmldom/xmldom/security/advisories/GHSA-h6q6-9hqw-rwfv

Can we bump jsii-rosetta with dependency on ^0.5.0 ?

**Comment by RomainMuller** [comment]
Hey!

We will issue a new release with the fixed dependency at the earliest convenience.

Note that - the risk associated with `jsii-rosetta`'s use is very limited (if any), as it cannot really be considered as parsing "untrusted" input.

**Comment by pahud** [comment]
1.25.0 was published. Issue closed.
