### ISSUE TITLE
No access to NodeJS in jsii/superchain when overriding the default container image command

### ISSUE THREAD

**Issue by jusiskin** [aws/jsii#2734]
### Affected Languages
- [X] `TypeScript` or `Javascript`
- [ ] `Python`
- [ ] `Java`
- [ ] .NET (`C#`, `F#`, ...)
- [ ] `Go`

### General Information
* **JSII Version:** latest `jsii/superchain` image (Image ID: `53fcfbbc6bda`)
* **Platform:**     N/A

### What is the problem?
In #2718, NVM was added instead of directly installing NodeJS 10.x in the `jsii/superchain` image. The default Docker `CMD` was changed to use a bash login shell:

https://github.com/aws/jsii/blob/c79a346ada8789efe63db2a1f798f55f31c56178/superchain/Dockerfile#L129

This works when you use the container without specifying an override command. When a command is specified, for example:

```sh
docker run --rm -it jsii/superchain node
```

this code is bypassed and NodeJS is no longer available:

```sh
docker: Error response from daemon: OCI runtime create failed: container_linux.go:370: starting container process caused: exec: "node": executable file not found in $PATH: unknown.
```

**Comment by RomainMuller** [comment]
I wonder if we can work around this by setting `ENTRYPOINT` instead of `CMD`?

**Comment by rix0rrr** [comment]
Otherwise we make NVM do symlink manipulation on disk (instead of changing environment variables in a sourced shell script).

That'd also be more robust.

**Comment by rix0rrr** [comment]
`bash -c` as entrypoint might also do it.

**Comment by udondan** [comment]
Thank you @RomainMuller 😸

**Comment by udondan** [comment]
Is this going to be pushed to docker hub immediately or scheduled tonight?
