### ISSUE TITLE
AttributeError: type object 'type' has no attribute '__jsii_type__' when trying to implement interface in Python

### ISSUE THREAD

**Issue by oleksii-donoha** [aws/jsii#2746]
### Affected Languages

- [ ] `TypeScript` or `Javascript`
- [X] `Python`
- [ ] `Java`
- [ ] .NET (`C#`, `F#`, ...)
- [ ] `Go`

### General Information
* **JSII Version:** CDK 1.94.1
* **Platform:**     Linux 5.10.18-200.fc33.x86_64

### What is the problem?
While implementing an interface, jsii cannot correctly retrieve jsii type.
Most likely related to #807 and #1781

```
from aws_cdk.aws_lambda_nodejs import ICommandHooks
import jsii

@jsii.implements(ICommandHooks)
class Bundler:
    def before_bundling(self, input_dir: str, output_dir: str):
        return [
           "some commands"
        ]
```

### Verbose Log
```
Traceback (most recent call last):
 ...
  File "...lib64/python3.9/site-packages/aws_cdk/aws_lambda_nodejs/__init__.py", line 990, in __init__
    jsii.create(NodejsFunction, self, [scope, id, props])
  File "...lib64/python3.9/site-packages/jsii/_kernel/__init__.py", line 278, in create
    args=_make_reference_for_native(self, args),
  File "...lib64/python3.9/site-packages/jsii/_kernel/__init__.py", line 144, in _make_reference_for_native
    return [_make_reference_for_native(kernel, i) for i in d]
  File "...lib64/python3.9/site-packages/jsii/_kernel/__init__.py", line 144, in <listcomp>
    return [_make_reference_for_native(kernel, i) for i in d]
  File "...lib64/python3.9/site-packages/jsii/_kernel/__init__.py", line 161, in _make_reference_for_native
    "data": {
  File "...lib64/python3.9/site-packages/jsii/_kernel/__init__.py", line 162, in <dictcomp>
    jsii_name: _make_reference_for_native(
  File "...lib64/python3.9/site-packages/jsii/_kernel/__init__.py", line 161, in _make_reference_for_native
    "data": {
  File "...lib64/python3.9/site-packages/jsii/_kernel/__init__.py", line 162, in <dictcomp>
    jsii_name: _make_reference_for_native(
  File "...lib64/python3.9/site-packages/jsii/_kernel/__init__.py", line 184, in _make_reference_for_native
    kernel.create(d.__class__, d)
  File "...lib64/python3.9/site-packages/jsii/_kernel/__init__.py", line 277, in create
    fqn=klass.__jsii_type__ or "Object",
AttributeError: type object 'type' has no attribute '__jsii_type__'

```

**Comment by RomainMuller** [comment]
@oleksii-donoha can you provide a more complete reproduction?

**Comment by oleksii-donoha** [comment]
@RomainMuller I'm not sure whether it's enough, but the context is this:

```
@jsii.implements(ICommandHooks)
class Bundler:
    def before_bundling(self, input_dir: str, output_dir: str):
        return [
           "some commands"
        ]


some_function = aws_lambda_nodejs.NodejsFunction(
            self,
            id="does stuff",
            entry="path/to/source.ts",
            deps_lock_file_path="path/to/package-lock.json",
            handler="handler",
            runtime=aws_lambda.Runtime.NODEJS_12_X,
            description="Function performs things",
            bundling=BundlingOptions(
                command_hooks=Bundler
            )   
        )
```
Python 3.9.1

**Comment by McDoit** [comment]
I assume the same issue exists in C#, just yesterday i tried implementing `IStringProducer` in C#

    [JsiiClass(typeof(StringProducer), "@aws-cdk/core.StringProducer")]
    internal class StringProducer : IStringProducer
    {
        public Func<string> function { get; set; }

        [JsiiMethod("produce", "{\"optional\":true,\"type\":{\"primitive\":\"string\"}}", "[{\"name\":\"context\",\"type\":{\"fqn\":\"@aws-cdk/core.IResolveContext\"}}]", false, false)]
        public string Produce(IResolveContext context)
        {
            return function();
        }
    }
Don't know if anything is wrong, but i got some messy jsii/cdk errors with that

**Comment by RomainMuller** [comment]
In C# you actually have to also extend `DeputyBase` for this to work (this is ugly, but actually harder to fix than I'd have guessed).

**Comment by RomainMuller** [comment]
@oleksii-donoha assuming your code example is correct (I.e: it's not just a typo), the problem may be that you are passing the type (`Bundler`) instead of an instance thereof (`Bundler()`).

```python
some_function = aws_lambda_nodejs.NodejsFunction(
            self,
            id="does stuff",
            entry="path/to/source.ts",
            deps_lock_file_path="path/to/package-lock.json",
            handler="handler",
            runtime=aws_lambda.Runtime.NODEJS_12_X,
            description="Function performs things",
            bundling=aws_lambda_nodejs.BundlingOptions(
                command_hooks=Bundler()
            )   
        )
```

**Comment by oleksii-donoha** [comment]
@RomainMuller it might have been a typo. Could it also be the case that I didn't implement other methods, only `before_bundling`?

**Comment by RomainMuller** [comment]
@oleksii-donoha  - So the code I copied above worked on my machine with the latest CDK, and produced the output I would expect.

There was an error if you failed to implement all method from the interface (as the `NodejsFunction` will attempt to call *at least* `after_bundling`, so it has to be defined); but it was a different error than the one you're facing.

**Comment by oleksii-donoha** [comment]
@RomainMuller I see, thanks for help. Very cryptic error message for a mundane error like that. `type object 'type'` should have given me a hint that I'm passing class instead of object but I somehow missed it.
