### ISSUE TITLE
Running jsii-pacmak fails when on a path with a space

### ISSUE THREAD

**Issue by ArmaanT** [aws/jsii#2748]
### Affected Languages

- [ ] `TypeScript` or `Javascript`
- [ ] `Python`
- [ ] `Java`
- [ ] .NET (`C#`, `F#`, ...)
- [ ] `Go`

### General Information
* **JSII Version:** 1.26.0 (build 7d76e02)
* **Platform:** Ubuntu 20.04

### What is the problem?
Running jsii-pacmak on a path with spaces in it will cause the command to fail. I did some quick testing and was able to solve the problem locally by wrapping the module directory in quotes [here](https://github.com/aws/jsii/blob/99837a8fff9edee8011439253a89617c498722a0/packages/jsii-pacmak/lib/packaging.ts#L58).

I can make a PR to fix this issue if the above idea makes sense.

### Verbose Log
```
$ '/home/armaan/path/with space/node_modules/.bin/jsii-pacmak' --verbose
[jsii-pacmak] [INFO] Found 1 modules to package
[jsii-pacmak] [INFO] Packaging NPM bundles
Error: Command (npm pack /home/armaan/path/with space) failed with status 1:
#STDERR> npm ERR! code ENOLOCAL
#STDERR> npm ERR! Could not install from "../../home/armaan/path/with" as it does not contain a package.json file.
#STDERR> 
#STDERR> npm ERR! A complete log of this run can be found in:
#STDERR> npm ERR!     /home/armaan/.npm/_logs/2021-03-26T22_38_17_866Z-debug.log
#STDERR> 
#STDOUT> 
    at ChildProcess.<anonymous> (/home/armaan/path/with space/node_modules/jsii-pacmak/lib/util.js:120:27)
    at Object.onceWrapper (events.js:422:26)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1048:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by RomainMuller** [comment]
@all-contributors add @ArmaanT for bug
