### ISSUE TITLE
Python module import fails with: KeyError: '__all__' (jsii-pacmak regression)

### ISSUE THREAD

**Issue by donicek** [aws/jsii#2750]
### Affected Languages

- [ ] `TypeScript` or `Javascript`
- [X] `Python`
- [ ] `Java`
- [ ] .NET (`C#`, `F#`, ...)
- [ ] `Go`

### General Information
* **JSII Version: 1.26.0** 
* **Platform: Mac OS, Linux** 

### What is the problem?
When trying to import from a module generated by the newest jsii-pacmak (via projen), I'm now getting a `KeyError: '__all__'` error. The module has no direct exports, it just exports several submodules. This worked without any issues when the module had been generated with `v1.22.0`.

If I'm reading the code correctly, the regression was introduced in this commit: https://github.com/aws/jsii/commit/c2bd156b30fd1db469fd609af09dbed314a5d280#diff-f7a931af3b21698bee9fa2730cdaa8d440e4c596348770339f0187ff7ae34752R1507 by adding a condition around the `__all__ = [ ... ]` block, which, in case the module has only submodules but no direct exports, leaves `__all__` undefined, thus making the subsequent call to `publication.publish()` fail (because it implicitly relies on the presence of `__all__`, even if empty).

### Verbose Log
```
Traceback (most recent call last):
  File "app.py", line 4, in <module>
    from my_package.cdk_constructs import pipeline
  File "/usr/local/lib/python3.7/site-packages/my_package/cdk_constructs/__init__.py", line 126, in <module>
    publication.publish()
  File "/usr/local/lib/python3.7/site-packages/publication.py", line 58, in publish
    all = localvars["__all__"]
KeyError: '__all__'
```

**Comment by RomainMuller** [comment]
Oh we might not be rendering an `__all__` entry if there is nothing exported from the present module... Maybe excessive optimisation?

**Comment by RomainMuller** [comment]
@all-contributors add @donicek for bug

**Comment by polothy** [comment]
Yeah, the initialization of `__all__` is now conditional, but `publication.publish()` expects it to always exist.  So... fix might be to modify the `publication` package?
