### ISSUE TITLE
Docs are Broken

### ISSUE THREAD

**Issue by skorfmann** [aws/jsii#2756]
The docs website seems to be broken for me

![Screenshot 2021-03-29 at 17 25 05](https://user-images.githubusercontent.com/136789/112860189-e4606380-90b3-11eb-9099-146dd4c8716b.png)
![Screenshot 2021-03-29 at 17 25 22](https://user-images.githubusercontent.com/136789/112860199-e62a2700-90b3-11eb-99fa-af47b0724cc1.png)

**Comment by peterwoodworth** [comment]
The site seems to work fine for me when I go to [user guides](https://aws.github.io/jsii/user-guides/) first then clicking on welcome. But you're right, same thing happens to me when I go to https://aws.github.io/jsii/ without going to user-guides first.

**Comment by NGL321** [comment]
May be bug with Github.io. Needs further investigation

**Comment by skorfmann** [comment]
> But you're right, same thing happens to me when I go to https://aws.github.io/jsii/ without going to user-guides first.

Which is the one linked on the project landing page :) 

![Screenshot 2021-03-29 at 22 53 30](https://user-images.githubusercontent.com/136789/112898956-cdd10100-90e1-11eb-8a8b-d331a2839fa9.png)

**Comment by RomainMuller** [comment]
Okay so the index for some reason contained references to outdated stylesheets? I'm not sure how this happened.

**Comment by RomainMuller** [comment]
Site has been restored now.
