### ISSUE TITLE
(jsii-go) Could we resolve the set of overriden methods by reflect not annotation.

### ISSUE THREAD

**Issue by yglcode** [aws/jsii#2768]
### Affected Languages

- [ ] `TypeScript` or `Javascript`
- [ ] `Python`
- [ ] `Java`
- [ ] .NET (`C#`, `F#`, ...)
- [X] `Go`

### General Information
* **JSII Version:** 1.26.0 (build 7d76e02), typescript 3.9.9
* **Platform:**     linux

* [x] I may be able to implement this feature request

* [X] This feature might incur a breaking change

### Description
In current jsii go package, a struct will embed the "overriden" interface and annotate it with the implemented "overriding" methods [doc](https://aws.github.io/jsii/user-guides/lib-user/language-specific/go/), such as:
type childClass struct {
   // We implement AbstractMethod, AbstractReadonlyProperty, and override the setter for ConcreteProperty
   jsiimodule.AbstractBaseClass `overrides:"AbstractMethod,AbstractReadonlyProperty,ConcreteProperty"`
   ...
}.

### Proposed Solution
My understanding is that all overriding methods will have pointer receiver. If this is correct, we may be able to resolve the set of overriding methods thru reflect automatically, for the following two reasons:
   1> If S contains an embedded field *T, the method sets of S and *S both include promoted methods with receiver T or *T.
   2> if a method is defined/overriden with pointer receiver *T, in reflect, it is removed from method-set of T, only available in method-set of *T.

So thru reflect, we can find the difference between method-sets of T and *T, which are the methods overriden. Here is some [sample code](https://gist.github.com/yglcode/910552910223e76a0e2eed179a873215).

**Comment by MrArnoldPalmer** [comment]
@yglcode this is interesting, I was unaware of this
>if a method is defined/overriden with pointer receiver *T, in reflect, it is removed from method-set of T, only available in method-set of *T.

So we would still need to delegate to the "overrides constructor" of a class in order to register the overrides with the runtime but this could remove the need for our custom "overrides" annotation as we can find this list via the difference between methods on *T and T.

@RomainMuller does this seem feasible to you? Adding this to the GA project board for now.

**Comment by RomainMuller** [comment]
I'm favorable to this. I wonder if we should "keep" the `overrides` tag, but make it optional. It could be needed if for some reason someone was to implement a method using a non-pointer receiver (which right now we say they should not do - so maybe this is enough for us to not care?)

**Comment by yglcode** [comment]
Sorry i missed this yesterday. yes, you are right, if people want to implement the methods using non-pointer receiver, we should keep "overrides" tag as optional choice. the "overrides" tag can coexist with reflection based resolution.

**Comment by MrArnoldPalmer** [comment]
closed by https://github.com/aws/jsii/pull/2780, thanks @yglcode!
