### ISSUE TITLE
go: constructs-go not using the latest version of jsii-runtime-go

### ISSUE THREAD

**Issue by corymhall** [aws/jsii#2779]
### Affected Languages

- [ ] `TypeScript` or `Javascript`
- [ ] `Python`
- [ ] `Java`
- [ ] .NET (`C#`, `F#`, ...)
- [X] `Go`

### General Information
* **JSII Version: v1.27.0** 
* **Platform: 18.04.1-Ubuntu**     

### What is the problem?

It looks like the `constructs-go` package is using an old version (`v1.26.0`) of `jsii-runtime-go` which is causing go to vendor the old version (`v1.26.0`) instead of the new version (`v1.27.0`).

Here is my `go.mod`
```go
module mymodule

go 1.16

require (
	github.com/aws/aws-cdk-go/awscdk v1.97.0-devpreview
	github.com/aws/jsii-runtime-go v1.27.0
)
```

result of `go mod graph`
```
mymodule github.com/aws/aws-cdk-go/awscdk@v1.97.0-devpreview
mymodule github.com/aws/jsii-runtime-go@v1.27.0
github.com/aws/aws-cdk-go/awscdk@v1.97.0-devpreview github.com/aws/jsii-runtime-go@v1.27.0
github.com/aws/aws-cdk-go/awscdk@v1.97.0-devpreview github.com/aws/constructs-go/constructs/v3@v3.3.71
github.com/aws/jsii-runtime-go@v1.27.0 github.com/Masterminds/semver/v3@v3.1.1
github.com/aws/constructs-go/constructs/v3@v3.3.71 github.com/aws/jsii-runtime-go@v1.26.0
github.com/aws/jsii-runtime-go@v1.26.0 github.com/Masterminds/semver/v3@v3.1.1
```

contents of `vendor/github.com/aws/jsii-runtime-go/version`
```
0.26.0
```

I noticed this issue because I am getting the below error message which I think should have been fixed in #2754 

```
panic: "Expected enum value, got \"DELETE\""

goroutine 1 [running]:
github.com/aws/jsii-runtime-go.InvokeVoid(0xc68540, 0xc0004486e0, 0xc7ae88, 0xb, 0xc000151950, 0x1, 0x1)
        /home/ubuntu/environment/mymodule/vendor/github.com/aws/jsii-runtime-go/runtime.go:225 +0x26e
github.com/aws/aws-cdk-go/awscdk/awss3.(*jsiiProxy_Bucket).AddCorsRule(0xc0004486e0, 0xc00007e510)
        /home/ubuntu/environment/mymodule/vendor/github.com/aws/aws-cdk-go/awscdk/awss3/awss3.go:544 +0x8a
mymodule/internal/stacks.StorageStack(0x7f3b1c110e58, 0xc0000a1c50, 0xc77b4d, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/ubuntu/environment/mymodule/internal/stacks/storage.go:36 +0x671
mymodule/internal/stages.BackendApp(0x7f3b1c10c3f0, 0xc0000a0f90, 0xc7782f, 0x7, 0xc00040bed0, 0x0, 0xc77cc7, 0x7, 0xc77cb2, 0x7, ...)
        /home/ubuntu/environment/mymodule/internal/stages/backend.go:20 +0x1f8
main.main()
        /home/ubuntu/environment/mymodule/main.go:25 +0x36a
exit status 2
```

code
```go
bucket.AddCorsRule(&awss3.CorsRule{
		AllowedMethods: &[]awss3.HttpMethods{
			awss3.HttpMethods_DELETE,
			awss3.HttpMethods_HEAD,
			awss3.HttpMethods_GET,
			awss3.HttpMethods_POST,
			awss3.HttpMethods_PUT,
		},
		AllowedOrigins: &[]*string{jsii.String("*")},
		AllowedHeaders: &[]*string{jsii.String("*")},
		ExposedHeaders: &[]*string{
			jsii.String("x-amz-server-side-encryption"),
			jsii.String("x-amz-request-id"),
			jsii.String("x-amz-id-2"),
			jsii.String("Etag"),
		},
	})
```

**Comment by MrArnoldPalmer** [comment]
good catch. Made https://github.com/aws/constructs/pull/631 to upgrade.

Side [helper functions for lists of pointer types](https://github.com/aws/jsii/blob/main/packages/%40jsii/go-runtime/jsii-runtime-go/runtime.go#L403) were added which you may prefer for `ExposedHeaders` in your code.

**Comment by corymhall** [comment]
> Side note: [helper functions for lists of pointer types](https://github.com/aws/jsii/blob/main/packages/%40jsii/go-runtime/jsii-runtime-go/runtime.go#L403) were added which you may prefer for `ExposedHeaders` in your code.

oh very cool!

**Comment by corymhall** [comment]
@MrArnoldPalmer how often are new releases made to `aws/constructs`? I see that the fix was already merged so just curious on the release.

**Comment by MrArnoldPalmer** [comment]
Constructs is mostly as needed. I'll try and get this out in the next 24 hours to unblock you.
