### ISSUE TITLE
Inconsistent construction of data types and constructs 

### ISSUE THREAD

**Issue by fulghum** [aws/jsii#279]
Data type classes versus Construct classes have inconsistent experience for creation.
ex: CodeProperty – have to guess whether to call new or builder pattern.  Inconsistent and confusing.

(might be more of a CDK codebase issue than a jsii issue..)

**Comment by fulghum** [comment]
@RomainMuller and @bmaizels – does the switch to builders address any of this feedback that we received?  Any thoughts on this one?

**Comment by bmaizels** [comment]
I think this is covered by other tasks (switching to builders and create)

**Comment by RomainMuller** [comment]
Resolving in favor of #488
