### ISSUE TITLE
Is there a way to include additional files in a built package?

### ISSUE THREAD

**Issue by grantHarris** [aws/jsii#2795]
### Affected Languages

- [ ] `TypeScript` or `Javascript`
- [ ] `Python`
- [ ] `Java`
- [ ] .NET (`C#`, `F#`, ...)
- [ ] `Go`

### General Information
* **JSII Version:** 
* **Platform:**     

### The Question

Is there a way to include additional files and have them added to the package as part of the build step? With our use case we have a Dockerfile and a shell script we want to include in the package along with the built output.

**Comment by RomainMuller** [comment]
The npm package produced is just a normal npm package. This means if it is bundled by `npm pack`, it will be shipping as part of your library.

What conditions what is included in the package is:
- The `files` section of the `package.json` file
- A `.npmignore` file (and if absent, a `.gitignore` file is used if present)

Your TypeScript code can refer to those files by resolving their relative path using `__dirname` for example.

**Comment by grantHarris** [comment]
This doesn't appear to work for building when python is a target (works for JS)

**Comment by patrickylam** [comment]
@RomainMuller - added for visibility
