### ISSUE TITLE
how jsii-pacmak exclude files/folders from npm package?

### ISSUE THREAD

**Issue by zxkane** [aws/jsii#2801]
## :question: Guidance

I have a cdk construct repo with example application project, the `jsii-pacmak` packages entire example folder(having `ts` source files) with its node_modules to final npm package! Is there any way to exclude the files/folders when packing the source? Or is it a feature request of `jsii-pacmak`?

the code repo is,
https://github.com/zxkane/snat

### Affected Languages

- [x] `TypeScript` or `Javascript`
- [ ] `Python`
- [ ] `Java`
- [ ] .NET (`C#`, `F#`, ...)
- [ ] `Go`

### General Information
* **JSII Version:**  1.28.0 (build 1801f4f), typescript 3.9.9
* **Platform:**      Ubuntu 18.04.5 LTS (Bionic Beaver)

**Comment by RomainMuller** [comment]
The mechanism here is the standard `npm` behavior:
- `package.json`'s `files` property
- `.npmignore` file if it exists
- `.gitignore` file if no `.npmignore` file exists

The `node_modules` directory should always be excluded however (except for packages included in `bundleDependencies`).

**Comment by zxkane** [comment]
Thanks for those deep dive information. It would be nice adding it to doc.

Ps: free to close the issue.

**Comment by peterwoodworth** [comment]
closing since issue is resolved
