### ISSUE TITLE
Sharing constants between languages

### ISSUE THREAD

**Issue by flemjame-at-amazon** [aws/jsii#2810]
### Affected Languages
- [x] `TypeScript` or `Javascript`
- [x] `Python`
- [x] `Java`
- [x] .NET (`C#`, `F#`, ...)
- [x] `Go`

### Description
We use CDK in typescript for our AWS infrastructure, and our application code is sometimes in other languages like java or python. There are cases where we need to have some constant values (usually strings) that are shared between our TS CDK code and our application code (e.g. the name of a DynamoDB table, S3 bucket). It is possible to hard code this information in both the CDK and application code, but this introduces the possibility of having a mismatch, leading to some sort of problem with the application.

It would be fantastic if we could share constants (especially typed constants, like an enum) between languages automatically. This is possible with jsii today, but the main drawback is that it requires that an application include the Node runtime to run JSII.

**Comment by RomainMuller** [comment]
Not sure what the issue is here... As you said, this feature is already supported by `jsii` today... If the problem is the node dependency... then this is a different issue (i.e: make jsii no longer require node to be user-managed)...

**Comment by flemjame-at-amazon** [comment]
> Not sure what the issue is here... As you said, this feature is already supported by `jsii` today... If the problem is the node dependency... then this is a different issue (i.e: make jsii no longer require node to be user-managed)...

@RomainMuller the issue is that there are cases where we can't easily include the Node runtime, like AWS Lambda, which doesn't have e.g. a Java + Lambda runtime managed by AWS. We'd prefer not to have to create our own runtime just to take advantage of JSII for constants.
