### ISSUE TITLE
Consider whether we should remove namespace support from jsii

### ISSUE THREAD

**Issue by eladb** [aws/jsii#283]
We are seeing issues implementing interfaces in various languages (e.g. python #270). Those are also not considered a very good practice in typescript (awslabs/aws-cdk#878). Perhaps we should get rid of them in jsii?

**Comment by jasdel** [comment]
Removing this namespaces  would prevent issues with language that do not support nested namespaces. If the concept of nested declaration is needed, using a submodule would be more flexible. But jsii should assert no circular module department exist

**Comment by eladb** [comment]
Now that https://github.com/awslabs/aws-cdk/issues/878 is resolved we can safely remove namespaces from Jsii

**Comment by RomainMuller** [comment]
We are going to go the submodules route (see #1286). This means the current namespace support will evolve into something more robust. I'm resolving this in favor of #1286
