### ISSUE TITLE
Java List compile error: incompatible types

### ISSUE THREAD

**Issue by Nycto** [aws/jsii#2839]
### Affected Languages

- [ ] `TypeScript` or `Javascript`
- [ ] `Python`
- [X] `Java`
- [ ] .NET (`C#`, `F#`, ...)
- [ ] `Go`

### General Information
* **JSII Version:** `1.29.0 (build 41df200), typescript 3.9.9`
* **Platform:** `Linux uaa6ba883bfd45a.ant.amazon.com 5.4.0-72-generic #80~18.04.1-Ubuntu SMP Mon Apr 12 23:26:25 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

### What is the problem?
Java builders are producing invalid code when one of the arguments is a list. Here is some sample code that shows the bug:

```
export interface SomeData {}

export interface TestProps {}

export class Test {
  public constructor(readonly foo: SomeData[], readonly props?: TestProps) { }
}
```

Which causes the following java compiling error:

```
build/private/pacmak-output/java/src/main/java/com/example/Test.java:58: error: incompatible types: List<CAP#1> cannot be converted to List<SomeData>
                this.foo,
                    ^
  where CAP#1 is a fresh type-variable:
    CAP#1 extends SomeData from capture of ? extends SomeData
```

The fully generated Java class loks like this:

```java
package com.example;

@javax.annotation.Generated(value = "jsii-pacmak/1.29.0 (build 41df200)", date = "2021-05-13T23:16:22.437Z")
@software.amazon.jsii.Jsii(module = com.example.$Module.class, fqn = "@amzn/provisioner-cdk-bootstrap.Test")
public class Test extends software.amazon.jsii.JsiiObject {

    protected Test(final software.amazon.jsii.JsiiObjectRef objRef) {
        super(objRef);
    }

    protected Test(final software.amazon.jsii.JsiiObject.InitializationMode initializationMode) {
        super(initializationMode);
    }

    public Test(final @org.jetbrains.annotations.NotNull java.util.List<com.example.SomeData> foo, final @org.jetbrains.annotations.Nullable com.example.TestProps props) {
        super(software.amazon.jsii.JsiiObject.InitializationMode.JSII);
        software.amazon.jsii.JsiiEngine.getInstance().createNewObject(this, new Object[] { java.util.Objects.requireNonNull(foo, "foo is required"), props });
    }

    public Test(final @org.jetbrains.annotations.NotNull java.util.List<com.example.SomeData> foo) {
        super(software.amazon.jsii.JsiiObject.InitializationMode.JSII);
        software.amazon.jsii.JsiiEngine.getInstance().createNewObject(this, new Object[] { java.util.Objects.requireNonNull(foo, "foo is required") });
    }

    public @org.jetbrains.annotations.NotNull java.util.List<com.example.SomeData> getFoo() {
        return java.util.Collections.unmodifiableList(software.amazon.jsii.Kernel.get(this, "foo", software.amazon.jsii.NativeType.listOf(software.amazon.jsii.NativeType.forClass(com.example.SomeData.class))));
    }

    public @org.jetbrains.annotations.Nullable com.example.TestProps getProps() {
        return software.amazon.jsii.Kernel.get(this, "props", software.amazon.jsii.NativeType.forClass(com.example.TestProps.class));
    }

    /**
     * A fluent builder for {@link com.example.Test}.
     */
    public static final class Builder implements software.amazon.jsii.Builder<com.example.Test> {
        /**
         * @return a new instance of {@link Builder}.
         * @param foo This parameter is required.
         */
        public static Builder create(final java.util.List<? extends com.example.SomeData> foo) {
            return new Builder(foo);
        }

        private final java.util.List<? extends com.example.SomeData> foo;
        private com.example.TestProps.Builder props;

        private Builder(final java.util.List<? extends com.example.SomeData> foo) {
            this.foo = foo;
        }

        /**
         * @returns a newly built instance of {@link com.example.Test}.
         */
        @Override
        public com.example.Test build() {
            return new com.example.Test(
                this.foo,
                this.props != null ? this.props.build() : null
            );
        }

        private com.example.TestProps.Builder props() {
            if (this.props == null) {
                this.props = new com.example.TestProps.Builder();
            }
            return this.props;
        }
    }
}
```

### Verbose Log

```
JSII PacMak version: 1.29.0 (build 41df200) from /home/ANT.AMAZON.COM/jfrasca/ws/fern/env/JsiiBuild-1.0/runtime/bin/jsii-pacmak
[jsii-pacmak] [INFO] Found 1 modules to package
[jsii-pacmak] [INFO] Packaging NPM bundles
[jsii-pacmak] [INFO] Loading jsii assemblies and translations
[jsii-pacmak] [INFO] Packaging 'dotnet' for 0 modules
[jsii-pacmak] [INFO] Packaging 'go' for 0 modules
[jsii-pacmak] [INFO] Packaging 'java' for @amzn/provisioner-cdk-bootstrap
[jsii-pacmak] [INFO] Packaging 'js' for @amzn/provisioner-cdk-bootstrap
[jsii-pacmak] [INFO] Packaging 'python' for 0 modules
[jsii-pacmak] [INFO] dotnet finished
[jsii-pacmak] [INFO] go finished
[jsii-pacmak] [INFO] python finished
[jsii-pacmak] [INFO] js finished
[jsii-pacmak] [INFO] java finished
[jsii-pacmak] [INFO] Packaged. load jsii (42.1s) | npm pack (1.3s) | java (0.1s) | js (0.1s) | dotnet (0.0s) | go (0.0s) | cleanup (0.0s) | python (???)
```

**Comment by Nycto** [comment]
I'm willing to try my hand at fixing this, but a question before I do:

Would you prefer the type to use covariants everywhere (`java.util.List<? extends com.example.SomeData>`)? Or get rid of the covariance for list types in the builder (`java.util.List<com.example.SomeData>`)?

Or if there is some other option here, let me know

**Comment by jsteinich** [comment]
I also just ran into this. Seems to be an issue with maps as well.
I assume covariants everywhere would be desired given #1653.

**Comment by Nycto** [comment]
I started to investigate tonight, and I'm thinking that while using covariants seems to be optimal, this comment implies that they _can't_ be used in this situation:

https://github.com/aws/jsii/blob/main/packages/jsii-pacmak/lib/targets/java.ts#L2647

**Comment by jsteinich** [comment]
Given that comment (which does make sense), perhaps we could simply cast the builder value where it is calling the constructor.

**Comment by Nycto** [comment]
Hmm. The Java compiler itself thinks these two types are incompatible, which is what led to this in the first place. Are we confident enough that the compiler is wrong to add a cast?

Basically, I see casting as a “break glass in case of emergency” tool in Java. I want to double check that we’re sure it’s warranted.

But to be clear: not my repository. So I’m happy to listen to others here if there is general support for adding a cast.

**Comment by jsteinich** [comment]
Ordinarily this type of cast could lead to runtime crashes as after casting a less specific type could be added to the list while later the original reference is accessed expecting the more specific type; however, I don't believe the JSII runtime will ever modify the list.

I believe the original issue (#1517) which inspired adding covariants would be better solved by #1807, but that's quite a project.

To summarize some of the tradeoffs:

- Removing covariants
  - Potentially a breaking change
  - Makes it harder to use lists or maps especially when a Typescript union
- Adding cast in builder assignment
  - Not very clean
  - Theoretically introduces potentially runtime errors, but I don't believe it will in practice
- Adding covariants other places
  - Just pushes issues to a different spot
  - Either need to make similar choice when overriding or not do covariant when override is detected

@RomainMuller any thoughts on the issue?

**Comment by Nycto** [comment]
Thank you for breaking that down. Seriously appreciated.

I’m not sure this is a breaking change, though. I don’t think covariants ever worked in this specific piece of code, so nobody would have ever been able to use them. Basically — no tests broke when I changed this. Which either means it’s a reasonably safe change, or a new test needs to be added to ensure the required functionality remains unchanged.

Based on the ticket you linked, it seems like Unions should be the focus. I’ll add a test with a union and see how it goes.

**Comment by jsteinich** [comment]
> I’m not sure this is a breaking change, though. I don’t think covariants ever worked in this specific piece of code, so nobody would have ever been able to use them

I'm thinking that as well, though it is hard to believe that this has been broken since August of last year and gone unnoticed.
