### ISSUE TITLE
Allow Dedicated Export of Types

### ISSUE THREAD

**Issue by skorfmann** [aws/jsii#2889]
### Affected Languages

- [x] `TypeScript` or `Javascript`
- [ ] `Python`
- [ ] `Java`
- [ ] .NET (`C#`, `F#`, ...)
- [ ] `Go`

### General Information
* **JSII Version:** `1.30.0 (build adae23f), typescript 3.9.10`
* **Platform:**     `Darwin Kernel Version 20.3.0`

* [x] I may be able to implement this feature request

* [ ] This feature might incur a breaking change

### Description

```ts
interface ActivityFailedEventDetails {
  /**
   * <p>The error code of the failure.</p>
   */
  readonly error?: string;
  /**
   * <p>A more detailed explanation of the cause of the failure.</p>
   */
  readonly cause?: string;
}

export { ActivityFailedEventDetails }
```

Throws an error `error JSII3001: Type "ActivityFailedEventDetails" cannot be used as the property type because it is private or @internal`

Rewriting as

```ts
export interface ActivityFailedEventDetails {
  /**
   * <p>The error code of the failure.</p>
   */
  readonly error?: string;
  /**
   * <p>A more detailed explanation of the cause of the failure.</p>
   */
  readonly cause?: string;
}
```

Works as expected.

### Proposed Solution

Both examples as shown above should work.

**Comment by RomainMuller** [comment]
This particular syntax trumps the check that verifies a given symbol is exported, as the `export` is not present on the value declaration itself... but instead is somewhere else.

It should be possible to support the "deferred export" syntax however... It might require tracking more state than we currently do and may be a non-trivial change. That being said, I would absolutely accept a PR that implements this.
