### ISSUE TITLE
Should reject changing method visibility while overriding

### ISSUE THREAD

**Issue by rix0rrr** [aws/jsii#289]
The following is NOT allowed in C#:

```
class A {
    protected fn() {
    }
}

class B extends A {
    public fn() {
    }
}
```

I honestly don't understand why, it seems like yet another perfectly reasonable thing to allow, but like Return Value Covariance it's one of those things that C# draws a hard line on and so we have to disallow it in jsii.

**Comment by RomainMuller** [comment]
Closed by #1876
