### ISSUE TITLE
How could I use the java library after I generate the jar by npm run build && npm run package

### ISSUE THREAD

**Issue by jianweic** [aws/jsii#2966]
I test the compilation and package is working fine and manage to use mvn to deploy it but how can I use the library

Example I generate the jar by this sample npm run build && npm run package
https://github.com/aws-samples/jsii-code-samples

Other language is work fine for me.
-->
- [/] `Java`

### General Information
* **Platform:**     MACOS
I use below command to deploy:

Use repo https://github.com/jianweic/jsii-code-samples and run

```
mvn --batch-mode  deploy "-DaltDeploymentRepository=github::default::https://maven.pkg.github.com//jianweic/jsii-code-samples"
```
To
https://github.com/jianweic/jsii-code-samples/packages/950765

I create demo as below and install it by mvn install but cannot use the library by pom.xml below
https://github.com/jianweic/ccw-demo-backend
```
...
	<repositories>
		<repository>
          <id>github</id>
          <url>https://maven.pkg.github.com/ajianweic/jsii-code-samples</url>
          <snapshots>
            <enabled>true</enabled>
          </snapshots>
    </repository>

  </repositories>
  <dependencies>
<dependency>
  <groupId>software.aws.jsiisamples.jsii</groupId>
  <artifactId>jsii-code-samples</artifactId>
  <version>1.7.0</version>
</dependency>
...
```

### The Question
[1]: How I use the java library, jar to call the HelloWorld?
[2]: I couldn't use import affinidi.aws.jsiisamples.jsii.HelloWorld after locally or  deploy , can some guide on how can test the java jar?

**Comment by jianweic** [comment]
Is there issue on the jsii to generete java libary, that's why it cannot be use?

**Comment by RomainMuller** [comment]
Hey @jianweic, if you have copied excerpts from your `pom.xml` here (and not re-typed it), then I think your issue might be a typo you have in there:


```
<url>https://maven.pkg.github.com/ajianweic/jsii-code-samples</url>
                                  ^-- spurious 'a' here 
```

Anyhow - can you please elaborate what error you end up facing? It'll help figure out where it comes from...
