### ISSUE TITLE
(rosetta) Java codegen issues

### ISSUE THREAD

**Issue by rix0rrr** [aws/jsii#2984]
### Affected Languages
- [ ] `TypeScript` or `Javascript`
- [ ] `Python`
- [x] `Java`
- [ ] .NET (`C#`, `F#`, ...)
- [ ] `Go`

### Example doesn't correctly initialize struct (requires research)

On:

https://docs.aws.amazon.com/cdk/api/latest/java/index.html

```java
 // Example automatically generated. See https://github.com/aws/jsii/issues/826
 Object vpc = Vpc.Builder.create(this, "TheVPC")
         .natGateways(1)
         .subnetConfiguration(asList(Map.of(
                 "cidrMask", 26,
                 "name", "Public",
                 "subnetType", ec2.SubnetType.getPUBLIC()), Map.of(
                 "cidrMask", 26,
                 "name", "Application1",
                 "subnetType", ec2.SubnetType.getPRIVATE_WITH_NAT()), Map.of(
                 "cidrMask", 26,
                 "name", "Application2",
                 "subnetType", ec2.SubnetType.getPRIVATE_WITH_NAT(),
                 "reserved", true), Map.of(
                 "cidrMask", 27,
                 "name", "Database",
                 "subnetType", ec2.SubnetType.getISOLATED())))
         .build();
 ```

That should be detecting a list of `SubnetConfiguration` structs, but is detecting a list of JSON objects.

(Caused by the example not typechecking properly? Although the comment indicates it has been compiled...)

### Example doesn't correctly detect constants (requires research)

In the same example on https://docs.aws.amazon.com/cdk/api/latest/java/index.html

```java
                 "subnetType", ec2.SubnetType.getPRIVATE_WITH_NAT()), Map.of(
 ```

Should look like `ec2.SubnetType.PRIVATE_WITH_NAT`.

### Structs don't use builders (easy fix)

On the same page https://docs.aws.amazon.com/cdk/api/latest/java/index.html

```java
  NatInstanceProvider natGatewayProvider = ec2.NatProvider.instance(new NatInstanceProps()
         .instanceType(new InstanceType("t3.small")));
```

`new NatInstanceProps()` is not the way to instantiate a struct. It should use `new NatInstanceProps.Builder().instanceType(...).build())`.

**Comment by iliapolo** [comment]
> Example doesn't correctly detect constants (requires research)

Interesting. This is exactly the comment I made on the `jsii-docgen` [PR](https://github.com/cdklabs/jsii-docgen/pull/435) for adding code snippets for properties:

https://github.com/cdklabs/jsii-docgen/pull/435#discussion_r706819167

Could rosetta be suffering from the same bug?

**Comment by rix0rrr** [comment]
Probably!

**Comment by rix0rrr** [comment]
Here's another Java issue:

`asList()` is potentially correct, but confusing because it heavily depends on a particular static import that may not be common. Should be replaced with `List.asList()` for better compatibility.

**Comment by skinny85** [comment]
I made the call about `asList()`, and my justification was that `List.asList()` would be too verbose. But it's kind of inconsistent with `Map.of()`, so I can definitely see changing that.

**Comment by rix0rrr** [comment]
All issues have been resolved
