### ISSUE TITLE
Default tsconfig.json option `forceConsistentCasingInFileNames` to `True` to create case consistency between filesystems

### ISSUE THREAD

**Issue by dsilbergleithcu-godaddy** [aws/jsii#3013]
### Affected Languages

- [ ] `TypeScript` or `Javascript`
- [ ] `Python`
- [ ] `Java`
- [ ] .NET (`C#`, `F#`, ...)
- [ ] `Go`

### General Information
* **JSII Version:** 6.14.14
* **Platform:** MacOS Big Sur

* [x] I may be able to implement this feature request

* [x] This feature might incur a breaking change

### Description

Typescript relies on the case sensitivity of the filesystem when it checks the paths for imports.  This creates issues when developing on a Win/Mac box but running CICD on Linux.  It is possible to get an "all clear" from the local build, and then fail in the CICD system if a filename doesn't match the casing of the import.

### Proposed Solution

By default, set the `forceConsistentCasingInFileNames` to `true` in the default options of the generated `tsconfig.json` file 

There appear to be 2 places where the compiler options for tsc are set:
* https://github.com/aws/jsii/blob/main/packages/jsii/lib/compiler.ts
* https://github.com/aws/jsii/blob/main/packages/jsii-rosetta/lib/typescript/ts-compiler.ts

I believe the first one will impact the compiler and generate the desired output.  I'm not sure what the function of the second one is.  It is likely a good idea to update both.

**Comment by RomainMuller** [comment]
I'm in favour of this feature, however this can probably be considered a breaking change (not sure). We might need to make this an opt-in setting?

**Comment by dsilbergleithcu-godaddy** [comment]
I had a similar thought about this being a breaking change.  Let me see about making this `opt-in`.  

I'll back out the changes to `jsii-rosetta`.  Thanks for the feedback.

**Comment by dsilbergleithcu-godaddy** [comment]
@RomainMuller I've updated my PR to reflect your comments.  Please take a look when you get a chance.
