### ISSUE TITLE
(rosetta) csharp constructor name does not matching class

### ISSUE THREAD

**Issue by mbonig** [aws/jsii#3056]
## :bug: Bug Report

Starting with TS:

```ts
export class MySimpleWebsite extends Construct {
  constructor(scope: Construct, id: string) {
    super(scope, id);
    const myBucket = new Bucket(this, 'MyBucket');
    new Distribution(this, 'MyDistribution', {
      defaultBehavior: { origin: new S3Origin(myBucket) },
    });
  }
}
```

renders to csharp using Rosetta as:

```csharp
class MySimpleWebsite : Construct
{
    public MyClass(Construct scope, string id) : base(scope, id)
    {
        var myBucket = new Bucket(this, "MyBucket");
        new Distribution(this, "MyDistribution", new Struct {
            DefaultBehavior = new Struct { Origin = new S3Origin(myBucket) }
        });
    }
}
```

with this config:

```ts
  const rosetta = new Rosetta({
    liveConversion: true,
    targetLanguages: [TargetLanguage.PYTHON, TargetLanguage.CSHARP, TargetLanguage.JAVA]
  })
  const translated = rosetta.translateSnippet({
    visibleSource: contents.join('\n'),
    where: 'example'
  }, language);
  
```

### Affected Languages

- [ ] `TypeScript` or `Javascript`
- [ ] `Python`
- [ ] `Java`
- [X] .NET (`C#`, `F#`, ...)
- [ ] `Go`

### General Information
* **JSII Version:** no global or local jsii installed, only jsii-rosetta and used as an api. jsii-rosetta@1.38.0 in package
* **Platform:**    Linux carbon 5.11.0-37-generic #41-Ubuntu SMP Mon Sep 20 16:39:20 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### What is the problem?

The constructor name should match the class name in csharp. Seems fine in Java:

```java
public class MySimpleWebsite extends Construct {
    public MySimpleWebsite(Construct scope, String id) {
        super(scope, id);
        Object myBucket = new Bucket(this, "MyBucket");
        Distribution.Builder.create(this, "MyDistribution")
                .defaultBehavior(Map.of("origin", new S3Origin(myBucket)))
                .build();
    }
}
```

### Verbose Log
None additional I can supply, I don't think.

**Comment by rix0rrr** [comment]
> The constructor name should match the class name in csharp.

I'm not sure what the actual report is because you didn't say, but I'm going to guess you mean the `new Struct`s in there.

Those are probably a result of the example not compiling successfully, so the translator doesn't know the type name that corresponds to `{ origin: new S3Origin(myBucket) }` (for example). 

Whether or not this works depends heavily on the `imports`, the current modules installed via NPM, and potentially your fixture. Since you didn't post any of those, it's hard to say.

**Comment by mbonig** [comment]
> > The constructor name should match the class name in csharp.
> 
> I'm not sure what the actual report is because you didn't say, but I'm going to guess you mean the `new Struct`s in there.
> 

the csharp that was rendered:

```csharp
class MySimpleWebsite : Construct
{
    public MyClass(Construct scope, string id) : base(scope, id)
    {
        var myBucket = new Bucket(this, "MyBucket");
        new Distribution(this, "MyDistribution", new Struct {
            DefaultBehavior = new Struct { Origin = new S3Origin(myBucket) }
        });
    }
}
```

Notice the "MyClass" for the constructor name.

and yes, also wondered about the Struct but wasn't sure that was an actual issue.
