### ISSUE TITLE
JSii generates an incorrect type in aws_eks (Python)

### ISSUE THREAD

**Issue by otaviomacedo** [aws/jsii#3070]
### Affected Languages

- [ ] `TypeScript` or `Javascript`
- [X] `Python`
- [ ] `Java`
- [ ] .NET (`C#`, `F#`, ...)
- [ ] `Go`

### General Information
* **JSII Version:** 1.39.0 (build 8af72c2), typescript 3.9.10
* **Platform:** Darwin Kernel Version 20.4.0: Thu Apr 22 21:46:47 PDT 2021; root:xnu-7195.101.2~1/RELEASE_X86_64 x86_64

### What is the problem?

The method `EndpointAccess.only_from`, from the `aws_eks` Python module has a parameter `cidr` of type string. But in the [source code], it is an array of string:

```python
class EndpointAccess(
    metaclass=jsii.JSIIMeta,
    jsii_type="@aws-cdk/aws-eks.EndpointAccess",
):
    '''Endpoint access characteristics.'''

    @jsii.member(jsii_name="onlyFrom")
    def only_from(self, *cidr: builtins.str) -> "EndpointAccess":
        '''Restrict public access to specific CIDR blocks.

        If public access is disabled, this method will result in an error.

        :param cidr: CIDR blocks.
        '''
        return typing.cast("EndpointAccess", jsii.invoke(self, "onlyFrom", [*cidr]))
```

Original bug: https://github.com/aws/aws-cdk/issues/16661

[1]: https://gist.github.com
[source code]: https://github.com/aws/aws-cdk/blob/7f7be089fa84afd0ab009a7feca2df4315749bc3/packages/@aws-cdk/aws-eks/lib/cluster.ts#L625-->

**Comment by shcherbak** [comment]
we are still suffering of this issue

**Comment by sumupitchayan** [comment]
It also looks like the [documentation page](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_eks.EndpointAccess.html#onlywbrfromcidr) shows the incorrect parameter type for `cidr` in TS:

<img width="826" alt="Screenshot 2024-07-17 at 1 40 36 PM" src="https://github.com/user-attachments/assets/5ff8f516-6b95-4a9d-98ab-d8ea6703618d">

I believe it should say `cidr string[] — CIDR blocks` under Parameters instead

**Comment by sumupitchayan** [comment]
Closing as a non-issue.

> The method EndpointAccess.only_from, from the aws_eks Python module has a parameter cidr of type string. But in the [source code](https://github.com/aws/aws-cdk/blob/7f7be089fa84afd0ab009a7feca2df4315749bc3/packages/@aws-cdk/aws-eks/lib/cluster.ts#L625--%3E), it is an array of string:

This is incorrect --`*cidr: builtins.str` in python denotes a variadic string argument, where it accepts multiple strings (where each individual argument is still of type `str`).

The TS [source code]([source code](https://github.com/aws/aws-cdk/blob/7f7be089fa84afd0ab009a7feca2df4315749bc3/packages/@aws-cdk/aws-eks/lib/cluster.ts#L625--%3E)) you linked also represents the same thing: `...cidr: string[]` is a rest parameter that allows the method to accept any number of `string` arguments.

The docs might be slightly confusing if you haven't encountered variadic arguments before, but it is correct.

**Comment by iliapolo** [comment]
@sumupitchayan it looks like doc generation is incorrect here, both on the [documentation page](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_eks.EndpointAccess.html#onlywbrfromcidr) and on [construct hub](https://constructs.dev/packages/aws-cdk-lib/v/2.153.0/api/EndpointAccess?lang=typescript&submodule=aws_eks#onlyFrom)

Can you check if `jsii-docgen` already has a bug filed for this? same for the documentation? (documentation page bugs should be filed in the CDK repo).

**Comment by sumupitchayan** [comment]
> @sumupitchayan it looks like doc generation is incorrect here, both on the [documentation page](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_eks.EndpointAccess.html#onlywbrfromcidr) and on [construct hub](https://constructs.dev/packages/aws-cdk-lib/v/2.153.0/api/EndpointAccess?lang=typescript&submodule=aws_eks#onlyFrom)
> 
> Can you check if `jsii-docgen` already has a bug filed for this? same for the documentation? (documentation page bugs should be filed in the CDK repo).

@iliapolo yes there is an issue for exactly this in `jsii-docgen`, looks like you filed it 😄 [#648](https://github.com/cdklabs/jsii-docgen/issues/648)

I guess we can still mark this issue as closed since we have one in docgen to track this bug.
