### ISSUE TITLE
Add aws-cdk build as an integration test for jsii

### ISSUE THREAD

**Issue by eladb** [aws/jsii#309]
It should be simple to build the aws-cdk as an integration test for jsii.

**Comment by fulghum** [comment]
Have we made any progress on this one?  Do we still need this one?  Should we pull it onto the project board?

**Comment by rix0rrr** [comment]
I think it would be okay for us not to have this. It's not a risk, it's more that there's a chance of lost productivity when integrating a new version of jsii into the CDK build.

**Comment by eladb** [comment]
+1

**Comment by MrArnoldPalmer** [comment]
Romain and I discussed reopening this now. The extra step feels like an easy way to get some extra assurance as we move forward with various JSII fixes/features.

@rix0rrr @eladb objections?

**Comment by eladb** [comment]
Not at all. Go for it!

**Comment by MrArnoldPalmer** [comment]
Closing in favor of #1209
