### ISSUE TITLE
Huge performance impact due to `whiteoutLeadingComments` calls

### ISSUE THREAD

**Issue by ansgarm** [aws/jsii#3091]
### Affected Languages

- [ ] `TypeScript` or `Javascript`
- [x] `Python`
- [ ] `Java`
- [ ] .NET (`C#`, `F#`, ...)
- [ ] `Go`

(possibly others as well)

### General Information
* **JSII Version: 1.37.0 (build a6fe12f), typescript 3.9.10**
* **Platform: OS X**     

### What is the problem?

Hi! I just did some CPU profiling of our `cdktf get` command as its execution time increased substantially over the course of the last months. The cause for this was probably the growing AWS Terraform provider – which can take up to an hour to build in CI nowadays.

It appears that calls to [`whiteoutLeadingComments`](https://github.com/aws/jsii/blob/137bb19e22eaed6cd8a58f40c99ee1c373c70643/packages/jsii/lib/transforms/ts-comment-replacer.ts#L122-L133) take a lot of time:

![image](https://user-images.githubusercontent.com/1112056/138701793-91ae7eac-598b-4370-93b1-a691890cfe15.png)

I was able to confirm this locally by commenting out the body of `whiteoutLeadingComments` which brought the invocation of JSII (with Python configured) down to 90 seconds (from 1270s).

Is there a way we could e.g. introduce caching for the result of `whiteoutLeadingComments` or `computeLineStarts` to improve the performance?

#### Reproduce

To reproduce the long build times, clone [repo](https://github.com/ansgarm/cdktf-jsii-performance) and run `cdktf get`.

**Comment by indrora** [comment]
This function appears to have either been renamed or rolled in elsewhere. Is this still a bottleneck?

**Comment by ansgarm** [comment]
I'd need to check – but I think we can close this one. All our issues that linked to this are closed by now, too. So if we revisit (i.e. profile) JSII performance at some point in the future, we'll just raise a new up-to-date issue if we find something like this again 👍
