### ISSUE TITLE
Disambiguate the response types

### ISSUE THREAD

**Issue by dstufft** [aws/jsii#31]
Currently it's not possible to parse a response from the ``jsii-runtime`` into a typed structure without your parser knowing ahead of time what type it is expecting. It would be great if the ``jsii-runtime`` would include enough information in the response to know what type the response is, then a parser could parse it into a typed structure without relying on out of band information.

This could be as simple as just adding an extra key alongside the ``ok`` key, that included that information in it.

**Comment by RomainMuller** [comment]
This also allows to prevent many kinds of bugs that can arise from incorrect interpretations of ambiguous situations.
