### ISSUE TITLE
reduced fidelity regarding peer dependencies

### ISSUE THREAD

**Issue by eladb** [aws/jsii#310]
PR #306 reduced the fidelity of the version information since there was no way to distinguish between the version required as a normal dependency and the version required as a peer, and there is no way to indicate that a dependency is only required as a peer.

**Comment by rix0rrr** [comment]
In what case does it fail?

**Comment by eladb** [comment]
Updated the title: this is just about loss of fidelity. The failure was actually legitimate since the peer didn't semver-match the normal dependency.
