### ISSUE TITLE
(jsii) `--add-deprecated-warnings` flag should not add warning when a non-deprecated class inherits a deprecated class

### ISSUE THREAD

**Issue by nija-at** [aws/jsii#3102]
## :bug: Bug Report

It is acceptable for a non-deprecated class to inherit a deprecated class.
The `--strip-deprecated` flag correctly handles this, by not exporting the deprecated class and treating it as a private member.

However, the `--add-deprecated-warnings` flag does not account for this. It produces a warning when the non-deprecated subclass is used.

Example: 

https://github.com/aws/aws-cdk/blob/c4ba858278bffe1a987ea8200c313f17f7f1cbe9/packages/%40aws-cdk/core/lib/bundling.ts#L251

`BundlingDockerImage` here is deprecated.

**Comment by nija-at** [comment]
Another example -

https://github.com/aws/aws-cdk/blob/db63fba358a5a8cc3d252156d14ead57d2b7560d/packages/%40aws-cdk/aws-ecr-assets/lib/image-asset.ts#L58

`DockerImageAssetOptions` is not deprecated whereas `FingerprintOptions` is.

**Comment by NGL321** [comment]
@otaviomacedo was this resolved with #3112?
