### ISSUE TITLE
Keywords should be forbidden as namespace names

### ISSUE THREAD

**Issue by DanielMSchmidt** [aws/jsii#3178]
### Affected Languages

- [ ] `TypeScript` or `Javascript`
- [X] `Python`
- [X] `Java`
- [X] .NET (`C#`, `F#`, ...)
- [X] `Go`

### General Information
* **JSII Version:** 1.37 and above
* **Platform:**     all

* [X] I may be able to implement this feature request

* [ ] This feature might incur a breaking change

### Description

When working with namespaces one can use names that are keywords in languages other than TS, resulting in invalid generated code. In our case it broke python when using the namespace `lambda` for AWS Lambda Resources.

### Proposed Solution

Similar to other parts I'd expect an error to be thrown from JSII when a namespace with a keyword is detected.

**Comment by indrora** [comment]
It looks like there's a list of reserved words for each language: https://github.com/aws/jsii/blob/main/packages/jsii/lib/reserved-words.ts

It looks like this isn't used while generating namespaces.

**Comment by ansgarm** [comment]
Whoops, please re-open this one 😇
