### ISSUE TITLE
Literate examples in submodule READMEs are not resolved

### ISSUE THREAD

**Issue by rix0rrr** [aws/jsii#3267]
## :bug: Bug Report

See https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_s3_assets-readme.html

![image](https://user-images.githubusercontent.com/524162/146517127-b8dd64f4-9d42-4820-951c-b85b2ffee5f8.png)

Those should have been code examples instead of non-working links.

**Comment by Chriscbr** [comment]
Another example: (https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_ec2-readme.html#using-nat-instances)

<img width="641" alt="Screen Shot 2022-02-14 at 2 24 51 PM" src="https://user-images.githubusercontent.com/5008987/153956739-2b98479b-99d0-4a4f-836e-d240d4584763.png">
