### ISSUE TITLE
add yaml struct tags for generated golang structs

### ISSUE THREAD

**Issue by Hunter-Thompson** [aws/jsii#3293]
### Affected Languages

- [ ] `TypeScript` or `Javascript`
- [ ] `Python`
- [ ] `Java`
- [ ] .NET (`C#`, `F#`, ...)
- [x] `Go`

### General Information
* **JSII Version:** 1.46.0
* **Platform:**     N/A

* [x] I may be able to implement this feature request

* [ ] This feature might incur a breaking change

### Description
In Go, JSII generates structs with json struct tags :

```
type ProviderConfig struct {
    Data *string `json:"data"`
}
```

It would be nice to have yaml struct tags too. While marshaling/unmarshaling this would help.

### Proposed Solution
```
type ProviderConfig struct {
    Data *string `json:"data" yaml:"data"`
}
```

### Notes

If you could point me to the file which does this I may be able to write a PR.

**Comment by MrArnoldPalmer** [comment]
I see no problem with this, but I'm wondering what your use case is? The JSON struct tags are generated to help marshaling/demarshalling as JSII types are serialized to JSON when passed to the kernel via stdin, and deserialized when received from the kernel via stdout.

Generally the struct tags aren't meant to be seen by consumers of generated JSII Go modules and are an implementation detail, though there may be some uses I'm not considering.

**Comment by Hunter-Thompson** [comment]
> Generally the struct tags aren't meant to be seen by consumers of generated JSII Go modules and are an implementation detail, though there may be some uses I'm not considering.

When we create a construct library in cdk8s using TS, since the generated structs in golang only have JSON struct tags, I cannot use those structs to marshal YAML data into it.

Lets look at an interface:

```ts
export interface CustomInterface {
    readonly config: Config;
}

export interface Config {
    readonly containerName: string;
    readonly containerImage: string
}
```

The generated structs for this would be : 

```go
type struct CustomInterface {
    Config Config `json:"config"`
}

type struct Config {
    ContainerName string `json:"containerName"`
    ContainerImage string `json:"containerImage"`
}
```

The application I'm building marshalls data into the CustomInterface struct from a YAML config which would look like this for our CustomInterface:

```yaml
config:
  containerName: test
  containerImage: test-image:latest
```

Then it takes those values and then creates a new container definition in cdk8s.

```go
podSpec := &k8s.PodSpec{
    Containers: &[]*k8s.Container{
        {
            Name:  jsii.String(config.containerName),
            Image: jsii.String(config.containerImage),
        },
    },
}
```

Sort of like helm without the madness : )

The problem here is that the camelCase is not being respected by the Marshaller, thats why yaml struct tags are necessary. I hope I was able to convey my use case.

**Comment by MrArnoldPalmer** [comment]
gotcha, so your application accepts some yaml configuration loaded and deserialized and passed as args to cdk8s constructs? Seems straightforward enough and I don't see any downside to enabling easier yaml deserialization. 👍🏻

**Comment by Hunter-Thompson** [comment]
> gotcha, so your application accepts some yaml configuration loaded and deserialized and passed as args to cdk8s constructs? 

yep you nailed it.
