### ISSUE TITLE
Go Pacmak OOM Crash and Performance

### ISSUE THREAD

**Issue by MrArnoldPalmer** [aws/jsii#3361]
We have received reports that jsii-pacmak can run out of memory causing crashes on large packages while doing Go code generation. Additionally we have seen the time it takes to generate go packages is significantly higher than other languages.

This is somewhat expected as the Go code generation is built differently than the other languages since it is the only generator that was built with submodule support in mind. There may be a number of easy optimizations to reduce memory usage and overall runtime via memoization during both first pass AST generation and second pass output.

**Comment by ansgarm** [comment]
This is resolved by #3362, isn't it?

**Comment by MrArnoldPalmer** [comment]
correct, should be improved in the next release.
