### ISSUE TITLE
Generated python code has syntax errors while ts code works

### ISSUE THREAD

**Issue by yiduyangyi** [aws/jsii#3402]
### Affected Languages

- [ ] `TypeScript` or `Javascript`
- [x] `Python`
- [ ] `Java`
- [ ] .NET (`C#`, `F#`, ...)
- [ ] `Go`

### General Information
* **JSII Version:** 
1.54.0
* **Platform:**     
Darwin C02Z2DYSLVCF 20.6.0 Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:21 PDT 2021; root:xnu-7195.141.6~3/RELEASE_X86_64 x86_64

### The Question

I meet some syntax errors in generated python code(TypeScript code just works correctly).  such as 
1. class declaration code is behind the use of the class in  the generated __init__.py
2. circle dependency in  the generated __init__.py

**Comment by RomainMuller** [comment]
Hey!

Would you be able to share a reproduction of your problem? This would help us diagnose and either fix it, or add compile-time detection of the issue (certain circular dependency patters simply cannot be implemented in Python).
