### ISSUE TITLE
CORS Error despite thoroughly reading CDK docs, CDK docs error in the public reference

### ISSUE THREAD

**Issue by wendysophie** [aws/jsii#3448]
### Affected Languages

- [ ] `TypeScript` or `Javascript`
- [ X] `Python`
- [ ] `Java`
- [ ] .NET (`C#`, `F#`, ...)
- [ ] `Go`

### General Information
* **JSII Version:** 
* **Platform:**     

### What is the problem?

The documentation about the AWS CDK for python when specifying the integration response, and method response wrongly put an extra under score on the "_access-_control-_allow-_origin", instead, the correct naming should be "Access-Control-Allow-Origin" which caused the customer's application not working even after throughly read the CDK docs.

I have attached the screen cap that customer shared with the ticket. The extra underscore could affect other parameter as well across the documentation.

### Verbose Log
[

**Comment by RomainMuller** [comment]
Hey! Thanks for reporting this!

There is indeed a bug in the Python transliteration suite which will cause it to incorrectly translate map keys in this particular context. I've issued a [PR](https://github.com/aws/jsii/pull/3449) with a fix.
