### ISSUE TITLE
What does "JSII" stand for?

### ISSUE THREAD

**Issue by james-yun** [aws/jsii#3490]
### Describe the issue

What does JSII stand for? JavaScript Idiomatic Interpreter?

Could very well be the case that JSII is not an acronym, it's the full name of the project whose original meaning no longer represents what the project is about (like LLVM - Low Level Virtual Machine).

Either way, a sentence in the documentation explaining this would satisfy my curiosity :)

### Links

https://aws.github.io/jsii/

**Comment by NGL321** [comment]
I believe @RomainMuller could explain his naming reasoning better, but I believe that its intentional there is no further expansion on the name "JSII" 😆

**Comment by RomainMuller** [comment]
> JavaScript Interop Interface - JSii!

Absolute definite no from me. It does not mean this.

"jsii" is not an acronym, same as "npm" is not an acronym (https://en.wikipedia.org/wiki/Npm).

**Comment by jadnaim** [comment]
watch --> https://youtu.be/AYYTrDaEwLs at the 6:58 min mark.

**Comment by MeatAcorn** [comment]
Wouldn't be an acronym anyway, you pronounce acronyms like NASA but not initialisms like FBI.
