### ISSUE TITLE
Add GoVisitor to rosetta index.ts

### ISSUE THREAD

**Issue by jsteinich** [aws/jsii#3552]
### Describe the feature

Export `GoVisitor` in https://github.com/aws/jsii/blob/main/packages/jsii-rosetta/lib/index.ts

### Use Case

Currently in order to use `GoVisitor` need something like:
```typescript
import * as rosetta from "jsii-rosetta";
import { GoVisitor } from "jsii-rosetta/lib/languages/go";
rosetta.translateTypeScript(file, new GoVisitor());
```

For C# you can just do
```typescript
import * as rosetta from "jsii-rosetta";
rosetta.translateTypeScript(file, new rosetta.CSharpVisitor());
```

### Proposed Solution

Just add
```typescript
export { GoVisitor } from './languages/go';
```
to https://github.com/aws/jsii/blob/main/packages/jsii-rosetta/lib/index.ts

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

CDKTF

### Environment details (OS name and version, etc.)

docker.mirror.hashicorp.services/hashicorp/jsii-terraform (based on jsii/superchain)

**Comment by MrArnoldPalmer** [comment]
@jsteinich this seems fine to me, curious what your usecase is, are you calling rosetta programmatically?

@rix0rrr any reason we should not make language visitors available on the public api?

**Comment by jsteinich** [comment]
> curious what your usecase is, are you calling rosetta programmatically?

Yes. Rosetta is being invoked programmatically. The main use case is via the `cdktf` cli where Terraform HCL is transformed into code in the chosen language. There is also a script used to help translate some integration tests into supported languages.

**Comment by NGL321** [comment]
@MrArnoldPalmer since all the other available language visitors are exposed, if its decided not to expose go, the exports should probably be removed for the others too.
