### ISSUE TITLE
java: jsii date timezones are not supported

### ISSUE THREAD

**Issue by eladb** [aws/jsii#356]
We currently use `Instant`

**Comment by bmaizels** [comment]
Need help with a TS compliance/repro case so that I understand what's being asked for here.

**Comment by RomainMuller** [comment]
Hey @eladb  can you please explain in more detail what the issue is here? I don't know that supporting arbitrary timezones is necessary here, as JavaScript does not allow you to control the timezone of `Date` instances as far as I know...
