### ISSUE TITLE
Awkward Java/Python/... enum constant names

### ISSUE THREAD

**Issue by RomainMuller** [aws/jsii#359]
Some enum constant names have names that translate somewhat awkwardly:

```java
// wrong on so many levels:
Runtime.NODE_J_S810; 
```

Noticed in aws-samples/aws-cdk-intro-workshop#22

**Comment by dstufft** [comment]
This doesn't just happen in Java, but happens in Python as well (for the same reasons).

**Comment by RomainMuller** [comment]
This has been solved as now `jsii` requires enum constants to use `TRUMP_CASE`. Resolving.
