### ISSUE TITLE
jsii on a monorepo using Nx is not picking up packages from the root package.json

### ISSUE THREAD

**Issue by ivandjomegni** [aws/jsii#3599]
### Describe the bug

I have set up a monorepo using Nx where I have packages/libraries for custom aws CDK modules. 

At the root package.json file, I have specified to use the latest versions of packages for aws-cdk-lib, constructs, jsii and others so they can be used by each module inside the monorepo.

Inside the module-specific package.json file I have a jsii script that when I run it, it throws me an error saying it encountered use of module that is not declared in "dependencies" or "peerDependencies", instead of picking it up from the root package.json

The workaround I found is to define both aws-cdk-lib and constructs inside each module-specific package.json file as dependencies and install them again there before jsii can run successfully, which removes the feature of a monorepo to share packages already defined at the root level

Note: all imports from the modules constructs work, finding the packages defined at the root level

```ts
import iam = require('aws-cdk-lib/aws-iam');
import { Aws, CfnOutput, Tags} from 'aws-cdk-lib';
import { CfnInstanceProfile } from 'aws-cdk-lib/aws-iam';
import {Construct} from 'constructs';
```

### Expected Behavior

My goal is that as a monorepo, jsii should look for the shared packages defined at the root package.json file, rather than on the module-specific package.json and successfully compile the module, so that packages defined at the module-specific level should only be packages that are specific to the module, if any.

### Current Behavior

Unable to resolve type "constructs.Construct". It may be @internal or not exported from the module's entry point (as configured in "package.json" as "main").

```
 14 export class COMPANYIAMSLRoleConstruct extends Construct {
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 15     public readonly iamSlRole: iam.CfnServiceLinkedRole;
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
... 
 75       })
    ~~~~~~~~
 76   }}
    ~~~~
lib/COMPANYIAMSLRoleConstruct.ts:15:21 - error JSII9000: Encountered use of module that is not declared in "dependencies" or "peerDependencies": "aws-cdk-lib"

15     public readonly iamSlRole: iam.CfnServiceLinkedRole;
                       ~~~~~~~~~
lib/COMPANYIAMSLRoleConstruct.ts:16:15 - error JSII9000: Encountered use of module that is not declared in "dependencies" or "peerDependencies": "constructs"
```

### Reproduction Steps

- **Generating an Nx Monorepo :** npx create-nx-workspace happynrwl --preset=ts
- Adding the aws-cdk-lib, constructs, and jsii packages inside the root package.json
- **Generating a node library :** nx g @nrwl/node:lib company-cdk-moduleName --publishable --importPath="@company-cdk/moduleName"
- setting up the node library to use a aws cdk module
- add the required key-value at the library-specific package.json (name, version, description, main, types, author, jsii)
- Navigate to the node library under packages/libraryName and run jsii

Sample code of library-specific package.json : 

```json
{
  "name": "@company-cdk/iam",
  "version": "4.0.0",
  "description": "COMPANY CDK Custom Module for Amazon IAM",
  "license": "MIT",
  "type": "commonjs"
  },
  "keywords": [
    "cdk",
    "npm",
    "package",
    "iam",
    "aws-iam"
  ],
  "author": {
    "name": "Ivan, Djomegni",
  },
  "publishConfig": {
    "registry": "<registryURL>"
  },
  "jsii": {
    "outdir": "../../dist/",
    "targets": {
      "python": {
        "distName": "company-cdk.iam",
        "module": "company_cdk.iam",
        "classifiers": [
          "Framework :: AWS CDK",
          "Framework :: AWS CDK :: 1"
        ]
      }
    }
  },
  "main": "lib/index.js",
  "types": "lib/index.d.ts",
  "scripts": {
    "tsc": "tsc",
    "watch": "tsc -w",
    "test": "jest --passWithNoTests",
    "cdk": "cdk",
    "buildp": "rm -f tsconfig.json && jsii && jsii-docgen",
    "package": "jsii-pacmak -v",
    "installLibrarySpecificPackages": "rm -rf package-lock.json && npm update && npm install",
    "diff": "cdk diff -c Stage=ops --app test/integ.default.js",
    "deploy": "cdk deploy -c Stage=ops --app test/integ.default.js --require-approval=never"
  }
}
```

### SDK version used

CDK

### Environment details (OS name and version, etc.)

cloud9 running linux

**Comment by RomainMuller** [comment]
`jsii` will only consider dependencies that are declared in the current package's `package.json` file, and will intentionally ignore those that are not declared... A valid `jsii` package has (at the very least) `peerDependencies` on the jsii modules it depends on.

**Comment by Oatelaus** [comment]
@RomainMuller as far as node is concerned having the peerDependency defined within the root level package should imply for all the child packages. This feels very much so like jsii isn't implementing a core language feature - can you confirm this is a "won't support"?

**Comment by gocapa** [comment]
Having the same issue. Any updates?
