### ISSUE TITLE
.NET L1 namespaces are awkward

### ISSUE THREAD

**Issue by rix0rrr** [aws/jsii#364]
I think the .NET generator should do something else for the nested property types of L1 classes.

Right for a, say, ELB listener, it creates the following:

```

class CfnListener_ {
}

namespace ..CDK.Elbv2.CfnLIstener {
   class ThisProperty { }
   class ThatProperty { }
}
```

Has the result that the main class has a trailing `_`, and the namespace that's created to hold the property types shows up in the left-hand side navigation panel of the reference docs I'm building.

Can we not simply do concatenation? 

```
class CfnListener {
}

class CfnListenerThisProperty { }
class CfnListenerThatProperty { }
```

etc?

**Comment by rix0rrr** [comment]
@costleya @eladb

**Comment by assyadh** [comment]
The new generator is using nested types. 

So now it looks cleaner:

```
CfnListener.ThisProperty
```
