### ISSUE TITLE
Version 1.62.0 causes CDK deployments to fail (Unable to deserialize value as aws-cdk-lib.aws_iam.RoleProps)

### ISSUE THREAD

**Issue by ChrisDowning** [aws/jsii#3677]
### Describe the bug

When deploying a CDK stack (CDK==2.23, jsii automatically resolved to 1.61) about a month ago, the deployment worked as expected and completed successfully.

When redeploying today (CDK==2.23, jsii automatically resolved to 1.62), deployment failed with the following error (within a CDK Pipeline CodeBuild job):
```
[Container] 2022/07/25 18:31:31 Running command cdk synth
jsii.errors.JavaScriptError: 
  @jsii/kernel.SerializationError: Passed to parameter props of new aws-cdk-lib.aws_iam.Role: Unable to deserialize value as aws-cdk-lib.aws_iam.RoleProps
  ├── 🛑 Failing value is an object
  │      { '$jsii.struct': [Object] }
  ╰── 🔍 Failure reason(s):
      ╰─ Key 'inlinePolicies': Unable to deserialize value as map<aws-cdk-lib.aws_iam.PolicyDocument> | undefined
          ├── 🛑 Failing value is an array
          │      [ [Object] ]
          ╰── 🔍 Failure reason(s):
              ╰─ Value is an array
```

Manually setting the jsii version to match the previously-working version (CDK==2.23, jsii==1.61), the deployment completed successfully.

### Expected Behavior

Expect jsii 1.62 to be drop-in compatible with 1.61 for a given, fixed version of CDK.

### Current Behavior

Allowing jsii version to resolve automatically resulted in using the newest version, which contains a bug (or at least, is incompatible with CDK 2.23).

### Reproduction Steps

Example CDK code which is the source of the error (minimized/generalized to remove sensitive information):
```
...
        ExamplePolicyDocument = _iam.PolicyDocument(
            statements=[
                _iam.PolicyStatement(
                    effect=_iam.Effect.ALLOW,
                    resources=["*"],
                    actions=[
                        "sts:assumeRole",
                        "sts:SetSourceIdentity"
                    ]
                )
            ]
        )

...

        lambda_job_role = _iam.Role(
            self,
            "ExampleRole",
            assumed_by=_iam.ServicePrincipal("lambda.amazonaws.com"),
            description="Example role",
            managed_policies=[
                _iam.ManagedPolicy.from_aws_managed_policy_name(
                    "service-role/AWSLambdaVPCAccessExecutionRole"
                ),
                _iam.ManagedPolicy.from_aws_managed_policy_name("AWSBatchFullAccess")
            ],
            inline_policies=[ExamplePolicyDocument],
        )
```

### SDK version used

1.61 and 1.62

### Environment details (OS name and version, etc.)

Amazon Linux 2, CodeBuild job, CDK v2.23

**Comment by RomainMuller** [comment]
So... `inline_policies` is typed as `typing.Optional[typing.Mapping[builtins.str, PolicyDocument]]`, and so an array was _never_ a valid value there. It very likely only accidentally worked before, and running a type-checker on your code would most likely have told you this invocation is not valid...

You'd actually need to have
```python
        lambda_job_role = _iam.Role(
            self,
            "ExampleRole",
            assumed_by=_iam.ServicePrincipal("lambda.amazonaws.com"),
            description="Example role",
            managed_policies=[
                _iam.ManagedPolicy.from_aws_managed_policy_name(
                    "service-role/AWSLambdaVPCAccessExecutionRole"
                ),
                _iam.ManagedPolicy.from_aws_managed_policy_name("AWSBatchFullAccess")
            ],
            inline_policies={
				"example": ExamplePolicyDocument,
			},
        )
```
