### ISSUE TITLE
Missing .jsii file

### ISSUE THREAD

**Issue by automartin5000** [aws/jsii#3678]
### Describe the bug

When using jsii.tsc.outDir config in `package.json`, everything compiles and packages correctly, however when attempting to run `cdk synth` in a Python package, an error is thrown: `Expected to find .jsii file in /var/folders...jsii-kernel-K2nLps/node_modules/<package_name>, but no such file found`

### Expected Behavior

No error

### Current Behavior

`
jsii.errors.JSIIError: Error for package tarball /Users/......jsii.tgz: Expected to find .jsii file in /var/folders...jsii-kernel-K2nLps/node_modules/<package_name>, but no such file found
`

### Reproduction Steps

1. Add the following to `package.json`
 `   "tsc": {
      "outDir": "bin",
      "rootDir": "src"
    }
`
2. Run `jsii`
3. Run `jsii-pacmak`
4. `pip install` in Python application
5. `cdk synth`

### Possible Solution

¯\_(ツ)_/¯

### SDK version used

1.62.0

### Environment details (OS name and version, etc.)

Mac OS 12.4

**Comment by automartin5000** [comment]
Looks like this might be happening all the time now and not just with `tsc.outDir`, still unsure what the problem is though.

**Comment by m1n9o** [comment]
Yeah, I got the same error with jsii 1.63.1.

**Comment by m1n9o** [comment]
Is there any workaround for this?

**Comment by RomainMuller** [comment]
Running `jsii` should create the `.jsii` file, unless compilation fails. I am currently unable to reproduce this issue... is there a chance you could provide pointers to the code that fails in this way?

**Comment by YuriGal** [comment]
I am starting to get this too.
```
(.venv) ygalanter@LaptopM-LVDT consumer % cdk synth
jsii.errors.JavaScriptError: 
  @jsii/kernel.Fault: Error for package tarball /Users/ygalanter/Documents/Github/cdk-jsii-example/consumer/.venv/lib/python3.11/site-packages/library_cdk_codepipeline_notifier/_jsii/library-cdk-codepipeline-notifier@0.0.3.jsii.tgz: Expected to find .jsii file in /var/folders/7_/xlqtzx8x103c36hpbylvg_zrxbpfzb/T/jsii-kernel-5WHEAp/node_modules/@diligentcorp/library-cdk-codepipeline-notifier, but no such file found
      at Kernel._load (/private/var/folders/7_/xlqtzx8x103c36hpbylvg_zrxbpfzb/T/tmplzr0lnp1/lib/program.js:7723:27)
      at /private/var/folders/7_/xlqtzx8x103c36hpbylvg_zrxbpfzb/T/tmplzr0lnp1/lib/program.js:7683:52
      at Kernel._debugTime (/private/var/folders/7_/xlqtzx8x103c36hpbylvg_zrxbpfzb/T/tmplzr0lnp1/lib/program.js:8406:28)
      at Kernel.load (/private/var/folders/7_/xlqtzx8x103c36hpbylvg_zrxbpfzb/T/tmplzr0lnp1/lib/program.js:7683:29)
      at KernelHost.processRequest (/private/var/folders/7_/xlqtzx8x103c36hpbylvg_zrxbpfzb/T/tmplzr0lnp1/lib/program.js:11037:36)
      at KernelHost.run (/private/var/folders/7_/xlqtzx8x103c36hpbylvg_zrxbpfzb/T/tmplzr0lnp1/lib/program.js:10997:22)
      at Immediate._onImmediate (/private/var/folders/7_/xlqtzx8x103c36hpbylvg_zrxbpfzb/T/tmplzr0lnp1/lib/program.js:10998:46)
      at processImmediate (node:internal/timers:466:21)
```
`.jsii` file is produced successfully when source is built

**Comment by cookejames** [comment]
I'm also experiencing this issue without setting a tsc outdir

**Comment by sirjoe** [comment]
Has anyone found a solution to this? I'm also experiencing the same issue. Have exhausted all avenues to resolve this.

**Comment by sirjoe** [comment]
> .jsii file is produced successfully when source is built

@YuriGal Did you manage to resolve this issue?
