### ISSUE TITLE
JSII only has one number type for both float and integer values.

### ISSUE THREAD

**Issue by jasdel** [aws/jsii#371]
Most languages that JSII language bindings could be created for, distinguish the difference between an integer and float type number. Since JSII only defines one number type, language bindings are forced to use the lowest common denominator of float64 for all number type parameters.

I think this creates a poor user experience for user's using code generated from JSII models for a language which does distinguish the difference between decimals and integers. Using float for all numbers has the following issues:
* Languages, (e,g, Go) with strong typing force users to explicitly convert between integers and floats. Requiring users to do unexpected extra steps to work with code generated from JSII models.
* Undefined API behavior providing a fractional value when logically only integers make sense, (e.g number of EC2 Instances). Will the number be rounded up, down, floored, or ceilinged.
* Lose of data, Users attempting to use a significantly large int64 number will lose precision when converting that int64 into a float64 value.

Given that JSII is based on Typescript/Javascript, I'm not really sure if there is anything that can be done about this issue. But, it would be helpful to define the behavior if customers do provide fractional numbers for APIs that logically expect integers. Potentially some way to annotate the resulting JSII model that a language binding should use integers instead of floats.

**Comment by RomainMuller** [comment]
As you have guessed, the reason for this is that *JavaScript* does not have integers. It however has been an itch to me for some time and I would also like to prevent floating point numbers through paths where only integers will be accepted.

**Comment by rts-rob** [comment]
We would like to use JSII for a project but are blocked by this issue. Is there any workaround?
