### ISSUE TITLE
Remove dependence on global "node" executable

### ISSUE THREAD

**Issue by pauldraper** [aws/jsii#3725]
### Describe the feature

This project relies on a "node" executable on PATH, regardless of what node.js executable is used to run cdk.

https://github.com/aws/jsii/blob/main/packages/%40jsii/python-runtime/src/jsii/_kernel/providers/process.py#L251

### Use Case

Node.js may not be installed globally. Or perhaps it is installed, but not named "node." E.g. node18, node19  similar to python2, python3.

### Proposed Solution

Use an env var, like

```
NODE_RUNTIME=/usr/local/bin/node18
```

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

*

### Environment details (OS name and version, etc.)

*

**Comment by mrgrain** [comment]
Resolved by https://github.com/aws/jsii/pull/4024

**Comment by pauldraper** [comment]
Thank you!

**Comment by mrgrain** [comment]
No worries. It's been resolved for ages. Apologies for missing the ticket. Let me know if that works for you.
