### ISSUE TITLE
Causes JavaScriptError in AWS CDK api-gateway

### ISSUE THREAD

**Issue by cn-cit** [aws/jsii#3742]
### Describe the bug

When using the AWS CDK api gateway Model.EMPTY_MODEL (or ERROR_MODEL) the cdk stacks cannot synthesize or deploy.

### Expected Behavior

The AWS CDK will not error when using the api gateway Model.EMPTY_MODEL

### Current Behavior

 @jsii/kernel.SerializationError: Of static property aws-cdk-lib.aws_apigateway.Model.EMPTY_MODEL: Unable to serialize value as aws-cdk-lib.aws_apigateway.IModel
🛑 Failing value is an instance of aws-cdk-lib.aws_apigateway.EmptyModel
 EmptyModel { modelId: 'Empty' }
 ╰── 🔍 Failure reason(s):
 ╰─ Type 'aws-cdk-lib.aws_apigateway.EmptyModel' not found
at Object.process (/tmp/tmpdm_u1x99/lib/program.js:6194:19)

### Reproduction Steps

use a Java cdk project and include this anywhere ...
`        Map<String, IModel> emptyResponseModels = new HashMap<>();
        emptyResponseModels.put("application/json", Model.EMPTY_MODEL);
`
Use 1.67.0 of this library and the error occurs.

### Additional Information/Context

revert back to 1.66.0 to overcome the problem.

### SDK version used

AWS CDK 2.37.1

### Environment details (OS name and version, etc.)

Windows 10

**Comment by RomainMuller** [comment]
Thanks for reporting. I'm able to reproduce the issue.

This is because I attempted to simplify the assembly load procedure by leveraging runtime-type-information woven in by the compiler... which may return FQNs that are actually not exported by the assembly, triggering this bug.

**Comment by RomainMuller** [comment]
Interesting - the `EmptyModel` class _does_ exist and get exported in the library, however it was `@deprecated` in V1 and is soft-removed from V2... this explains why it still has runtime type information bound to it, but does not exist in the model.

The fix I designed still would work there... The best strategy might be to have RTTI _not_ be woven for deprecated types that will be pruned, but this might end up requiring a huge refactor... This might hence still be the best fix.
