### ISSUE TITLE
Streaming bin script output in non-typescript kernels

### ISSUE THREAD

**Issue by jmalins** [aws/jsii#3782]
### Describe the feature

Pipe the output streams of bin scripts invoked from the JSII kernel. Currently, these calls are made using the synchronous `InvokeScriptRequest` / `InvokeScriptResponse` synchronous API. The output is buffered until the call completes. This experience is not ideal for longer running scripts with progressive updates.

### Use Case

Long-running scripts with progressive updates, such as `projen deploy` called under Python via the JSII kernel, rather than a globally installed installed `projen` instance.

These calls were recently made to work via a few updates:
 - https://github.com/aws/jsii/pull/3762
 - https://github.com/projen/projen/pull/2132
 - https://github.com/projen/projen/issues/2103

The experience, however, is not ideal, due to the buffered output.

### Proposed Solution

Maintain the current synchronous (`InvokeScriptRequest` / `InvokeScriptResponse`) API for backwards compatibility, but add a new streaming API that language runtimes can opt into if they are on a platform that supports it. The opt-in approach will allow this to be implemented progressively.

I suspect this will require out-of-band IPC ([local domain sockets or named pipes](https://nodejs.org/api/net.html#ipc-support)) so that it doesn't disrupt the standard kernel connection streams.

I am not an IPC expert, but one (naive) approach on POSIX OSs would be:
 1. language runtime dynamically creates local sockets to receive the target process `stdout` and `stderr`
 2. sockets/FDs identifiers are passed to kernel via a new `InvokeScriptWithStreams` call
 3. kernel opens streams to the argument file descriptors, passes them to `spawnSync` of the target process
 4. language runtime receives data on sockets, streams to `stdout` / `stderr` on the user process
 5. kernel process completes, returns exit code, probably using existing `InvokeScriptResponse` structure

I have a nervous suspicion it is more complicated than this (`termcap`?), and I wouldn't know where to start with Windows. I definitely welcome thoughts on the approach.

### Other Information

My team is very interested in building out a first-rate Python dev-tool experience for JSII based libraries, specifically CDK on projen.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.x

### Environment details (OS name and version, etc.)

MacOS, Linux

**Comment by RomainMuller** [comment]
I wonder if we should reverse control here, and instead of having the kernel spawn the child process on behalf of the caller, it merely returned the `command`, `arguments`, and possibly environment variables that need to be passed to `spawn` or equivalent in the local language?

As you're guessing, the IPC situation in Windows versus POSIX platforms is quite complicated, and it turns out to be relatively easy to introduce subtle bugs when attempting to do this (even `node` fails to completely "hide" the behavioral differences between Windows and the other OS'es).

**Comment by jmalins** [comment]
@RomainMuller that is a _profoundly_ better approach! 👍

How about this for an API, reusing the `InvokeScriptRequest` struct for the argument:
```typescript
// api.ts
export interface GetScriptCommandResponse {
  command: string;
  args: string[];
  env: Record<string, string>;
}

// kernel.ts
export class Kernel {
  // ...
  public getBinScriptCommand(req: api.InvokeScriptRequest): api.GetScriptCommandResponse;
  // ...
}
```
I presume we would retain the existing invoke API for compatibility purposes. It can be refactored to use the new `getBinScriptCommand` method internally.

**Comment by jmalins** [comment]
I realized after getting into the code, that JSII requires a unique argument type for each API call. PR #3794 uses the basic approach above, but with a `GetScriptCommandRequest` argument that mirrors the parameters of the `InvokeScriptRequest`
