### ISSUE TITLE
Consider switching to an in process JS Engine for Python

### ISSUE THREAD

**Issue by dstufft** [aws/jsii#384]
The design of the Python JSII runtime *attempts* to make it easy to potentionally swap out the use of shelling out to a ``node`` process and instead switch to using an in memory process. This effectively represents a trade off:

1) The JSII will no longer be a pure Python package, but instead will contain compiled code.
  - It could fail gracefully and fall back to relies on ``node`` existing.
2) The JSII will no longer depend on an out of band installation of ``node`` to exist on the target machine.

Beyond that, the benefits are that it should ideally speed things up since we'll no longer be paying the cost to marshal everything to JSON and read/write from stdin/stdout.

**Comment by rix0rrr** [comment]
I would love to see you try! 

I just recall that Elad went this way with his Java implementation early on, but ended up stripping it because the interpreter was too slow. Speed gains are possible but not guaranteed.

**Comment by RomainMuller** [comment]
It's also important to note that code may depend on the node standard library, which may not be available in in-process engines and would thus have to be polyfilled.

**Comment by garnaat** [comment]
I think we should close this issue.  We have no compelling reason at this time to switch.  If such a reason emerges later, we will create a new issue.
