### ISSUE TITLE
MyPy throwing type errors when it shouldn't

### ISSUE THREAD

**Issue by alexmv** [aws/jsii#3931]
In the Python CDK, attempting to pass `aws_events_targets.LambdaFunction` as the target of an `events.Rule` fails to typecheck:

```
$ mypy test.py
test.py:19: error: List item 0 has incompatible type "LambdaFunction"; expected "IRuleTarget"
test.py:19: note: 'LambdaFunction' is missing following 'IRuleTarget' protocol member:
test.py:19: note:     __jsii_proxy_class__
Found 1 error in 1 file (checked 1 source file)
```

It does _run_ perfectly fine, however -- this is purely an error in the typesystem.

### Reproduction Steps

```python:test.py
from aws_cdk import aws_events, aws_events_targets, aws_lambda, core

class Example(core.Construct):
    def __init__(self, scope: core.Construct):
        super().__init__(scope, "some-name")
        some_lambda = aws_lambda.Function(
            self,
            "some-handler",
            runtime=aws_lambda.Runtime.PYTHON_3_8,
            code=aws_lambda.AssetCode("some/path"),
            handler="some_package.handler",
            retry_attempts=0,
        )
        aws_events.Rule(
            self,
            "some-rule",
            schedule=aws_events.Schedule.cron(minute="*/5"),
            targets=[aws_events_targets.LambdaFunction(some_lambda)],
        )
```

`pip install mypy && mypy test.py`

### Error Log

```
test.py:19: note: 'LambdaFunction' is missing following 'IRuleTarget' protocol member:
test.py:19: note:     __jsii_proxy_class__
```

### Environment

  - **CLI Version:** 1.17.13
  - **Framework Version:** 1.31.0
  - **OS:**  OS X 10.14.6
  - **Language:** Python 3.8.0 / mypy 0.770

### Other

It is also possible this is a bug in mypy.

---

Possible duplicate: https://github.com/aws/jsii/issues/1262

--- 

This is :bug: Bug Report

**Comment by iliapolo** [comment]
It has been a long while since this issue was last commented on. Both `MyPy` CDK, and jsii have gone through many upgrades. jsii in particular had a few `__jsii_proxy_class__` related PRs:

- https://github.com/aws/jsii/pull/2809
- https://github.com/aws/jsii/pull/4611

Closing as I am unable to reproduce this as of now. Please comment here with an up do date reproduction if you encounter this issue again.
