### ISSUE TITLE
Add *.tsbuildinfo to auto-generated .npmignore file

### ISSUE THREAD

**Issue by m-radzikowski** [aws/jsii#3978]
### Describe the feature

If I'm not mistaken, the `tsconfig.tsbuildinfo` file generated during the `jsii` build should not be part of the output package.

If the `.npmignore` file does not exist, the `jsii-pacmak` generates it automatically. It includes ignores for `*.ts` and `tsconfig.json`, but not `tsconfig.tsbuildinfo`.

### Use Case

Following the documentation, I ended up with a bundle file containing >2 MB `tsconfig.tsbuildinfo` file, being 90% of the package size.

### Proposed Solution

Add `*.tsbuildinfo` here:

https://github.com/aws/jsii/blob/396f6129968e2399206b5026faf0b23a9ee61cd9/packages/jsii-pacmak/lib/npm-modules.ts#L134-L138

### Other Information

jsii and jsii-pacmak v1.75.0

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

-

### Environment details (OS name and version, etc.)

any

**Comment by NextThread** [comment]
hi, added this feature
