### ISSUE TITLE
Conflicting goals around private type and interface handling in jsii

### ISSUE THREAD

**Issue by rix0rrr** [aws/jsii#399]
We currently have a design deficiency in jsii around advertising types of objects in the kernel; however, it can't be fixed (quickly) because the fix will break expected Java behavior (and probably also C# and Python).

## Short intro

Object references are passed over the wire like so:

```
{ "$jsii.byref": "@scope/package.Class@10000" }
```

As can be seen, the token consists both of a type name and an identifier. It's unclear to me whether it's allowed to assign semantics to the class part of the identifier. In the kernel, lookup and storage in an object table happens by the whole string, but the Java runtime definitely splits off the type name and looks up the class name to instantiate based on that type string.

In case the referenced type references an interface, a proxy class for that interface is instantiated instead of the actual class.

## Type derivation in Kernel

The kernel does some type analysis to decide what type to advertise in the type token on the wire, to avoid `ClassCastException`s in strongly-typed client languages, and to allow downcasting. This becomes problematic when the actual type is not an exported JSII type.

Let's say we have the following inheritance hierarchy:

```
┌───────────────┐       ┌ ─ ─ ─ ─ ─ ─ ─ ─ ─ ┐
│ export Super  │──────▶    export ISuper    
└───────────────┘       └ ─ ─ ─ ─ ─ ─ ─ ─ ─ ┘
        ▲                                    
        │                                    
┌───────────────┐       ┌ ─ ─ ─ ─ ─ ─ ─ ─ ─ ┐
│ export Middle │──────▶   export IMiddle    
└───────────────┘       └ ─ ─ ─ ─ ─ ─ ─ ─ ─ ┘
        ▲                                    
        │                                    
┌───────────────┐       ┌ ─ ─ ─ ─ ─ ─ ─ ─ ─ ┐
│     Child     │──────▶    export IChild    
└───────────────┘       └ ─ ─ ─ ─ ─ ─ ─ ─ ─ ┘
```

And we return a `Middle` from a function that declares returning a...

```ts
function returnMe(): T {
  return new Middle();
}
```

* `T = Super`, we return `Middle@10000`.
* `T = ISuper`, we return `Middle@10000`.
* `T = Middle`, we return `Middle@10000`.
* `T = IMiddle`, we return `Middle@10000`.

So, super easy if the type is known in the client language, because the client language can do the substitutability analysis. However, what if we were to return a `Child`? We want to return the most specific type that fits:

```ts
function returnMe(): T {
  return new Child();
}
```

* `T = Super`, we return `Middle@10000`, most specific class.
* `T = ISuper`, we return `Middle@10000`, most specific class.
* `T = Middle`, we return `Middle@10000`, most specific class.
* `T = IMiddle`, we return `Middle@10000`, most specific class.
* `T = IChild`, we return `IChild@10000`, not a class, have the client use an interface proxy.

Why do this at all? It will preserve downcasting in the target language, which is going to be necessary for any API that returns references to objects by a generic type. For example, the following code uses downcasting to access tree members:

```ts
// findChild() becomes useless if it always returns an IConstruct$proxy.
const resource = construct.node.findChild('Resource') as CfnSomeResource;
```

The whole `findChild()` API is not usable over JSII without this feature.

Now, you might think this is too much effort and we might decide we're not going to do most-specific class analysis for unexported objects, and always return the interface type in those cases (leading to a proxy object on the client side).

That's fine, but doesn't fundamentally prevent the issue which I'm going to describe now:

## Caching of type

In order to keep object IDs stable (so that multiple references to the same object return the same object instance), the object reference token is cached on the object on first assignment.

The problem here is that subsequent references to an object might not require the same type:

```ts
// See type hierarchy from before
const child = new Child();

function returnMiddle(): Middle {
  return child;
}

function returnIChild(): IChild {
  return child;
}
```

Depending on the order in which these functions are called, a specific FQN will be cached on the `child` object, which will be wrong for the subsequent call, leading to a `ClassCastException` in Java:

**First call returnMiddle(), then call returnIChild() from Java**

* Call `returnMiddle(): Middle`, returning an instance of an object
* We'll do the analysis and cache`"Middle@10000"` on the object.
* Java constructs an instance of `Middle`, all is well.
* Next call goes to `returnIChild(): IChild`, we'll return the cached value `"Middle@10000"`
* Java will return the same instance of `Middle`.
* Leads to a `ClassCastException` when attempted to be assigned to an `IChild` variable.

When called in reverse order, an `IChild$proxy` will be created which will fail assignment to the `Middle` variable.

## Attempted solution

My attempted solution was to have multiple object identities for different returned types on the same object. For example, in the previous example, we'd return the following object references:

* `Middle@10000`
* `IChild@10001`

Both referring to the same JavaScript object.

Everything will work fine, except comparing objects by identity.

## Java problem

Wouldn't you know it, the Java tests explicitly test that object identity is maintained for objects created in Java-land, which might also implement arbitrary interfaces by which they are accessed. Example from the compliance tests:

```java
class SubclassNativeFriendlyRandom extends Number implements ..., IRandomNumberGenerator
```

This object is created as a `Number`, but subsequently accessed as an `IRandomNumberGenerator`:

```
> { create Number@10000 }
> { get generator }
< { $jsii.byref: IRandomNumberGenerator@10001 }
```

This is the case that caching the identifier had solved, which forced the same identifier to be returned on second access, even though according to the type system visible to JSII `Number` does *not* implement `IRandomNumberGenerator`, but according to Java's type system it does (so no `ClassCastException`).

The tests explicitly assert that the sent and returned objects are the same instances. Note that using the object would have gone fine (except perhaps somewhat downgraded performance since function calls on the object need to roundtrip though JSII instead of being done directly in the JVM), it's the extrafunctional assertion that fails.

EDIT: Oh and downcasting would fail too, of course 😠 

## Fixing it

There are a number of  ways in which we can fix the current issue. To name a few:

* Separating class and interface types on the wire
* Separating type from object identity on the wire
* Having strongly-typed clients pre-annotate freshly created objects with the interfaces an object will support, so that we can map all of them to the same object (and can also validate types on ingress, see below).
* Completely drop interfaces from the wire. The client needs to do assignability analysis and construct the proxy when the returned class is not assignable (and Just Trust(tm) the rest of the type analysis).
* Drop the object identity requirement.

Before we go there, I just want to get the details down and start the discussion.

**Comment by eladb** [comment]
Thanks for the awesome write up. 

I don't think we can drop the object identity requirement. It is a basic property of polymorphism that we can't afford to lose.

The idea of separating the type from object identity on the wire resonates with me. Object identity should have been an opaque ID, and the fact we currently need to parse it in languages like Java is an indication that this was the wrong design choice.

**Comment by rix0rrr** [comment]
Yeah that seems like the simplest solution. The client is then required to keep a table of the form:

```
{ object_id -> { type_fqn -> object_instance }}
```

**Comment by eladb** [comment]
why does it need the FQN? In most cases the FQN is annotated on the type

**Comment by rix0rrr** [comment]
Consider the case where we're returning an instance of `Child` from a method that returns an `IChild`. I can see us returning something like this:

```
< { "$jsii.byref": "Middle@10000", "$jsii.implementing": "IChild" }
```

So we can say "this is an instance of Middle, ID 10000", but we still need an object implementing `IChild` to return, so we're going to need to instantiate a proxy somewhere. The advantage of doing this though is that subsequent returns:

```
< { "$jsii.byref": "Middle@10000", "$jsii.implementing": "IMiddle" }
< { "$jsii.byref": "Middle@10000", "$jsii.implementing": "ISuper" }
< { "$jsii.byref": "Middle@10000" }
```

Can all reuse the same class object from the table (preserving object identity), just not for public interfaces privately implemented. And for objects created in Java, we can prepopulate the table: 

```
jsiiCall(new SubclassNativeFriendlyRandom());

// internal lookup table
10000 -> SubclassNativeFriendlyRandom -> <instance>
         IRandomNumberGenerator -> <instance>
```

It's an unfortunate fact that Java won't have enough information when it first sees a private object, so we're going to have to make do with limited information and enhance as we go along.

Not sure if the JVM will let us change a class after it has been instantiated, but even if it did, doesn't seem like those would be capabilities we should build our runtime on.

**Comment by rix0rrr** [comment]
Here's another interesting dimension to this problem, when the Java private inheritance happens:

Java passes in an object of `{ "$jsii.byref": "Number@10000" }`, when the expected type is `IRandomNumberGenerator`. 

If we were to validate that, we would fail it (which we obviously shouldn't), but avoiding validation completely on object ingress makes it harder to catch errors in other cases.
