### ISSUE TITLE
Python - Some Dependencies Do Not Get Emitted

### ISSUE THREAD

**Issue by dstufft** [aws/jsii#413]
This *might* be a duplicate of https://github.com/awslabs/jsii/issues/361.

Basically, when emitting dependency information the Python generator only cares about peer dependencies, however it appears that some items are dependencies but which are not currently marked as peer dependencies. This surfaces as a missing library at runtime like:

```
Traceback (most recent call last):
  File "app.py", line 2, in <module>
    from aws_cdk import (
  File "/Users/dstufft/projects/aws-cdk-examples/python/application-load-balancer/.env/lib/python3.7/site-packages/aws_cdk/aws_autoscaling/__init__.py", line 13, in <module>
    import aws_cdk.aws_autoscaling_common
ModuleNotFoundError: No module named 'aws_cdk.aws_autoscaling_common'
```

This can be worked around by simply manually installing the missing library (in the above case, ``aws-cdk.aws-autoscaling-common``).

We need to determine if this just needs #361 to be resolved, and get that across the finish line, or if Python should look at more than just peer dependencies and if so, stop filtering to only peer dependencies.

**Comment by RomainMuller** [comment]
@dstufft - #361 has a PR available that you might want to test against.

**Comment by RomainMuller** [comment]
#361 has now shipped, it is possible that the problem is gone!
