### ISSUE TITLE
Superchain: missing permissions for installation of global packages

### ISSUE THREAD

**Issue by Obirah** [aws/jsii#4141]
### Describe the bug

When using the Superchain image (`1-buster-slim-node18` in my case) in GitLab CI and trying to install global NPM packages (e.g. `npm i -g pnpm`), the build fails with a permission denied error indicating that the `superchain` user has no permissions to write to `/usr/lib/node_modules`.

### Expected Behavior

It should be possible to install global NPM packages out-of-the-box.

### Current Behavior

Installing a global NPM package fails with a permission denied error.

### Reproduction Steps

Run a GitLab CI job with the Superchain image and try to install a global package.

### Possible Solution

Give the sufficient permissions to the `superchain` user (or add pnpm to the default tools 😉).

### Additional Information/Context

Current workaround is to change the installation directory for global packages before installing them:

```
mkdir ~/npm-global
npm config set prefix '~/npm-global'
export PATH=~/npm-global/bin:$PATH
npm i -g pnpm
```

### SDK version used

1-buster-slim-node18

### Environment details (OS name and version, etc.)

1-buster-slim-node18 on GitLab CI

**Comment by mrgrain** [comment]
We have sudo available in superchain:
```
sudo npm i -g pnpm
```
