### ISSUE TITLE
jsii-pacmak ignores dist-* files from @aws-sdk/util-utf8-browser

### ISSUE THREAD

**Issue by lalitkumarbTR** [aws/jsii#4178]
### Describe the bug

I have a monorepo of CDK patterns which I build and package using jsii and jsii-pacmak respectively. I need to use few AWS-SDK modules in one of the patterns so I have bundled the following:

```
"bundledDependencies": [
    "@aws-sdk/client-ec2",
    "@aws-sdk/client-codestar-connections",
    "@aws-sdk/client-sts"
  ],
```
I use nohoist in my package.json to ensure these are installed in the node_modules of the required patterns. When I install the dependencies and build the packages I see the following in node_modules:

<img width="303" alt="image" src="https://github.com/aws/jsii/assets/52484805/e8b24759-57d6-4b10-ab90-102ff66a111f">

The three dist- files inside @aws-sdk/util-utf8-browser is the concern which are there in my local. But after I run jsii-pacmak I don't see those three dist- files. I extracted the JS tarball and found them missing. However other util-* modules are not impacted. 

<img width="197" alt="image" src="https://github.com/aws/jsii/assets/52484805/81d76d2f-8873-4503-8eb9-060d26cb9f1d">

Due to these missing files, I get the following error when I run cdk synth/deploy:
```
Error: Cannot find module '<my-project-dir>node_modules/cdk/node_modules/@aws-sdk/util-utf8-browser/dist-cjs/index.js'. Please verify that the package.json has a valid "main" entry
```
Because the main entry is of course in the `"main": "./dist-cjs/index.js",` while it is missing from the JS distribution after running jsii-pacmak. 

### Expected Behavior

jsii-pacmak should include the dist-* file inside @aws-sdk/util-utf8-browser module after creating the JS package. This impacts all other distributions like Java, Python etc. because the modules are not found in the jsii package itself. When I copy those files manually then CDK synth/deploy works fine.

### Current Behavior

```
lalitkumarb@host cdk-patterns % cdk synth
Error: Cannot find module 'packages/cdk-patterns/node_modules/my-cdk/node_modules/@aws-sdk/util-utf8-browser/dist-cjs/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (node:internal/modules/cjs/loader:353:19)
    at Function.Module._findPath (node:internal/modules/cjs/loader:566:18)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (my-cdk/node_modules/@cspotcode/source-map-support/source-map-support.js:811:30)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (packages/cdk-patterns/node_modules/my-cdk/node_modules/@aws-crypto/util/src/convertToBuffer.ts:5:1)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1157:10) {
  code: 'MODULE_NOT_FOUND',
  path: 'packages/cdk-patterns/node_modules/my-cdk/node_modules/@aws-sdk/util-utf8-browser/package.json',
  requestPath: '@aws-sdk/util-utf8-browser'
}

Subprocess exited with error 1
```

### Reproduction Steps

I have created a public repository for reproducing this issue. Please follow the README https://github.com/lalitkumarbTR/jsii-pacmak-issue

### SDK version used

cdk - 2.81.0 (build bd920f2), @aws-sdk "version": "3.363.0"

### Environment details (OS name and version, etc.)

Mac OS Ventura 13.4 local, Ubuntu@latest on GitHub runner

**Comment by lalitkumarbTR** [comment]
For reproducing this issue, I have created a public repo https://github.com/lalitkumarbTR/jsii-pacmak-issue

**Comment by lalitkumarbTR** [comment]
Workaround: **Use node v18.13**

I opened a case with AWS and the support engineer was able to figure out the workaround. The reason it worked on Amazon Linux and not on Ubuntu 20.04/22.04 is because of the node version which is 18.13 on AL2023 while it is 18.17 by default from nvm on Ubuntu. On my laptop MacOS I was running node v16.x and it did not work either, so upgrading to node 18.13 fixed the issue. The active support for node 18(LTS) will end on (18 Oct 2023) per [https://endoflife.date/nodejs ](https://endoflife.date/nodejs) So it would be better to get this issue/bug fixed on all node versions > 18.

**Comment by mrgrain** [comment]
Pretty sure this is due to a change in npm v9 that changed the behavior of `npm pack` which is used under the hood.
https://github.blog/changelog/2022-10-24-npm-v9-0-0-released/

I see in your reproduction example you define `files` in `package.json` which is exactly where the new behavior comes in.
The different results with different node version will be caused by different default npm versions.

You can confirm this by running `npm pack` and inspect the result. If it's also missing the files, than jsii-pacmak behaves as expected.
