### ISSUE TITLE
structural typing allowed in typescript breaks python users

### ISSUE THREAD

**Issue by kaizencc** [aws/jsii#4283]
### Describe the bug

See https://github.com/aws/aws-cdk/pull/27284

```ts
export class A extends B {
  public static create(): A {
    return super.create(); // returns type B
  }
}

export interface AProp {
  readonly aProp: A;
}
```

In TypeScript, this works because of structural typing, TS understands that `B` can be cast to `A`. However, in the jsii-generated Python, this is not the case and the following error is recorded:

```bash
TypeError: type of argument aProp must be one of (module.A); got
module.B instead
```

### Expected Behavior

Since Python cannot handle structural typing, the expected behavior is that jsii returns an error and disallows this.

### Current Behavior

Jsii allows this, resulting in a runtime error in Python

### Reproduction Steps

Create code similar to the example above where TS relies on structural typing to ensure that type `B` is valid type `A`. Then build the python package and run it.

### SDK version used

n/a

### Environment details (OS name and version, etc.)

n/a

**Comment by rix0rrr** [comment]
It's not just Python. This won't work in any nominally typed language (Java or C#) either.

Also cannot be fixed, since we can't detect this happening on the TS side.
