### ISSUE TITLE
Python packages from @user/package-name have non-compliant names

### ISSUE THREAD

**Issue by mikejgray** [aws/jsii#4390]
### Describe the bug

As identified [in this repo](https://github.com/mbonig/state-machine/issues/37), JSII is generating a Python package from a TypeScript project called `@mbonig/state-machine`. That package is named `mbonig.state-machine` in Python, which is not a valid Python package name, and cannot be imported using Python's default `import` statement.

### Expected Behavior

Package names like `@mbonig/state-machine` would translate to something like `mbonig_state_machine`.

### Current Behavior

The Python package is named `mbonig.state-machine` and has an unnecessarily nested structure as follows:

```zsh
❯ tree /Users/Mike/Library/Caches/pypoetry/virtualenvs/mbonig-statemachine--IYWOJtL-py3.11/lib/python3.11/site-packages/mbonig
/Users/Mike/Library/Caches/pypoetry/virtualenvs/mbonig-statemachine--IYWOJtL-py3.11/lib/python3.11/site-packages/mbonig
└── state-machine
    ├── __init__.py
    ├── __pycache__
    │   └── __init__.cpython-311.pyc
    ├── _jsii
    │   ├── __init__.py
    │   ├── __pycache__
    │   │   └── __init__.cpython-311.pyc
    │   └── state-machine@0.0.32.jsii.tgz
    └── py.typed

5 directories, 6 files
```

### Reproduction Steps

```zsh
# Reproduced on Python 3.10 and 3.11
python -m venv .venv
source .venv/bin/activate
pip install mbonig.state-machine
touch main.py
```

`main.py`
```python
import mbonig.state_machine  # throws an exception
import mbonig_state_machine  # throws an exception

# Workaround, which will load the package properly
import importlib
mbonig_state_machine = importlib.import_module("mbonig.state-machine")
```

### Possible Solution

I'm not sure why this is happening, because when I untar the JavaScript the structure is pretty flat. I suspect the directory structure is being generated somehow based on the namespace but I'm not familiar with how that works.

```zsh
❯ tree /Users/Mike/Library/Caches/pypoetry/virtualenvs/mbonig-statemachine--IYWOJtL-py3.11/lib/python3.11/site-packages/mbonig/state-machine/_jsii/package/
/Users/Mike/Library/Caches/pypoetry/virtualenvs/mbonig-statemachine--IYWOJtL-py3.11/lib/python3.11/site-packages/mbonig/state-machine/_jsii/package/
├── API.md
├── LICENSE
├── README.md
├── node_modules
│   ├── ...
├── lib
│   ├── BuildStateType.d.ts
│   ├── BuildStateType.js
│   ├── StateMachine.d.ts
│   ├── StateMachine.js
│   ├── StepFunctionsAutoDiscover.d.ts
│   ├── StepFunctionsAutoDiscover.js
│   ├── index.d.ts
│   └── index.js
└── package.json

14 directories, 64 files
```

### Additional Information/Context

jsii@1.82.0, jsii@1.x:
  version "1.82.0"
  resolved "https://registry.yarnpkg.com/jsii/-/jsii-1.82.0.tgz#dbc5d61853619a0fb7653539663832ae1c2bf2a5"
  integrity sha512-EMOjpWCiRYCo5ZzndGXsSsMrBSj4sa7njzEcFWryVnXj6reVP2axwsa3AXC/xCf4/PjchESxGDbSieX7cP9A+A==
  dependencies:
    "@jsii/check-node" "1.82.0"
    "@jsii/spec" "^1.82.0"
    case "^1.6.3"
    chalk "^4"
    fast-deep-equal "^3.1.3"
    fs-extra "^10.1.0"
    log4js "^6.9.1"
    semver "^7.5.1"
    semver-intersect "^1.4.0"
    sort-json "^2.0.1"
    spdx-license-list "^6.6.0"
    typescript "~3.9.10"
    yargs "^16.2.0"

jsii@1.93.0:
  version "1.93.0"
  resolved "https://registry.yarnpkg.com/jsii/-/jsii-1.93.0.tgz#a30e077883235c7fdd09772e0637eeefeef975d9"
  integrity sha512-J6In5MDWcmVosOwZxdwcW+NisQZ2p9g2zWFwCO3RpMoHmpzYasChZSvRvpgR5iFB7m10QRebU+45R2WCGsadfg==
  dependencies:
    "@jsii/check-node" "1.93.0"
    "@jsii/spec" "^1.93.0"
    case "^1.6.3"
    chalk "^4"
    fast-deep-equal "^3.1.3"
    fs-extra "^10.1.0"
    log4js "^6.9.1"
    semver "^7.5.4"
    semver-intersect "^1.4.0"
    sort-json "^2.0.1"
    spdx-license-list "^6.8.0"
    typescript "~3.9.10"
    yargs "^16.2.0"

### SDK version used

1.82.0

### Environment details (OS name and version, etc.)

I reproduced with Mac OS Ventura 13.5.1 (22G90) on a MacBook Air M1

**Comment by mbonig** [comment]
I think this is more on my set up of the jsii config.
