### ISSUE TITLE
dotnet: optional enum passes a value and not undefined

### ISSUE THREAD

**Issue by eladb** [aws/jsii#446]
See awslabs/aws-cdk#2240

**Comment by eladb** [comment]
@costleya can you please take a look?

**Comment by wmmagee** [comment]
I looked into this a bit and here's what I've seen.  Null values are not allowed for "primitives" in C#.  The code that creates the C# types checks if an optional is a primitive and converts that to a Nullable of that primitive type so a null value will be possible.  The enum values are really just ints and so have the same issue that they need to be converted to a Nullable but JSII doesn't mark them as primitive.

The conversion of a primitive to a Nullable happens in the Amazon.JSII.Generator.SymbolMap.GetTypeSyntax function.

**Comment by McDoit** [comment]
Seems to be related, and fixed, in this issue?
https://github.com/awslabs/jsii/issues/414
