### ISSUE TITLE
Support nested object property

### ISSUE THREAD

**Issue by tmokmss** [aws/jsii#4465]
### Describe the feature

Allow us to use a nested object as a prop to a construct. Something like this:

```ts
interface SomeConstructProps {
  readonly propA: {
    readonly propAA: string;
    readonly propAB: string;
  }
  readonly propB: string;
}
```

Currently we get an error when trying to use such definition: `error JSII1003: Only string-indexed map types are supported`

### Use Case

I'm currently building a construct library for OpenSearch resources. In OpenSearch REST API, nested property structures are heavily used, for example: [create a role](https://opensearch.org/docs/latest/security/access-control/api/#create-role). I want to naturally map this structure to my TypeScript code, but current jsii limitation does not allow that.

```json
{
  "cluster_permissions": [
    "cluster_composite_ops",
    "indices_monitor"
  ],
  "index_permissions": [{
    "index_patterns": [
      "movies*"
    ],
    "dls": "",
    "fls": [],
    "masked_fields": [],
    "allowed_actions": [
      "read"
    ]
  }],
  "tenant_permissions": [{
    "tenant_patterns": [
      "human_resources"
    ],
    "allowed_actions": [
      "kibana_all_read"
    ]
  }]
}
```

```ts
// we want this
  readonly payload: {
    cluster_permissions?: string[];
    index_permissions?: [
      {
        index_patterns?: string[];
        dls?: string;
        fls?: string[];
        masked_fields?: string[];
        allowed_actions?: string[];
      }
    ];
    tenant_permissions?: [
      {
        tenant_patterns?: string[];
        allowed_actions?: string[];
      }
    ];
  };
```

### Other Information

I found that you can do this with an intermediate interface struct:

```ts
interface SomeConstructProps {
  readonly propA: AProps;
  readonly propB: string;
}

interface AProps {
  readonly propAA: string;
  readonly propAB: string;
}
```

Doing this conversion automatically help a lot when there is a deep nest structure.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### CDK version used

2.132.0

### Environment details (OS name and version, etc.)

macOS

**Comment by rix0rrr** [comment]
This will most likely never happen. To support all the languages we want to support, we need the nested struct to have a name... and declaring it separately is the most obvious way to do that.
