### ISSUE TITLE
Add Kotlin as a target language?

### ISSUE THREAD

**Issue by digitalsanctum** [aws/jsii#451]
I started work to add Kotlin as a supported language of AWS CDK a while back. I've begun the work here and it's been a journey :) I'm starting to wonder if it's worth the effort given that Java is available already. My initial motivation was to make heavy use of data classes instead of the builders that are found everywhere in the CDK along with other Kotlin niceties where it makes sense. What do others think? Should I continue this work or pivot and possibly contribute to jsii and the CDK in other ways?

For reference, my fork is here: https://github.com/digitalsanctum/jsii

**Comment by digitalsanctum** [comment]
Related CDK issue: https://github.com/awslabs/aws-cdk/issues/557

**Comment by GrahamLea** [comment]
My 2c: 
* I'm not convinced a full Kotlin version of the whole API adds significant value over the Java version.
* A Kotlin version of the existing Java/Maven template would be great.

**Comment by RomainMuller** [comment]
We have some work going on in #957, and we definitely think there is value in having native Kotlin bindings generated.

**Comment by GrahamLea** [comment]
@RomainMuller Still going? It looks dormant for ~5 months.

**Comment by RomainMuller** [comment]
> @RomainMuller Still going? It looks dormant for ~5 months.

Yes you could see it as dormant at the moment; but we haven't abandoned the idea though.

**Comment by RomainMuller** [comment]
Closing in favor of #1541
