### ISSUE TITLE
Reconsidering using interfaces for props objects in Java and .NET

### ISSUE THREAD

**Issue by fulghum** [aws/jsii#480]
Java/.NET UX research showed that users sometimes tripped over the property object interfaces when learning the API.  IDE suggestions to implement the interface type often left UX participants confused and stuck.  

The interfaces make sense in TypeScript, but don't seem to add as much value in Java or .NET.

**Comment by fulghum** [comment]
Discussed this one today; Romain is going to investigate if we need support for multiple inheritance.

**Comment by RomainMuller** [comment]
There is at least one case in the CDK that leverages multiple struct inheritance, and that is on a `stable` API, meaning we cannot break this before we hit CDK 2.0. So at least for now, we have to keep retaining interfaces so we can support all kinds of polymorphisms that the TypeScript language idiom allows for 🙁
