### ISSUE TITLE
Better descripts about Labels usage

### ISSUE THREAD

**Issue by rrezino** [aws/jsii#485]
I'd like to start contributing to the project and for that, I'm reading the available documentation plus checking the open issues/topics, etc. 
But I didn't find clear information about the Label which are being used for this project (I can guess) but I'm not sure. 
For instance p0, p1, p2. I think it's phase 0, 1, 2. But again I'm just guessing. 
Did I miss something in the documentation? If not, can someone write the descriptions on the label list?

Thanks

**Comment by NGL321** [comment]
Hey @rrezino,

I apologize for the long delay in response.
Many of the labels (specifically the ones without descriptions, or with ambiguous descriptions) are for internal team use.
If you are still interested in contributing, all help is welcomed!

😸
