### ISSUE TITLE
java: Improve use of Builder pattern

### ISSUE THREAD

**Issue by fulghum** [aws/jsii#488]
UX Research Feedback – Customers have commented that the use of Builder objects for CDK function prop objects does not feel idiomatic.  They find passing in a builder as the third param for construct construction inconsistent with other Java APIs and the builder pattern.  

Customers expected to see the Builder pattern either used entirely for constructing constructs, or not at all in the constructor.

**Comment by RomainMuller** [comment]
The design we are going for is:

```
Table configTable = TableBuilder.builder(this, "configTable")
        .tableName(configTableInfo.getDynamoTableName())
        .billingMode(BillingMode.PAY_PER_REQUEST)
        .serverSideEncryption(true)
        .partitionKey(Attribute.builder()
                .name(tableMeta.getPartitionKeyField().getAttributeName())
                .type(pkType)
                .build())
        .build();
```
