### ISSUE TITLE
Configuration for executing jsii applications

### ISSUE THREAD

**Issue by fulghum** [aws/jsii#490]
Customer UX Feedback – customers tried to execute a jsii application in their IDE (Java in IntelliJ), but got errors about JSII_OUTPUT_DIR not being set.  Customers expect to be able to run code from within their IDE, just like non-jsii code.  We should see if we can default an configuration and if there are other problems customers would hit here.

**Comment by eladb** [comment]
Are you should this was `JSII_OUTPUT_DIR` and not `CDK_OUTDIR` or perhaps was it `JSII_RUNTIME`?
