### ISSUE TITLE
jsii: inherit docs and tags from supertypes, even if hidden

### ISSUE THREAD

**Issue by rix0rrr** [aws/jsii#510]
For maximum usability, we should be inheriting member docstrings (and doctags) from supertypes, even if they are not exported.

This reduces unnecessary typing for users.

We should only inherit for the constructor if the signature is the same.

**Comment by eladb** [comment]
Yes! I was even thinking that we should encourage/enforce not adding docstrings on overrides so that there's a single source of truth (and then we can duplicate them in the assembly).

**Comment by rix0rrr** [comment]
So TypeScript does a bit of this already for us. If there are no docstrings on a member and there are docstrings on the member it inherits from, the compiler will feed us the right inherit docstring.

It does not work for constructors yet, nor does it work for merging doc blocks (for example, docs for arguments could be inherited from a parent while summary/remarks are taken from the current docstring).
