### ISSUE TITLE
.NET: ToString() should override from Object

### ISSUE THREAD

**Issue by rix0rrr** [aws/jsii#533]
Warnings right now:

```
@aws-cdk/cdk: IResolvableWithPostProcessProxy.cs(36,23): warning CS0114: 'IResolvableWithPostProcessProxy.ToString()' hides inherited member 'object.ToString()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword. [/tmp/jsii-pacmak-codenO5qGD/Amazon.CDK/Amazon.CDK.csproj] 
```

This is wrong, it should override.

**Comment by assyadh** [comment]
I *think* I fixed this already in the new generator: 

https://github.com/aws/jsii/blob/hamzaad/dotnet-generator-redux/packages/jsii-pacmak/lib/targets/dotnet/dotnetgenerator.ts#L407

The required work is to make sure the warning are not showing anymore.

**Comment by assyadh** [comment]
This was indeed fixed with the new generator:

https://github.com/aws/jsii/blob/master/packages/jsii-pacmak/lib/targets/dotnet/dotnetgenerator.ts#L400
