### ISSUE TITLE
jsii does not populate .jsii.types with the exported types

### ISSUE THREAD

**Issue by Console32** [aws/jsii#546]
I try to generate a aws cdk component library for multiple languages using jsii. But I got Problems finding the types in the packages.

After further investigation i can reproduce the problem with the Getting Start (Hello World) example of Jsii. The types section of my .jsii file stays empty after i run `npm run build`.

The package.json looks like this:
```
{
  "name": "JsiiDemo",
  "version": "1.0.0",
  "description": "",
  "main": "lib/index.js",
  "types": "lib/index.d.ts",
  "author": {
    "name": "tbd",
    "email": "tbd",
    "url": "tbd"
  },
  "repository": {
    "type": "git",
    "url": "tbd"
  },
  "scripts": {
    "build": "jsii",
    "watch": "jsii -w",
    "package": "jsii-pacmak -v"
  },
  "jsii": {
    "outdir": "dist",
    "targets": {
    }
  },
  "keywords": [],
  "license": "ISC"
}
```

The index.ts contains the mentioned Hello World example

```
export class HelloJsii {
    public sayHello(name: string) {
        return `Hello, ${name}!`
    }
}
```

the generated .jsii file when i run npm run build:

``` 
{
  "author": {
    "email": "tbd",
    "name": "tbd",
    "roles": [
      "author"
    ],
    "url": "tbd"
  },
  "description": "JsiiDemo",
  "homepage": "tbd",
  "jsiiVersion": "0.11.3 (build 464b8c6)",
  "license": "ISC",
  "name": "JsiiDemo",
  "repository": {
    "type": "tbd",
    "url": "tbd"
  },
  "schema": "jsii/0.10.0",
  "targets": {
    "dotnet": {
      "namespace": "Acme.HelloNamespace",
      "packageId": "Acme.HelloPackage"
    },
    "java": {
      "maven": {
        "artifactId": "hello-jsii",
        "groupId": "com.acme.hello"
      },
      "package": "com.acme.hello"
    },
    "js": {
      "npm": "JsiiDemo"
    },
    "sphinx": {}
  },
  "types": {},
  "version": "1.0.0",
  "fingerprint": "EDUVQkx8nALpGPa3ftKyU6xSbu9Rwc18WGx9yBpyX/A="
}
```

does not match the expected output as mentioned in the README.md [here](https://github.com/awslabs/jsii#what-kind-of-sorcery-is-this)

I am on windows, nvm 6.7, nodejs 11.15

**Comment by Console32** [comment]
The problem is windows related, if I run the npm run build on WSL it works as expected

**Comment by RomainMuller** [comment]
That's very odd. I'm going to guess this is a path-parsing related issue, because that's the usual suspect for this type of issues.

**Comment by RomainMuller** [comment]
Alright it was likely a `\`-related thing... And I've done a pass through all our Windows bugs and we are now testing our codebase on Windows, too... Hopefully this will be fixed in the next JSII release!!
