### ISSUE TITLE
Cannot serialize non-jsii enums

### ISSUE THREAD

**Issue by Kent1** [aws/jsii#559]
Hi,

I use AWS CDK for building my cloudformation stacks.
I wanted to pass in the context the name of the environment in order to parameterized my stack.

So i created an Enum class Environment like this one
```Java
public enum Environment implements software.amazon.awscdk.core.Environment {
  Dev, Acc, Prod;

  @Override
  public String getAccount() {
    return "12345678901";
  }

  @Override
  public String getRegion() {
    return "eu-west-1";
  }
}
```

However, when i pass this Environment in my StackProps, i get the following error : `Error: Cannot serialize non-jsii enums`

Can we make enum serializable if they implement JsiiSerializable ?
Or am I doing something wrong ?

Quentin

**Comment by RomainMuller** [comment]
The fact the enum implements `core.Environment` should have been enough here. That's a particularity of Java enums that we have failed to account for.

In principle, implementing `JsiiSerializable` you could make it work, but that seems like an awful amount of work for something that should work out of the box.

I've converted this to a `feature-request` as this is currently a feature gap.

**Comment by lohithsamaga** [comment]
Hi,
I am interested.
Using Java enums is useful when creating EventBridge rules.

Can you please implement this feature?
Thanks in advance.
