### ISSUE TITLE
Main readme.md is incorrect

### ISSUE THREAD

**Issue by CyrusNajmabadi** [aws/jsii#572]
It looks like jsii performs many additional checks that are not documented, and not part of the main readme.  For example:

```
cyrusn@DESKTOP-UVPENCH ~/go/src/github.com/pulumi/pulumi/jsii[master ≡ +1 ~0 -0]> npm run build

> experiments@1.0.0 build /home/cyrusn/go/src/github.com/pulumi/pulumi/jsii
> jsii

Error: Error: The "package.json" file must specify the "author.name" attribute
    at _required (/home/cyrusn/go/src/github.com/pulumi/pulumi/jsii/node_modules/jsii/lib/project-info.js:149:15)
```

It's not clear why that attribute is required.  Then:

```
cyrusn@DESKTOP-UVPENCH ~/go/src/github.com/pulumi/pulumi/jsii[master ≡ +1 ~0 -0]> npm run build

> experiments@1.0.0 build /home/cyrusn/go/src/github.com/pulumi/pulumi/jsii
> jsii

Error: TypeError: Cannot read property 'url' of undefined
    at Object.loadProjectInfo (/home/cyrusn/go/src/github.com/pulumi/pulumi/jsii/node_modules/jsii/lib/project-info.js:71:43)
```

This is a straight crash.  Without the source it wouldn't be possible to even know what to fix here.  This is happening due to a missing "repository" section (also not in readme).

**Comment by ozbillwang** [comment]
Got the same. Could the repo owner creates an example folder with several examples for quick references.

**Comment by RomainMuller** [comment]
Hey,

The `README` document has been since improved.
The idea of adding an examples folder is a good one! I'll create a separate issue to track this.

Regards,
Romain.
