### ISSUE TITLE
cannot find mechanism to override marshalling behavior

### ISSUE THREAD

**Issue by CyrusNajmabadi** [aws/jsii#575]
In our project we use some fairly complex typescript types.  When exposing or consuming these types in the generated python, we'd like to be able to control how the marshalling works.  For example, we have a type that can represent something that is similar to  Promise.  We'd like to be able to marshall that to/from a Python asyncio.Task or asyncio.Future. 

Is such a thing possible?  I can see in the .net side of thing there is an IJsiiToFrameworkConverter, and it may be possible to construct things (maybe using ServiceContainer) to use our own custom converter.

However, it's unclear to me how i would do the same for python.  Is there a jsii 'escape hatch' as it were to give control over the sorts of common TS concepts that JSII currently can't handle?

**Comment by unicomp21** [comment]
Ditto, asyncio support would rock.  In fact, I think if we can this thing batching sufficiently across the ipc/marshaling boundary, combined w/ head use of ValueTask in .net core, and python asyncio Queue, etc., we could get really good throughput.
