### ISSUE TITLE
TS arrays are projected into .net arrays.  But changes to .net array aren't reflected on TS side.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [aws/jsii#582]
This code:

```ts
export class HelloJsii {
    public strings: string[];

    constructor() {
        this.strings = ["a", "c", "c"];
    }
}
```

Produces c# code like:

```c#
        public virtual string[] Strings
        {
            get => GetInstanceProperty<string[]>();
            set => SetInstanceProperty(value);
        }
```

AFAICT, this just won't work properly for a couple of reasons:

1. any mutations on the .net side (for example, setting a value into that array) won't be seen on hte TS/js side.
2. any mutations on the TS/JS side (for example, pushing a new element, or changing an array element) won't be seen on the .net side.

It appears as if class instances try to stay connected to the underlying TS/JS object.  However, collection instances do not.  They can diverge and the .net side must constantly re-request the same property to get the 'current' snapshot of the TS/JS side.

I'm not sure if this is an issue for python.

**Comment by MrArnoldPalmer** [comment]
This is why most properties in JSII classes are readonly and can't be set through property access + assignment. We have to have some sort of way of knowing when properties change on either side of the host/node process. Usually this is done with methods. If the property on the class can be changed post construct, the user must call a method on the class to do so which lets us pass that value into the JSII runtime and receive changes back into the host.

Let me know if this doesn't answer your question.
