### ISSUE TITLE
Trying to make async function produces:  error TS9999: JSII: Non-primitive types must have a symbol

### ISSUE THREAD

**Issue by CyrusNajmabadi** [aws/jsii#584]
This simple code:

```ts
export class HelloJsii {
    public strings: string[];

    constructor() {
        this.strings = ["a", "c", "c"];
    }

    public async applyAsync(): Promise<void> {
    }
}
```

Produces: 

```
lib/index.ts:11:5 - error TS9999: JSII: Non-primitive types must have a symbol
```

Is that expected?  Are Promises a supported construct fro jsii?  It seems like tehy could potentially marshall to/from equivalent constructs at least in some platforms (i.e. Task/TaskCompletionSource in .net).

**Comment by RomainMuller** [comment]
Hey @CyrusNajmabadi  - this might be because of an incorrect handling of the `Promise<void>` return type. I think it tries to find the symbol for the promise return type...

**Comment by SomayaB** [comment]
Closing this issue since there hasn't been a response in a while. Feel free to reopen.
