### ISSUE TITLE
.Net CDK isues stemming from jsii?

### ISSUE THREAD

**Issue by McDoit** [aws/jsii#594]
I have a couple of issues related to .Net usage  of the CDK framework, that I think might be coming from underlying issues in the jsii

Should I report these issues here directly, or does the CDK team take them here?

The issues I'm currently suffering from:

https://github.com/awslabs/aws-cdk/issues/2362
https://github.com/awslabs/aws-cdk/issues/2375
https://github.com/awslabs/aws-cdk/issues/2496
https://github.com/awslabs/aws-cdk/issues/2613
https://github.com/awslabs/aws-cdk/issues/3280

**Comment by assyadh** [comment]
Relates: https://github.com/aws/jsii/pull/703 - this will fix the first issue

**Comment by assyadh** [comment]
Remaining original issues:

https://github.com/aws/aws-cdk/issues/2375
https://github.com/aws/aws-cdk/issues/2496

**Comment by assyadh** [comment]
Remaining issue: aws/aws-cdk#2375

aws/aws-cdk#2496 is getting fixed here: https://github.com/aws/jsii/pull/736

**Comment by McDoit** [comment]
One big showstopper now is the https://github.com/aws/aws-cdk/issues/3244 bug, it affects almost every single CDK resource created and is impossible to work around, or do you have any recommendations for it?

**Comment by kuhnboy** [comment]
My work around for now was to downgrade to 0.28.0 -- which will affect certain constructs though such as VPC and tagging as those methods changed around 0.29.0 or 0.30.0.

**Comment by assyadh** [comment]
> One big showstopper now is the [aws/aws-cdk#3244](https://github.com/aws/aws-cdk/issues/3244) bug, it affects almost every single CDK resource created and is impossible to work around, or do you have any recommendations for it?

Hi @McDoit , I have a fix in PR (wip): https://github.com/aws/jsii/pull/772

**Comment by assyadh** [comment]
Latest version of the runtime is out with the fix.
