### ISSUE TITLE
Auto-detect breaking changes and enforce semver

### ISSUE THREAD

**Issue by eladb** [aws/jsii#63]
Since jsii understands the API of a module, we can determine if there were breaking changes between two versions of the API. This is a very powerful capability and we should introduce it early in the game. This also ties nicely into the desire to review API changes via the normal code review process.

The low-level building block consists of a capability to compare two jsii specs and determine if the changes are minor or major based on the semver specification. The [india](https://github.com/bcherny/india) library implements a similar approach based on these [rules](https://github.com/bcherny/india/blob/master/rules.js) (maybe we can use india or extends it somehow to support jsii specs).

Now that we have the ability to compare two jsii specs, we should consider a mode for the compiler to automatically detect breaking changes. This will require checking-in the jsii spec of the module into source control and adding an option to fail the build in case breaking changes are introduced. The workflow (which is not flushed out yet) should also support enforcing version bumps based on the type of changes. See [semantic-release](https://github.com/semantic-release/semantic-release) - perhaps we can plug into it somehow so this will integarte with our release process.

**Comment by RomainMuller** [comment]
`jsii-diff` achieves this
