### ISSUE TITLE
use J2V8 to optimize java JSII runtime

### ISSUE THREAD

**Issue by sam-goodwin** [aws/jsii#642]
I stumbled across J2V8 which provides a high performance binding between Java and V8:

https://github.com/eclipsesource/j2v8

I'm wondering if this would help optimize the Java JSII runtime.

**Comment by eladb** [comment]
This is cool, but we need more than v8. jsii modules can use the node.js APIs and the packaging story is coupled with npm.

**Comment by sam-goodwin** [comment]
Ah, fair enough. The JNI strategy might be interesting to keep in mind if optimizations become a priority. 

This can probably be resolved.
