### ISSUE TITLE
jsii-publish

### ISSUE THREAD

**Issue by eladb** [aws/jsii#649]
We should extract all the publishing code from [aws-delivlib](https://github.com/awslabs/aws-delivlib) into a `jsii-publish` tool that can be used in CI/CD systems to publish jsii modules without hassle.

**Comment by udondan** [comment]
If anyone is interested, I created a docker image / GitHub action which can build and publish the artifacts. (Maven not supported yet)

https://github.com/marketplace/actions/jsii-publish
