### ISSUE TITLE
Unable to pass python package metadata

### ISSUE THREAD

**Issue by afthar** [aws/jsii#656]
I'm passing Python package data in package.json as follows:
```
"targets": {
      "python": {
        "author": "memycompany",
        "name": "da-cdk",
        "version": "0.2",
        "description": "hellojsii",
        "package": "package-hellojsii",
        "testItem": "testItemValue"
      }
    }
```
and getting `UNKNOWN-0.1.4-py3-none-any.whl` as a package name. Please advise how to properly build python package. Thanks

**Comment by RomainMuller** [comment]
The supported settings for the `python` target are:
- `distName` (the name of the listing on PyPI)
- `module` (the name of the Python module

The `author`, `version`, and `description` are taken from the `package.json` standard fields for the same semantics.

**Comment by afthar** [comment]
awesome, you've just made my day @RomainMuller, thanks
