### ISSUE TITLE
Python package information doesn't include license information

### ISSUE THREAD

**Issue by eladb** [aws/jsii#707]
https://github.com/aws/jsii/blob/32bc117025cc7fd7ee48bab0d524ab8f772abb77/packages/jsii-pacmak/lib/targets/python.ts#L1159

**Comment by RomainMuller** [comment]
I submitted a draft PR (#712) to this effect. The caveat right now is that the only licensing information I have available is the SPDX short identifier, which I can turn into the SPDX license name -- however it appears that the PyPI classifiers don't use the standard license names, as can be observed at https://pypi.org/classifiers/, the `License :: OSI Approved :: Apache Software License` would seem to be the only option to match all versions of the `Apache` licenses...

I haven't investigated other licenses as of yet, but this might require manual mapping which doesn't sound pleasant... 😩
