### ISSUE TITLE
Increase heap memory for jsii engine 

### ISSUE THREAD

**Issue by bverhoeve** [aws/jsii#745]
## :rocket: Feature Request
When using JSII for small AWS CDK applications, the JSII kernel will normally not run out of heap memory. However, for larger apps (>800 resources, multiple stacks), depending on the complexity, you can encounter the following error: `FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory`.

Is there already a way to increase the Javascript heap memory beyond the default value?

### Affected Languages

- [ ] `TypeScript` or `Javascript`
- [x] `Python`
- [ ] `Java`
- [ ] .NET (`C#`, `F#`, ...)

### General Information
* **JSII Version:** v0.15
* **Platform:**     UNIX

* [ ] I may be able to implement this feature request

* [x] This feature might incur a breaking change

### Description
Add a setting in the `cdk.json` file which specifies the maximum allowed heap memory that `jsii` can allocate. Set the maximum heap memory then to this setting.

**Comment by RomainMuller** [comment]
I don't think we can host this setting in `cdk.json` (because JSII can be used in contexts other than `cdk`).

Ability to customize the `node` runtime is however a very interesting idea and we should dig into this further. We should also consider what other aspects of the `node` runtime we could/should allow users to control.

**Comment by RomainMuller** [comment]
Note that in the meantime, you can pass additional arguments to the `node` process by setting the `NODE_OPTIONS` environment variable. In particular, controlling the max heap size can be achieved using:

```bash
# Sets the maximum heap to 4GiB
NODE_OPTIONS='--max-old-space-size=4096'
```

**Comment by bverhoeve** [comment]
Does `jsii` always use the system `node` installation to run? Or does it use another kernel?

If the system `node` is the case, the `NODE_OPTIONS` is quite nice already as a workaround :)

**Comment by bverhoeve** [comment]
@RomainMuller the `NODE_OPTIONS` variable works for increasing the max heap size, but unfortunately not the call stack size. This can be changed by using `node` with the `--stack_size` option set to a certain value. Unfortunately, the `--stack_size` option can't be set yet using `NODE_OPTIONS`.

**Comment by RomainMuller** [comment]
Ah - an alternate way to solve this until we actually support acting on those settings via configuration is to create a wrapper around `node` that is ahead of the *real* node in your `$PATH`, something along the lines of (warning: I haven't tested it):

```bash
#!/bin/bash

/usr/local/bin/node --stack_size=4096 $@
```

**Comment by ansgarm** [comment]
We recently encountered this as well in the CDK for Terraform when generating provider bindings for the AWS Terraform Provider for Go.  

Here is a [small example](https://github.com/ansgarm/cdktf-go-aws-oom-jsii) which can be used to reproduce the issue or to do some profiling.
For now we went the route of [setting](https://github.com/hashicorp/terraform-cdk/blob/633c9136ed241db6e3aa4e8d67e178766a63032e/packages/cdktf-cli/lib/get/constructs-maker.ts#L285) `NODE_OPTIONS` on `process.env` so it is made available to the child process for `jsii-pakmak` which is spawned by `jsii-srcmak` (which we use). While this seems like an okayish fix, I'm still a bit confused why the memory usage is that heavy.  
  
Do you have any pointers where one might start digging, @RomainMuller? We're experiencing this particularly with Go (to this 7 GB extent 🏋️😄)
