### ISSUE TITLE
jsiiSpec Constructor

### ISSUE THREAD

**Issue by rhboyd** [aws/jsii#769]
### Affected Languages
- [X] `TypeScript` or `Javascript`

### The Question
I'm assuming that because the jsii-spec/lib/assembly doesn't include a Constructor there isn't a straightforward way to pass a `.jsii` JSON blob to it and get a well-formed assembly out of it, is this correct? What I'm trying to do is take a given `.jsii` file and be able to make some assumptions about what properties it has.

**Comment by eladb** [comment]
I think you are looking for [jsii-reflect](https://www.npmjs.com/package/jsii-reflect).

**Comment by rhboyd** [comment]
Cool. thanks. I'll dig into it.

**Comment by rhboyd** [comment]
I'm trying to build a typescript app into JS so I can run it in a Lambda. When I add the `import { TypeSystem } from 'jsii-reflect';` command to my `index.ts` I get the following error when I try to invoke my Lambda:
```
Unable to import module 'app': Error
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
``` 

inside the `node_modules` folder in the lambda, my IDE is complaining about the `tsconfig.json` for the jsii-reflect package.

```
"references": [
        { "path": "../jsii" },  <- undelined in red ( I also don't have any jsii files at the directory this is pointing to)
        { "path": "../jsii-spec" },
        { "path": "../oo-ascii-tree" }
    ]
```

**Comment by rhboyd** [comment]
I think this error might be a different issue. I tried to remove all the references to jsii-reflect and delete the `node_modules` directory and the error is still there.

**Comment by rhboyd** [comment]
fixed it. I tried to be clever and build a TS app from scratch instead of using a template and ended up with the node_modules folder in the wrong place.
