### ISSUE TITLE
.NET Nuget packages should have an icon

### ISSUE THREAD

**Issue by assyadh** [aws/jsii#773]
The packages right now lack icons in Nuget/nuget gallery.

Example:

https://www.nuget.org/packages/Amazon.JSII.Analyzers/

We can just use the SDK one.

**Comment by assyadh** [comment]
Updated the generator to include a PackageIconUrl node based on the package.json of the CDK construct.

Remaining work is to backfill all the CDK constructs with https://sdk-for-net.amazonwebservices.com/images/AWSLogo128x128.png

**Comment by RomainMuller** [comment]
We don't have a dedicated icon for `jsii` as of yet, though.

**Comment by assyadh** [comment]
Discussed this with @elad and we can use the github /logo/ folder files, with the cdn endpoint.

**Comment by assyadh** [comment]
Right, we can use the CDK one for the CDK constructs, but for Jsii related packages, one will be needed.
