### ISSUE TITLE
Python runtime: log IO before encoding/decoding

### ISSUE THREAD

**Issue by rix0rrr** [aws/jsii#793]
## :rocket: Feature Request

The Python runtime first decodes JSON, then prints to stderr  afterwards (if `JSII_DEBUG` is set).

That means if JSON decoding fails (for whatever reason), we have no way to determine from the log what the offending line was. 't Were better if it was the other way around, log first THEN try to decode.

Observed in https://github.com/aws/aws-cdk/issues/4102

**Comment by RomainMuller** [comment]
In fact the Python runtime *never* writes to `stderr`. All the logs observed in the `JSII_DEBUG` trace of aws/aws-cdk#4102 (except the traceback) are coming from the `jsii-kernel`.

Now I agree - the JSON parsing error should probably be caught and the text that caused it to occur should be mentioned in the error.
