### ISSUE TITLE
jsii kernel gives quite unhelpful error message when serializing a function

### ISSUE THREAD

**Issue by rix0rrr** [aws/jsii#806]
## :bug: Bug Report

Now obviously, functions should never get passed to the jsii kernel to serialize, so this is already a bug. But if they do:

```
jsii.errors.JavaScriptError: 
  Error: Resolution error: JSII kernel assumption violated, undefined is not an object.
```

Upon reading this error message you'll tear out your hair trying to figure out how this is possible, because no code path looks like it should allow `undefined` at that point.

This is because:

```
> JSON.stringify(function() { return 666; })
undefined
```

Thanks JavaScript! 

Anyway, explicitly testing for functions using `typeof value === 'function'` and throwing a more appropriate error message would be VERY VERY helpful.

**Comment by RomainMuller** [comment]
The error message was improved & now provides a suggestion as per a probable cause, too.
