### ISSUE TITLE
Kernel silently ignores additional properties when deserializing structs

### ISSUE THREAD

**Issue by RomainMuller** [aws/jsii#822]
### Affected Languages

- [ ] `TypeScript` or `Javascript`
- [X] `Python`
- [X] `Java`
- [X] .NET (`C#`, `F#`, ...)

### General Information
* **JSII Version:** `0.17.0`

### What is the problem?
The kernel struct deserialization silently ignores any properties that the type does not declare. When deserializing type unions where the first candidate has no required property, this means serialization will ignore everything and succeed (resulting in an empty object), instead of attempting the next candidate type.

This is the root cause of aws/aws-cdk#3917

**Comment by nija-at** [comment]
Capturing context from https://github.com/aws/aws-cdk/issues/3917, this is impacting the use of L1 constructs from the SAM module.

**Comment by RomainMuller** [comment]
An "easy" solution here involves throwing an error when encountering an un-modeled property instead of ignoring it; however this means the various runtimes may not serialize additional properties; which may require adding code there to this effect.

**Comment by nija-at** [comment]
Another instance of this in Java identified from a customer report - https://github.com/aws/aws-cdk/issues/2013
