### ISSUE TITLE
allow adding additional files to tsconfig

### ISSUE THREAD

**Issue by eladb** [aws/jsii#965]
Maybe we should add a feature request to `jsii` to support adding files to the `includes` clause... We already support injecting `exclude` clauses......

_Originally posted by @RomainMuller in https://github.com/aws/aws-cdk/pull/4946_

**Comment by RomainMuller** [comment]
I think I would rather handle it in allowing users to basically won and control the `tsconfig.json` file and simply ensure they're compatible with `jsii` requirements...

**Comment by zxkane** [comment]
This issue has been inactive for a while, any plan to implement it. #1644 #2071 also requires this feature.  

It’s a blocking issue for below scenario,

The library has some static assets not ending with `.ts` extension, the hardcode `include` in tsconfig can not package them to output folder.

**Comment by nickehunt-idm** [comment]
See my updated issue on this, any progress / options for this?
